<html>
<head>
<title></title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<META name="Description" content="Adult Content Disclaimer">
<META name="Keywords" content="San Francisco escorts, escorts services, escort providers, call girl escorts, escort directory, san francisco escort, escort services, full service escorts, california escort service, oakland escorts, san jose escorts, asian escorts, black escorts, cityvibe escorts">
<META name=city content="San Francisco Bay and Sacramento">
<META name=state content="CA">
<META name=Robots content=all>
<META http-equiv="Revisit-After" content="10 days">
<META name="Copyright" content="CA escort ads lovings.com 1996-2009 copyright">
<link rel="meta" href="http://www.lovings.com/labels.rdf" type="application/rdf+xml" title="ICRA labels" />
<script language="JavaScript" type="text/JavaScript">
<!--
function MM_reloadPage(init) {  //reloads the window if Nav4 resized
  if (init==true) with (navigator) {if ((appName=="Netscape")&&(parseInt(appVersion)==4)) {
    document.MM_pgW=innerWidth; document.MM_pgH=innerHeight; onresize=MM_reloadPage; }}
  else if (innerWidth!=document.MM_pgW || innerHeight!=document.MM_pgH) location.reload();
}
MM_reloadPage(true);
//-->
</script>
<link href="../_css/category.css" type=text/css rel=stylesheet>
<style type="text/css">
<!--
.style1 {
	color: #FF0000;
	font-weight: bold;
}
-->
</style>
</head>
<body class="splash">
&nbsp;&nbsp;
<div id="blahpage">
  <CENTER>
    <p><STRONG><FONT size="3">This site contains adult   material</FONT></STRONG></p>
    <p><A href="#adult">Adult Warning</A> <A href="#viewing">Viewing Content</A> <A href="#posting">Posting Content</A> <A href="#refunds">Refunds</A> <A href="#blocking">Parental Blocking</A> <A href="#liability">Warranty and   Liability<BR>
    </A><A href="#interruptions">Interruptions   and Discontinuances</A> <A href="#privacy">Privacy</A> <A href="#spam">Spam and   Emails</A> <A href="#records">18 U.S.C. 2257</A> <A href="#copyright">Copyright   Infringement</A></p>
  </CENTER>
  <p align="left"><A id="adult" title="adult" name="adult"></A>Warning! These website contains adult material that may be   offensive to some readers, somewhere.</p>
  <p align="left">If you are under 21 years of   age or if it is illegal to view adult oriented material in your community,   please go away now. Shoo! This site is not so rounchy anyway, you will be dissapointed... We cannot be held responsible for your actions. We are   not acting in any way to send you this information, you are choosing to receive   it. If you continue past this point, you understand and accept the   responsibility for your own actions, thus releasing Lovings, Inc as well as our   service provider from all liability.</p>
  <p align="left"><FONT color="#ff0000"><STRONG><FONT color="#000000">By entering this site, you certify that you have full knowledge   that it contains adult material. Furthermore, you are certifying that the   viewing, reading and downloading of the files in this web site does not violate   the community standards of your street, village, city, town, country, state,   drum circle or province. </FONT></STRONG></FONT><FONT color="#000000"><STRONG>Do not continue unless   you know your local laws do not prohibit the viewing of sexually explicit   materials. Ignorance is not a defense.</STRONG></FONT></p>
  <p align="left">You also certify that you   are wholly liable for any false disclosures and you are responsible for any   legal ramifications that may arise from the viewing, posting, reading or   downloading of files or material contained within this web site. You are also   fully responsible for any legal ramifications that may result as a result of   fraudulent entry into or use of this web site.</p>
  <p align="left"><FONT color="#ff0000">Lovings, Inc is not the author of the classified   ads on this web site, and presents no guarantees of veracity of any statements, nor nature or quality of services listed.</FONT></p>
  <p align="left"><STRONG>Agreements: </STRONG></p>
  <p align="left"><STRONG><A id="viewing" title="viewing" name="viewing"></A>Viewing content:</STRONG> 1.I am at least 21   years of age; 2.The material I'm viewing is for my own personal use and isn't to   be viewed by minors or anyone but myself; 2.I desire to receive and haven't   requested that the Postal Service or any Other Governmental Agency intercept   sexually explicit material; 3.I can STOP receiving such material at any time by   logging off now and not returning; 4.I believe that as an adult, I've the   unalienable right to read and / or view any type of material that I choose; 5.At   no time, will minors be subjected to said material of any kind; 6.By using links on the home page and / or by looking at anything on this site, I am   agreeing that the material contained herein is not obscene or offensive in any   way nor ever will be considered obscene or offensive. I also certify that the   material presented here is not illegal or considered obscene in my street,   village, community, city, state, country or province. If I am unsure, I will not   continue; 8. I have a sense of humor; 9. I'm not drunk, or under the influence   of drugs that can impede my judgment or give me an excuse to say "I didn't mean   it" later;</p>
  <p align="left"><STRONG><A id="posting" title="posting" name="posting"></A>Placing an ad:</STRONG> 1. If I contact Lovings, Inc in order to advertise on any of the Lovings, Inc owned sites, I certify that I have the right to all the materials   I made available to Lovings, Inc, and said materials do not violate any copyright laws.<STRONG> I also certify that I understand that any vulgar, obscene   or X-rated statements or materials will be removed or edited at the Publisher's   discretion. </STRONG></p>
  <p align="left">I certify that I am pictured   in and have the right of use of the Content provided to Lovings, Inc for the   purpose of advertising and that I am in full legal possession of the Content. I   further certify that all Content is produced in accordance with all applicable   provisions of the Child Protection Restoration and Penalties Enhancement Act and   are fully compliant with all requirements of 18 U.S.C.&sect; 2257 and all other   applicable Federal, State and Local laws and regulations.</p>
  <p align="left">I certify that I and all the   individuals pictured or discussed in Content submitted fully understand that the   submitted Content is to be used in relation to adult entertainment   advertisement/promotion including publishing of the Content on Internet World   Wide Web. The I certify that the advertising posted is not to be used for   promotion of any illegal activities. I certify that the identification (IDs)   provided in order to post photos/visual materials is true legal documents   belonging to me, and I take full legal and criminal responsibility for that   statement. <STRONG>I understand that in case that the fraudulent ID documents   were provided, Lovings, Inc upon discovery reserves the right to immediately   remove any advertisements and take other steps, including but not limited to   such as notifying proper authorities and a permanent ban of the Undersigned   and/or any agents from advertising on Lovings, Inc Web Sites, and that no credit   nor refund will be issued.</STRONG></p>
  <p align="left"><STRONG><A id="refunds" title="refunds" name="refunds"></A>Refunds/Credit:</STRONG> Refunds will be issued   for non-published classifieds ONLY, including the classifieds refused on the   grounds of obscene/vulgar/illegal content, and will reflect a 10% handling   fee.<BR>
    If a Lovings, Inc web site You are advertising on is not available/offline for over 24   hours, you are entitled to a credit for the downtime only. Should you decide to   discontinue your advertising with Lovings, Incdue to an outage of over 48   hours, you are entitled to a refund equal to the time your ad is off line   ONLY.<BR>
    <BR>
    <span class="style1">There will be no refund nor credit for ads removed due to  fraudulent (fake) IDs or DMCA (copyright/ownership infringment) related takedowns. Using a fake ID is illegal, and we hate it, because we   don't want underage people on our web site - so please don't even try.</span></p>
  <p align="left"><STRONG><A id="blocking" title="blocking" name="blocking"></A>Parental blocking:</STRONG> This web site is   listed with and in compliance with the following child-blocking services:<BR>
    <A href="http://www.netnanny.com/" target="_blank">NETNANNY</A> &amp; <A href="http://www.fosi.org/about/" target="_blank">ICRA</A></p>
  <p align="left">Concerned parents, please   use the above services to block the access to our web sites. *You* are the   parent, and raising your child in a way you find fit is both your right and your   solemn responsibility. We made it easy and convenient to block  your children from accessing our web site.  Please help us and the community you live in by taking   this responsibility into your own hands.</p>
  <p align="left"><STRONG><A id="liability" title="liability" name="liability"></A>Warranty and liability:</STRONG> Lovings, Inc   makes no warranty that goods and services available through advertisers and   third party vendors will meet any particular performance or quality standards,   and disclaims all other warranties of any kind, either express or implied,   including implied warranties of fitness for any particular purpose, except to   the extent that any warranty cannot be disclaimed under applicable law. Lovings,   Inc will not be responsible nor liable for damages resulting from the use or   inability to use any goods or services available or advertised through the   Lovings, Inc site. Under no circumstances shall Lovings, Inc be liable for any   indirect, incidental, special or consequential damages or injuries, including   but not limited to, the loss of profit arising out of or in connection to the   content of Lovings, Inc site, good or services advertised or obtained through   advertisers or third party vendors. Lovings, Inc is not responsible for any   typographic errors within the site. The absolute limit of liability for any   claim including, but not limited to, claims due to the Lovings, Inc' negligence,   shall be any service fee, purchase fee or user fee paid by any claimant,   including but not limited to advertisers and third party vendors, to Lovings,   Inc in connection to the provision of services or products to the claimant by   Lovings, Inc. Lovings, Inc offers no warranty express or implied pertaining to   any destination, social area or resource listed. Lovings, Inc is not responsible   for any products or services avertised nor the quaility thereof. </p>
  <p align="left"><STRONG><A id="interruptions" title="interruptions" name="interruptions"></A>Interruptions and   Discontinuances:</STRONG> Lovings, Inc is not and will not be responsible for   interruptions or discontinuances of services including periodical system   hardware and software upgrades, system reconfiguration, or by factors beyond its   control; including, but not limited to equipment failure, delays, system   administration conflicts, negligence, strikes, police action, world wars, dogs   that eat our hard drives or acts of nature or god(s) of your choice. Lovings,   Inc will, however, upon request, offer a credit for any funds paid for the   actual Web Site off-line time if longer than 24 hours, of the value equal to the   actual advertising cost during the off-line time only. </p>
  <p align="left">Any disputes will be handled   by mediation and /or arbitration through the neutral parties mutually agreed   upon, under jurisdiction of the state of California. If either party disputes   the decisions of the mediators/arbitrators within 30 days, any further disputes   will be continued in California, under jurisdiction and laws of the state of   California. Should any of the clauses of this contract be unenforceable in the   state/county/city of residence of either party, the rest of the clauses are   still legally binding and in effect.</p>
  <p align="left"><STRONG><A id="privacy" title="privacy" name="privacy"></A>Privacy</STRONG>: Lovings, Inc does not collect   the infomation about the web site visitors, past the standard log files which   provide a measurement of web site traffic, the number of visitors and such - no   individual information. We believe in your   right to protect your privacy and follow a strict NOB policy (Not Our   Business).</p>
  <p align="left">Lovings, inc advertisers   posting photos are required to provide the indentification and the proof of age   as per 18 U.S.C. 2257 Record-Keeping Requirements Compliance law along with a   signed model release statement. All models are at least 18 years old.</p>
  <p align="left"><STRONG><A id="spam" title="spam" name="spam"></A>Spam and emails:</STRONG> Lovings, Inc does not spam.   Any affiliates or other business associates of Lovings, Inc caught spamming will   be immediately removed, the business association severed, and any funds witheld.   Any third party e-mail addresses in Lovings, inc possesion will not be released   to other parties except by express written permission of the email owner. We are   serious about this, folks. Lovings, Inc receives over a 2000 spam messages   daily, which makes us really pissed off on this issue. Any spammers will be   canned! *Any spam that promotes sexual abuse of children will be immediately reported to the authorities. **Spam adressed to &quot;Webmistress&quot; that promotes penis growth is just plain annoying.</p>
  <p align="left">We will occasionally contact the current and past advertisers with special promotions and site news. These emails will be sent no less than 1 month apart. You can opt out by using the appropriate &quot;Opt out&quot; link in the email. Your email will never be sold or made available to third parties.</p>
  <p align="left"><STRONG><A title="records" name="records"></A>18 U.S.C. 2257 Record-Keeping Requirements Compliance   Stetement:</STRONG> All models and other persons that appear in any visual   depiction of actual sexually explicit conduct appearing or otherwise contained   in this Website were over the age of eighteen years at the time of the creation   of such depictions. Some of the aforementioned depictions appearing or otherwise   contained in or at this site contain only visual depictions of actual sexually   explicit conduct made before July 3, 1995, and, as such, are exempt from the   requirements set forth in 18 U.S.C. &sect; 2257 and C.F.R. 75. The owners and   operators of this Website are not the primary producer (as defined in 18 U.S.C.,   section 2257) of the visual content contained in the Website except for the   photographs created by Lovings, inc and identified by copyright &copy;Lovings.com.   With regard to the photographs by Lovings, Inc and the remaining depictions of actual sexual conduct appearing or   otherwise contained in this site, the records required pursuant to 18 U.S.C. &sect;   2257 are kept in the following location by the corresponding Custodians of   Records:</p>
  <p align="left">ATTN: Custodian of   Records<BR>
    Lovings, Inc.<BR>
    1914A Clement Street<BR>
    San Francisco, CA   94121</p>
  <p align="left"><STRONG><A id="copyright" title="copyright" name="copyright"></A>Copyright Infringement:</STRONG> If any of   the images included here are copyrighted by someone else but Lovings, inc and   participating advertisers and you are able to provide us with the copyright   information, the steps will be taken immediately to comply with the copyright   law; including but not limited to: removing the image in question from public   display immediately  and permanently. We do our best to prevent   this, but the nature of the digital media makes it difficult to keep up with   this kind of information. Please contact us <b><A href="http://my.lovings.com/contact-us/" target="_blank">&gt;&gt;through   this form&lt;&lt;</A></b> for any copyright violations. We will take is seriously, and respond ASAP within our regular business hours (M-F 11am-6pm). Please include the url of the images in question and all the materials at your disposal that prove the copyright infringement.</p>
  <p align="left">&copy; Copyright 1996-2008   Lovings, Inc. All rights reserved. All pages and materials including but not   limited to the digital editions of the photographs and other art work, design   elements &amp; databases, copy &amp; layout of this site are protected by United   States and international copyright laws. Copying or distribution by any means is   strictly prohibited. <STRONG>Do NOT copy or link to images on this web site for   use anywhere else on or off the internet.</STRONG> This means you!</p>
</div>
</body>
</html>