
<!DOCTYPE html>
<html id="ctl00_htmlElement" xmlns:fb="http://www.facebook.com/2008/fbml" xmlns:og="http://opengraphprotocol.org/schema/" lang="en">
	<head id="ctl00_Head1"><meta charset="utf-8" /><meta name="viewport" content="width=device-width, initial-scale=1" /><meta id="ctl00_ogSiteName" property="og:site_name" content="OnTheHub.com" /><meta id="ctl00_ogTitle" property="og:title" content="OnTheHub" /><meta id="ctl00_ogType" property="og:type" content="website" /><meta id="ctl00_ogUrl" property="og:url" content="http://e5.onthehub.com/index.html" /><meta id="ctl00_ogImage" property="og:image" content="https://elmsprodcdnendpoint.azureedge.net/images/oth_network_96x55px_roundedcorners_whitebackground.png?4.7.7125.28" /><meta id="ctl00_ogDescription" property="og:description" content="Student Discount Software | Educational Software Discounts | OnTheHub links students, faculty and staff to exclusive academic discount software." /><meta id="ctl00_fbAppId" property="fb:app_id" content="134512176588098" /><title>
	Privacy Policy | OnTheHub | Save on Minitab, SPSS, EndNote, Parallels and More
</title>
		<script type="text/javascript">  
			var appInsightsInstrumentationKeys = {
				prod: "bc78e422-53ae-4a32-8046-7861f6fa11cc",
				staging: "8c0ef4f5-c3dd-4741-ac7f-1224724cb376",
				load: "675d557d-4073-4e5f-a53e-52653d0c100f"
			};	
	
			var appInsights = window.appInsights || function (a) {
				function b(a) {
					c[a] = function () {
						var b = arguments;
						c.queue.push(function () {
							c[a].apply(c, b)
						})
					}
				}
				var c = {
					config: a
				},
				d = document,
				e = window;
				setTimeout(function () {
					var b = d.createElement("script");
					b.src = a.url || "https://az416426.vo.msecnd.net/scripts/a/ai.0.js",
					d.getElementsByTagName("script")[0].parentNode.appendChild(b)
				});
				try {
					c.cookie = d.cookie
				} catch (a) {}
				c.queue = [];
				for (var f = ["Event", "Exception", "Metric", "PageView", "Trace", "Dependency"]; f.length; )
					b("track" + f.pop());
				if (b("setAuthenticatedUserContext"), b("clearAuthenticatedUserContext"), b("startTrackEvent"), b("stopTrackEvent"), b("startTrackPage"), b("stopTrackPage"), b("flush"), !a.disableExceptionTracking) {
					f = "onerror",
					b("_" + f);
					var g = e[f];
					e[f] = function (a, b, d, e, h) {
						var i = g && g(a, b, d, e, h);
						return !0 !== i && c["_" + f](a, b, d, e, h),
						i
					}
				}
				return c
			}
		({
			instrumentationKey: appInsightsInstrumentationKeys.prod
		});
		window.appInsights = appInsights, appInsights.queue && 0 === appInsights.queue.length && appInsights.trackPageView();
	</script>
	<meta name="format-detection" content="telephone=no" /><script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script><script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.4/js/bootstrap.min.js"></script><script>this.jQuery || document.write('<script src="//e5.onthehub.com/static/js/jquery/jquery-1.9.1.min.js">\x3C/script>')</script><script>$.fn.alert != undefined || document.write('<script src="//e5.onthehub.com/static/js/bootstrap/bootstrap.min.js">\x3C/script>')</script><link rel="stylesheet" href="https://elmsprodcdnendpoint.azureedge.net/themes/default/default.css" type="text/css" /><script type="text/javascript" src="//e5.onthehub.com/static/js/webStore/SocialNetworkControls.js?4.7.7125.28"></script><script>var kvLocalStore = {"AccessGuarantee":{"SdmBuyNow":"Click to purchase selected add-on offerings"},"Common":{"Available":"Available","Close":"Close","Error":"Error","Loading":"Loading...","PleaseWait":"Please Wait","Processing":"Processing...","Remove":"Remove","Unavailable":"Unavailable"},"LibraryWaitList":{"AddedToWaitList":"Added to Wait List"},"OfferingDetails_aspx":{"BackupMediaAvailable":"Backup media available in most countries","BackupMediaAvailableHoverMessage":"Backup media for this product may be available from your shopping cart. Availability depends on the country from which you are ordering."},"PageContext":{"Interstitial":false},"ShoppingCart_aspx":{"ViewFullCart":"View Full Cart"},"WebStore":{"Add":"Add","AddedToYourShoppingCart":"Added to Your Shopping Cart","AddToCart":"Add to Cart","Brand":"onthehub e-store","Checkout":"Check Out","ContinueShopping":"Back to Shopping","CookieBanner":"<span>By using this site you agree to the use of cookies for analytics, personalized content and ads.</span><a href=\"/WebStore/Support/PrivacyPolicy.aspx\" class=\"learn-link\">Learn more</a>","DemoQuestionsContact":"If you have questions, please <a href=\"/WebStore/Support/ContactUs.aspx\">contact</a> your administrator.","ExpressCheckout":"Express Checkout","ExpressCheckoutMessage":"By placing this order, you agree to all terms and conditions associated with its items.","ExternalUrl":"http://onthehub.com/estore","Id":"49c547ba-f56d-dd11-bb6c-0030485a6b08","InCart":"In Cart","InterstitialUrl":"/WebStore/AddToCartInterstitial.aspx","NoRecommendationsSelected":"No recommended items are selected.","Ordered":"Ordered","Organization":"OnTheHub","PlatformConflictPrompt":"The platform of the product you have chosen appears to be different than the computer you are presently using. Are you sure you would like to add this product to your cart?","ShoppingCartUrl":"/WebStore/ShoppingCart.aspx","ViewAllTermsAndConditions":"View all terms and conditions."}};kvLocalStore.StatusMessages = [];if (!kvLocalStore.hasOwnProperty('ValidationSummary')) kvLocalStore.ValidationSummary = [];</script><script src="/bundles/webstore?v=rhNtWNlrrxja-DcL6HVZfRqzlKPxjWGa_KKPGrCAp_01"></script>
</head>
	<body>
		<noscript>
			<div>
				<p>
					This website requires javascript to be enabled. It appears that your browser is configured to disable javascript.<br />
<br />
For instructions on enabling javascript in your browser, see <a href='https://www.google.com/adsense/support/bin/answer.py?hl=en&answer=12654'>https://www.google.com/adsense/support/bin/answer.py?hl=en&answer=12654</a>.<br />
<br />
If javascript is enabled in your browser and you are still getting this message, please contact your network administrator.
				</p>
			</div>
		</noscript>
		<form name="aspnetForm" method="post" action="./PrivacyPolicy.aspx" id="aspnetForm">
<div>
<input type="hidden" name="__EVENTTARGET" id="__EVENTTARGET" value="" />
<input type="hidden" name="__EVENTARGUMENT" id="__EVENTARGUMENT" value="" />
<input type="hidden" name="__VIEWSTATE" id="__VIEWSTATE" value="/wEPDwUJNDczMzI3NTY3D2QWAmYPZBYCAgEPFgIeBGxhbmcFAmVuFgQCAQ9kFgICBg8WAh4HY29udGVudAVzaHR0cHM6Ly9lbG1zcHJvZGNkbmVuZHBvaW50LmF6dXJlZWRnZS5uZXQvaW1hZ2VzL290aF9uZXR3b3JrXzk2eDU1cHhfcm91bmRlZGNvcm5lcnNfd2hpdGViYWNrZ3JvdW5kLnBuZz80LjcuNzEyNS4yOGQCBQ9kFgYCAw8PFgIeB1Zpc2libGVoZBYCAgUPDxYCHgRUZXh0BWhJZiB5b3UgaGF2ZSBxdWVzdGlvbnMsIHBsZWFzZSA8YSBocmVmPSIvV2ViU3RvcmUvU3VwcG9ydC9Db250YWN0VXMuYXNweCI+Y29udGFjdDwvYT4geW91ciBhZG1pbmlzdHJhdG9yLmRkAgUPZBYQAgcPZBYEAgUPZBYEZg9kFgJmDw8WAh4LTmF2aWdhdGVVcmwFX34vV2ViU3RvcmUvQ29tbW9uL1NlbGVjdEN1cnJlbmN5QW5kQ3VsdHVyZS5hc3B4P3J1cmw9JTJmV2Vic3RvcmUlMmZTdXBwb3J0JTJmUHJpdmFjeVBvbGljeS5hc3B4FgIeCmFyaWEtbGFiZWwFJ1dlYnN0b3JlIGN1bHR1cmUgYW5kIGN1cnJlbmN5IHNlbGVjdGlvbhYGZg8WAh4JaW5uZXJodG1sBQpVUyBEb2xsYXJzZAIBDxYCHgVjbGFzcwUWZmxhZy1pY29uIGZsYWctaWNvbi11c2QCAg8PFgIfAwUHRW5nbGlzaGRkAgIPFgIfAmgWBgIBDxYCHwYFClVTIERvbGxhcnNkAgIPFgIfBwUWZmxhZy1pY29uIGZsYWctaWNvbi11c2QCAw8PFgIfAwUHRW5nbGlzaGRkAgcPZBYGAgEPFgIfAmgWBgIFDxYCHwJoZAIHDw8WAh8EBSN+L1dlYlN0b3JlL0FjY291bnQvWW91ckFjY291bnQuYXNweGRkAgsPDxYCHwQFHH4vV2ViU3RvcmUvU2hvcHBpbmdDYXJ0LmFzcHhkZAIDDxYCHwJnFgICAQ8PFgIfBAVRL1dlYlN0b3JlL1NlY3VyaXR5L1NpZ25Jbi5hc3B4P3J1cmw9JTJmV2Vic3RvcmUlMmZTdXBwb3J0JTJmUHJpdmFjeVBvbGljeS5hc3B4JTNmZGQCBQ8WAh8CZ2QCCQ8PFgIfBAVkfi9XZWJTdG9yZS9Qcm9kdWN0c0J5TWFqb3JWZXJzaW9uTGlzdC5hc3B4P2NtaV9jcz0xJmNtaV9tbnVNYWluPWVkNmFkNzNjLTdiYzctZTAxMS1hZTE0LWYwNGRhMjNlNjdmNmRkAgsPDxYCHwJoZGQCDQ9kFgQCAQ9kFgQCAw8PZBYEHgV0aXRsZQUOUHJvZHVjdCBTZWFyY2geC3BsYWNlaG9sZGVyBQ5Qcm9kdWN0IFNlYXJjaGQCBQ8PFgIeDU9uQ2xpZW50Q2xpY2sFf3Nob3dEaWFsb2coeyd0aXRsZSc6a3ZMb2NhbFN0b3JlLkNvbW1vbi5QbGVhc2VXYWl0LCdjb250ZW50JzprdkxvY2FsU3RvcmUuQ29tbW9uLlByb2Nlc3NpbmcsJ2FsbG93Q2xvc2luZyc6ZmFsc2V9KTtyZXR1cm4gdHJ1ZTsWAh8FBQZTZWFyY2hkAgMPDxYGHgxDdXN0b21NZW51SUQoKVhTeXN0ZW0uR3VpZCwgbXNjb3JsaWIsIFZlcnNpb249NC4wLjAuMCwgQ3VsdHVyZT1uZXV0cmFsLCBQdWJsaWNLZXlUb2tlbj1iNzdhNWM1NjE5MzRlMDg5JGZjZTBmZWI5LTdlYzctZTAxMS1hZTE0LWYwNGRhMjNlNjdmNh4XQ3VycmVudEN1c3RvbU1lbnVJdGVtSUQoKwQkMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMDAwHwJnZGQCDw8PFgIfAmhkZAIXDw8WBh4JRm9yZUNvbG9yDB4IQ3NzQ2xhc3MFH2FsZXJ0IGFsZXJ0LWRhbmdlciBtYXJnaW5Cb3R0b20eBF8hU0ICBmRkAh8PZBYEAgEPDxYCHwMFH1Rlcm1zIG9mIFVzZSBhbmQgUHJpdmFjeSBQb2xpY3lkZAIDDw8WAh8DBcyXATxwPg0KCUJ5IGJyb3dzaW5nIHRoaXMgU2l0ZSwgeW91IGFncmVlIHRoYXQgeW91IGhhdmUgcmVhZCBhbmQgdW5kZXJzdGFuZCB0aGUgZm9sbG93aW5nIFRlcm1zIG9mIFVzZSBhbmQgUHJpdmFjeSBQb2xpY3kgaW4gaXRzIGVudGlyZXR5LCBpbmNsdWRpbmcgYW55IHVwZGF0ZXMgdGhhdCBtYXkgYmUgcG9zdGVkIG9uIHRoZSBTaXRlIGZyb20gdGltZSB0byB0aW1lLiBLaXZ1dG8gU29sdXRpb25zIEluYy4gcmVzZXJ2ZXMgdGhlIHJpZ2h0IHRvIHJldmlzZSB0aGUgVGVybXMgb2YgVXNlIGFuZCBQcml2YWN5IFBvbGljeSwgYXQgaXRzIHNvbGUgZGlzY3JldGlvbiwgYnkgdXBkYXRpbmcgdGhpcyBwb3N0aW5nLjwvcD4NCjxwPg0KCVJlZmVyZW5jZXMgdG8gS2l2dXRvIFNvbHV0aW9ucyBJbmMuIChvciBLaXZ1dG8pIGluIHRoaXMgZG9jdW1lbnQgYWxzbyBhcHBseSB0byBLaXZ1dG/igJlzIHdob2xseSBvd25lZCBicmFuZHMsIFRleGlkaXVtIGFuZCBPblRoZUh1Yi48L3A+DQo8b2w+DQoJPGxpPg0KCQk8YSBocmVmPSIjMSI+V2hhdCBpbmZvcm1hdGlvbiBkbyB5b3UgZ2F0aGVyIGFib3V0IG1lPzwvYT48L2xpPg0KCTxsaT4NCgkJPGEgaHJlZj0iIzIiPkhvdyBkbyB5b3UgY29sbGVjdCBhbmQgdXNlIHBlcnNvbmFsbHkgaWRlbnRpZmlhYmxlIGluZm9ybWF0aW9uPzwvYT48L2xpPg0KCTxsaT4NCgkJPGEgaHJlZj0iIzMiPkhvdyBjYW4gSSBhY2Nlc3MsIHVwZGF0ZSBvciBkZWxldGUgbXkgcGVyc29uYWwgaW5mb3JtYXRpb24/PC9hPjwvbGk+DQoJPGxpPg0KCQk8YSBocmVmPSIjNCI+SG93IGRvIHlvdSBjb2xsZWN0IGFuZCB1c2Ugbm9uLXBlcnNvbmFsbHkgaWRlbnRpZmlhYmxlIGluZm9ybWF0aW9uPzwvYT48L2xpPg0KCTxsaT4NCgkJPGEgaHJlZj0iIzUiPldoYXQgc2VjdXJpdHkgaXMgaW4gcGxhY2UgdG8gcHJvdGVjdCBteSBpbmZvcm1hdGlvbj88L2E+PC9saT4NCgk8bGk+DQoJCTxhIGhyZWY9IiM2Ij5XaGVyZSB3aWxsIG15IGluZm9ybWF0aW9uIGJlIHByb2Nlc3NlZD88L2E+PC9saT4NCgk8bGk+DQoJCTxhIGhyZWY9IiM3Ij5XaGF0IGlzIHlvdXIgZW1haWwgcG9saWN5PzwvYT48L2xpPg0KCTxsaT4NCgkJPGEgaHJlZj0iIzgiPldobyBjYW4gSSBjb250YWN0IHdpdGggcXVlc3Rpb25zIG9yIGNvbmNlcm5zIGFib3V0IHRoaXMgcG9saWN5PzwvYT48L2xpPg0KPC9vbD4NCjxwIGFsaWduPSJsZWZ0Ij4NCgk8c3Ryb25nPk5vdGU6IDwvc3Ryb25nPktpdnV0b+KAmXMgcHJpdmFjeSBwb2xpY3kgYW5kIHN0YW5kYXJkcyBhZGhlcmUgdG8gdGhlIEV1cm9wZWFuIFVuaW9u4oCZcyBHZW5lcmFsIERhdGEgUHJvdGVjdGlvbiBSZWd1bGF0aW9uIChHRFBSKS4gVGhlIEdEUFIgdGFrZXMgZWZmZWN0IG9uIDI1IE1heSAyMDE4LiBUaGUgcHJvdGVjdGlvbnMgb2ZmZXJlZCBieSB0aGlzIGxlZ2lzbGF0aW9uIGFwcGx5IHRvIGFsbCB1c2VycyBvZiBLaXZ1dG/igJlzIHByb2R1Y3RzIGFuZCBzZXJ2aWNlcywgYm90aCBpbnNpZGUgYW5kIG91dHNpZGUgdGhlIEVVLjwvcD4NCjxoMz4NCgkxLiA8YSBuYW1lPSIxIj48L2E+V2hhdCBpbmZvcm1hdGlvbiBkbyB5b3UgZ2F0aGVyIGFib3V0IG1lPzwvaDM+DQo8cD4NCglCb3RoIHBlcnNvbmFsbHkgYW5kIG5vbi1wZXJzb25hbGx5IGlkZW50aWZpYWJsZSBpbmZvcm1hdGlvbiBhYm91dCBlYWNoIHZpc2l0b3IgbWF5IGJlIGdhdGhlcmVkIGZyb20gdGhpcyBzaXRlLiBUaGUgdHlwZSBvZiBpbmZvcm1hdGlvbiBnYXRoZXJlZCBkZXBlbmRzIG9uIHlvdXIgYWN0aW9ucyBhbmQgaW50ZXJhY3Rpb24gd2l0aCB0aGUgc2l0ZS48L3A+DQo8aDQ+DQoJUGVyc29uYWxseSBJZGVudGlmaWFibGUgSW5mb3JtYXRpb248L2g0Pg0KPHA+DQoJUGVyc29uYWxseSBpZGVudGlmaWFibGUgaW5mb3JtYXRpb24gaXMgb25seSBjb2xsZWN0ZWQgd2hlbiB5b3Ugdm9sdW50YXJpbHkgc3VibWl0IHRoaXMgaW5mb3JtYXRpb24gb24gYW4gYXMtbmVlZGVkIGJhc2lzIHN1Y2ggYXMgZHVyaW5nIHJlZ2lzdHJhdGlvbiBhbmQgb3JkZXJpbmcuIEFueSBwZXJzb25hbCBpbmZvcm1hdGlvbiB0aGF0IHlvdSBtYXkgc2hhcmUgd2l0aCB1cyBpcyBrZXB0IHByaXZhdGUuIE5laXRoZXIgeW91ciBuYW1lIG5vciBhbnkgb3RoZXIgaWRlbnRpZnlpbmcgZGF0YSBhYm91dCB5b3UgaXMgc29sZCBvciBzaGFyZWQgd2l0aCBhbnkgb3RoZXIgdGhpcmQgcGFydHkgdW5sZXNzIHJlcXVpcmVkIGZvciB0aGUgZnVsZmlsbG1lbnQgb3IgcmVmdW5kIG9mIHlvdXIgb3JkZXIgb3Igc2VydmljZS4gTW9yZSBpbmZvcm1hdGlvbiBvbiB0aGlzIHVzZSBpcyBwcm92aWRlZCBsYXRlciBpbiB0aGlzIHByaXZhY3kgcG9saWN5LjwvcD4NCjxoND4NCglOb24tUGVyc29uYWxseSBJZGVudGlmaWFibGUgSW5mb3JtYXRpb248L2g0Pg0KPHA+DQoJTm9uLXBlcnNvbmFsbHkgaWRlbnRpZnlpbmcgaW5mb3JtYXRpb24gaXMgZ2F0aGVyZWQgdGhyb3VnaCBvdXIgc2l0ZSB0ZWNobm9sb2d5IHRvIGNyZWF0ZSBhIG1vcmUgcGVyc29uYWxpemVkIGFuZCByZWxldmFudCBleHBlcmllbmNlIGR1cmluZyB5b3VyIHZpc2l0LiBUaGUgaW5mb3JtYXRpb24gYWxzbyBhbGxvd3MgdXMgdG8gaW1wcm92ZSB0aGUgZnVuY3Rpb25hbGl0eSBvZiB0aGUgd2Vic2l0ZSB0byBiZXR0ZXIgc2VydmUgeW91LjwvcD4NCjxoMz4NCgkyLiA8YSBuYW1lPSIyIj48L2E+SG93IGRvIHlvdSBjb2xsZWN0IGFuZCB1c2UgcGVyc29uYWxseSBpZGVudGlmaWFibGUgaW5mb3JtYXRpb24/PC9oMz4NCjxoND4NCglDb2xsZWN0aW5nIFBlcnNvbmFsbHkgSWRlbnRpZmlhYmxlIEluZm9ybWF0aW9uPC9oND4NCjxwPg0KCVBlcnNvbmFsbHkgaWRlbnRpZmlhYmxlIGluZm9ybWF0aW9uIG1heSBiZSBjb2xsZWN0ZWQgZHVyaW5nIHJlZ2lzdHJhdGlvbiwgb3JkZXJpbmcgYW5kIGJpbGxpbmcsIGR1cmluZyBjdXN0b21lciBzZXJ2aWNlIGludGVyYWN0aW9ucyBvciB3aGVuIHlvdSBlbnRlciBhIGNvbnRlc3QuIFBlcnNvbmFsbHkgaWRlbnRpZmlhYmxlIGluZm9ybWF0aW9uIGlzIG5ldmVyIHNoYXJlZCBpbiB3YXlzIHVucmVsYXRlZCB0byB0aGUgbWV0aG9kcyBkZXNjcmliZWQgYmVsb3cgd2l0aG91dCBub3RpZnlpbmcgeW91IG9mIHRoZSBpbnRlbnQgYmVmb3JlaGFuZCwgYW5kIGFsc28gcHJvdmlkaW5nIHlvdSB3aXRoIGFuIG9wcG9ydHVuaXR5IHRvIG9wdC1vdXQgb3Igb3RoZXJ3aXNlIHByb2hpYml0IHN1Y2ggdW5yZWxhdGVkIHVzZXMuPC9wPg0KPGg0Pg0KCVJlZ2lzdHJhdGlvbjwvaDQ+DQo8cD4NCglEdXJpbmcgcmVnaXN0cmF0aW9uLCB5b3UgbWF5IGJlIHByb21wdGVkIGZvciB5b3VyIG5hbWUgYW5kIGVtYWlsIGFkZHJlc3MgZm9yIGF1dGhlbnRpY2F0aW9uIGFuZCB2ZXJpZmljYXRpb24gcHVycG9zZXMuIFRoZXNlIHN0ZXBzIG1heSBiZSBuZWNlc3NhcnkgdG8gZW5zdXJlIHVzZXJzIGFyZSBwcm9wZXJseSBpZGVudGlmaWVkIGFuZCBhdXRoZW50aWNhdGVkIGFzIGEgcXVhbGlmaWVkIHVzZXIuIFNvbWUgb2ZmZXJpbmdzIGFuZCBwcm9tb3Rpb25zIG9uIHRoaXMgc2l0ZSBtYXkgYmUgcmVzdHJpY3RlZCB0byBjZXJ0YWluIHR5cGVzIG9mIHVzZXJzIChlLmcuIHN0dWRlbnRzLCBmYWN1bHR5LCBvciBzdGFmZikgb3IgdG8gbWVtYmVycyBvZiBjZXJ0YWluIG9yZ2FuaXphdGlvbnMuIEJ5IHByb3ZpZGluZyB5b3VyIGVtYWlsIGFkZHJlc3MsIGFuZCBzdWJzZXF1ZW50bHkgaGF2aW5nIHlvdXIgYWNjb3VudCB2ZXJpZmllZCwgeW91IG1heSBiZW5lZml0IGZyb20gdGhlc2Ugb2ZmZXJpbmdzIGFuZCBwcm9tb3Rpb25zLjwvcD4NCjxoND4NCglPcmRlcmluZyBhbmQgQmlsbGluZzwvaDQ+DQo8cD4NCglXaGVuIHlvdSBwbGFjZSBhbiBvcmRlciB0aHJvdWdoIG9uZSBvZiBLaXZ1dG/igJlzIHNpdGVzIGZvciBhIHByb2R1Y3QgdGhhdCBpcyBub3QgZnJlZSwgeW91IG1heSBuZWVkIHRvIHN1cHBseSB5b3VyIGNyZWRpdCBjYXJkIGluZm9ybWF0aW9uLiBXaGVuIG9yZGVyaW5nIGEgcHJvZHVjdCB0aGF0IGlzIHBoeXNpY2FsbHkgZGVsaXZlcmVkLCB5b3Ugd2lsbCBuZWVkIHRvIHByb3ZpZGUgdGhlIG5lY2Vzc2FyeSBzaGlwcGluZyBpbmZvcm1hdGlvbiAoZS5nLiBwb3N0YWwgYWRkcmVzcykuIFRoaXMgaW5mb3JtYXRpb24gbWF5IGJlIHJlcXVpcmVkIHRvIGZ1bGZpbGwgeW91ciBvcmRlciBhbmQvb3IgZm9yIGV4cG9ydC1jb21wbGlhbmNlIHB1cnBvc2VzLiBZb3VyIGNyZWRpdCBjYXJkIGluZm9ybWF0aW9uIGlzIG5vdCBzdG9yZWQgb24gb3VyIHNlcnZlcjsgaXQgaXMgc2ltcGx5IHBhc3NlZCBvbiB0byB0aGUgY3JlZGl0IGNhcmQgcHJvY2Vzc2luZyBzeXN0ZW0gZm9yIHZhbGlkYXRpb24uIFlvdSBtYXkgYWxzbyBiZSBwcm9tcHRlZCBmb3IgeW91ciBuYW1lIGFuZCBlbWFpbCBhZGRyZXNzIHRvIGNyZWF0ZSB5b3VyIG9ubGluZSByZWNlaXB0IGFuZCBmb3IgdXMgdG8gc2VuZCB5b3Ugb3JkZXItcmVsYXRlZCBlbWFpbHMuPC9wPg0KPGg0Pg0KCUN1c3RvbWVyIFNlcnZpY2U8L2g0Pg0KPHA+DQoJUGVyc29uYWxseSBpZGVudGlmaWFibGUgaW5mb3JtYXRpb24gbWF5IGJlIGNvbGxlY3RlZCBpZiB5b3UgcmVwb3J0IGEgcHJvYmxlbSBvciBzdWJtaXQgYW4gaW5xdWlyeSB0byBvdXIgY3VzdG9tZXIgc2VydmljZSB0ZWFtKHMpLiBBIHJlY29yZCBvZiB0aGF0IGNvcnJlc3BvbmRlbmNlIG1heSBiZSBtYWludGFpbmVkIHRvIHByb3ZpZGUgeW91IHdpdGggYW4gb3B0aW1hbCBjdXN0b21lciBzZXJ2aWNlIGV4cGVyaWVuY2UuPC9wPg0KPGg0Pg0KCUVudGVyaW5nIGEgQ29udGVzdCBvciBQcm9tb3Rpb248L2g0Pg0KPHA+DQoJRnVydGhlcm1vcmUsIGluZm9ybWF0aW9uIGZyb20geW91IG1heSBiZSBjb2xsZWN0ZWQgZm9yIGVudHJ5IGludG8gY29udGVzdHMgYW5kIHNpbWlsYXIgcHJvbW90aW9ucyB3aGVuIHlvdSB2b2x1bnRhcmlseSBjaG9vc2UgdG8gcGFydGljaXBhdGUuIEFsbCBjb250ZXN0cyBoYXZlIHRoZWlyIG93biB0ZXJtcyBhbmQgY29uZGl0aW9ucyB3aGljaCBjYW4gYmUgdmlld2VkIG9uIHRoZSBjb250ZXN04oCZcyBwYWdlLjwvcD4NCjxoND4NCglVc2luZyBQZXJzb25hbGx5IElkZW50aWZpYWJsZSBJbmZvcm1hdGlvbjwvaDQ+DQo8cD4NCglZb3VyIHBlcnNvbmFsbHkgaWRlbnRpZmlhYmxlIGluZm9ybWF0aW9uIGlzIG5vdCBzb2xkLCB0cmFkZWQgb3IgcmVudGVkIHRvIG90aGVycy48L3A+DQo8cD4NCglLaXZ1dG8gZG9lcyBlbXBsb3kgb3RoZXIgdHJ1c3RlZCBjb21wYW5pZXMgdG8gcGVyZm9ybSBjZXJ0YWluIGZ1bmN0aW9ucyBvbiBvdXIgYmVoYWxmLCBpbmNsdWRpbmcgb3JkZXIgZnVsZmlsbG1lbnQgYW5kIGRlbGl2ZXJ5LCBhcyB3ZWxsIGFzIGNyZWRpdCBjYXJkIHByb2Nlc3NpbmcuIFRoZXNlIGJ1c2luZXNzIGFmZmlsaWF0ZXMgaGF2ZSBhY2Nlc3MgdG8gcGVyc29uYWwgaW5mb3JtYXRpb24gbmVlZGVkIHRvIHBlcmZvcm0gdGhlaXIgZnVuY3Rpb25zLCBidXQgYXJlIG5vdCBwZXJtaXR0ZWQgdG8gdXNlIHlvdXIgcGVyc29uYWwgaW5mb3JtYXRpb24gZm9yIGFueSBvdGhlciBwdXJwb3NlLjwvcD4NCjxwPg0KCUFkZGl0aW9uYWxseSwgaW5mb3JtYXRpb24gcmVsYXRlZCB0byB0aGUgb3JkZXIgb2YgYSBwcm9kdWN0IG1heSBiZSBzaGFyZWQgd2l0aCB0aGUgc3VwcGxpZXIgb2YgdGhhdCBwYXJ0aWN1bGFyIHByb2R1Y3QsIGZvciB3YXJyYW50eSBhbmQgc3VwcG9ydCBwdXJwb3Nlcy4gVGhpcyBtYXkgaW5jbHVkZSB5b3VyIG5hbWUsIGRhdGUgb2YgeW91ciBvcmRlciBhbmQgcHJvZHVjdCBwdXJjaGFzZWQuPC9wPg0KPHA+DQoJSWYgeW91IGhhdmUgcXVlc3Rpb25zIGFib3V0IGhvdyBvbmUgb2Ygb3VyIGJ1c2luZXNzIHBhcnRuZXJzIG9yIHN1cHBsaWVycyB1c2UgaW5mb3JtYXRpb24gYWJvdXQgeW91LCBjb250YWN0IHRoZW0gZGlyZWN0bHkuPC9wPg0KPGgzPg0KCTMuIDxhIG5hbWU9IjMiPjwvYT5Ib3cgY2FuIEkgYWNjZXNzLCB1cGRhdGUsIG9yIGRlbGV0ZSBteSBwZXJzb25hbCBpbmZvcm1hdGlvbj88L2gzPg0KPGg0Pg0KCUFjY2Vzc2luZyBhbmQgVXBkYXRpbmcgUGVyc29uYWwgSW5mb3JtYXRpb24gKFJpZ2h0IHRvIEFjY2Vzcyk8L2g0Pg0KPHA+DQoJVXNlcnMgY2FuIHJlcXVlc3QgYW55IG9mIHRoZSBmb2xsb3dpbmcgZnJvbSBLaXZ1dG8gYXQgYW55IHRpbWUuPC9wPg0KPHVsPg0KCTxsaT4NCgkJQ29uZmlybWF0aW9uIG9mIHdoZXRoZXIgS2l2dXRvIHBvc3Nlc3NlcyBhbnkgb2YgdGhlIHVzZXLigJlzIHBlcnNvbmFsIGluZm9ybWF0aW9uPC9saT4NCgk8bGk+DQoJCVRoZSBsb2NhdGlvbihzKSB3aGVyZSBLaXZ1dG8gaXMgcHJvY2Vzc2luZyB0aGUgdXNlcuKAmXMgcGVyc29uYWwgaW5mb3JtYXRpb248L2xpPg0KCTxsaT4NCgkJVGhlIHB1cnBvc2UocykgZm9yIHdoaWNoIEtpdnV0byBpcyBwcm9jZXNzaW5nIHRoZSB1c2Vy4oCZcyBwZXJzb25hbCBpbmZvcm1hdGlvbjwvbGk+DQoJPGxpPg0KCQlBIGNvcHkgb2YgYWxsIHRoZSB1c2Vy4oCZcyBwZXJzb25hbCBpbmZvcm1hdGlvbiBpbiBLaXZ1dG/igJlzIHBvc3Nlc3Npb24sIHRvIGJlIHByb3ZpZGVkIGluIGEgY29tbW9ubHkgdXNlZCwgbWFjaGluZS1yZWFkYWJsZSBmb3JtYXQuPC9saT4NCjwvdWw+DQo8cD4NCglUbyByZXF1ZXN0IGFueSBvZiB0aGUgYWJvdmUgaW5mb3JtYXRpb24sIGNvbnRhY3QgPGEgaHJlZj0ibWFpbHRvOnByaXZhY3lAa2l2dXRvLmNvbSI+cHJpdmFjeUBraXZ1dG8uY29tPC9hPi48L3A+DQo8cD4NCglVc2VycyBjYW4gYWxzbyByZXZpZXcgYW5kIG1ha2UgdXBkYXRlcyB0byB0aGUgaW5mb3JtYXRpb24gYW5kIHByZWZlcmVuY2VzIGluIHRoZWlyIGFjY291bnQgcHJvZmlsZSBhdCBhbnkgdGltZSB0aHJvdWdoIHRoZSBBY2NvdW50IEluZm9ybWF0aW9uIHBhZ2Ugb24gdGhlaXIgV2ViU3RvcmUsIHByb3ZpZGVkIHRoZXkgYXJlIHNpZ25lZCBpbiB0byB0aGVpciBhY2NvdW50LjwvcD4NCjxoND4NCglEZWFjdGl2YXRpbmcgYW4gQWNjb3VudDwvaDQ+DQo8cD4NCglZb3UgY2FuIGhhdmUgeW91ciBhY2NvdW50IGRlYWN0aXZhdGVkIG9yIGRlbGV0ZWQgYnkgY29udGFjdGluZyBTdXBwb3J0LiBIb3dldmVyLCBkb2luZyBzbyB3aWxsIGxpbWl0IHlvdXIgYWNjZXNzIHRvIG1lbWJlcnMtb25seSBhcmVhcyBvZiB0aGUgc2l0ZS4gQW55IHB1cmNoYXNlIGhpc3RvcnkgaW5mb3JtYXRpb24sIGhvd2V2ZXIsIHdpbGwgcmVtYWluIGluIHByb3RlY3RlZCBwZXJtYW5lbnQgcmVjb3Jkcy48L3A+DQo8aDQ+DQoJRGVsZXRpbmcgUGVyc29uYWwgSW5mb3JtYXRpb24gKFJpZ2h0IHRvIEVyYXN1cmUpPC9oND4NCjxwPg0KCVVzZXJzIGNhbiByZXF1ZXN0IHRoZSBkZWxldGlvbiBvZiBhbGwgb2YgcGVyc29uYWwgaW5mb3JtYXRpb24gS2l2dXRvIGhhcyBjb2xsZWN0ZWQgYWJvdXQgdGhlbSBhdCBhbnkgdGltZS4gSW4gdGhlIGFic2VuY2Ugb2YgYW55IHVyZ2VudCBsZWdhbCBvciBidXNpbmVzcyByZWFzb24gdG8gcmV0YWluIGEgdXNlcuKAmXMgcGVyc29uYWwgaW5mb3JtYXRpb24gKGUuZy4gYWRoZXJlbmNlIHRvIGEgbGF3IG9yIGEgY29udHJhY3R1YWwgb2JsaWdhdGlvbiksIEtpdnV0byB3aWxsIHBlcm1hbmVudGx5IGRlbGV0ZSBvciBvYmZ1c2NhdGUgYWxsIHBlcnNvbmFsIGluZm9ybWF0aW9uIGFib3V0IHVzZXJzIHdobyBtYWtlIHRoZXNlIHJlcXVlc3RzLjwvcD4NCjxwPg0KCVdoZW4gcmVxdWlyZWQsIEtpdnV0byB3aWxsIGFsc28gY29udGFjdCBhbnkgdGhpcmQgcGFydGllcyB0byB3aGljaCBLaXZ1dG8gcGFzc2VkIHRoZSB1c2Vy4oCZcyBwZXJzb25hbCBkYXRhIGFuZCBlbnN1cmUgdGhhdCB0aGUgZGF0YSBpcyBkZWxldGVkIGZyb20gdGhlIHN5c3RlbXMgYW5kIHJlY29yZHMgb2YgdGhvc2UgdGhpcmQgcGFydGllcyBhcyB3ZWxsLjwvcD4NCjxwPg0KCVRvIHJlcXVlc3QgdGhlIGVyYXN1cmUgb2YgeW91ciBwZXJzb25hbCBkYXRhLCBjb250YWN0OiA8YSBocmVmPSJtYWlsdG86cHJpdmFjeUBraXZ1dG8uY29tIj5wcml2YWN5QGtpdnV0by5jb208L2E+LjwvcD4NCjxoMz4NCgk0LiA8YSBuYW1lPSI0Ij48L2E+SG93IGRvIHlvdSBjb2xsZWN0IGFuZCB1c2Ugbm9uLXBlcnNvbmFsbHkgaWRlbnRpZmlhYmxlIGluZm9ybWF0aW9uPzwvaDM+DQo8cD4NCglLaXZ1dG8gdXNlcyB0ZWNobm9sb2dpZXMgbGlrZSBjb29raWVzLCBwaXhlbCB0YWdzICjigJxwaXhlbHPigJ0pLCBhbmQgbG9jYWwgc3RvcmFnZSB0byBkZWxpdmVyLCBzZWN1cmUsIGFuZCB1bmRlcnN0YW5kIHByb2R1Y3RzLCBzZXJ2aWNlcywgYW5kIGFkcywgb24gYW5kIG9mZiBvdXIgc2l0ZXMuPC9wPg0KPGg0Pg0KCUNvbGxlY3Rpbmcgbm9uLXBlcnNvbmFsbHkgaWRlbnRpZmlhYmxlIGluZm9ybWF0aW9uPC9oND4NCjxwPg0KCVlvdXIgdmVyaWZpY2F0aW9uIHN0YXR1cyBpcyBjb2xsZWN0ZWQgb25jZSB5b3Ugc3VjY2Vzc2Z1bGx5IHJlZ2lzdGVyIHRocm91Z2ggYW55IG9mIG91ciB2ZXJpZmljYXRpb24gc2VydmljZXMuIFRoZSByZXN1bHRpbmcgc3RhdHVzIGlzIG5vbi1wZXJzb25hbGx5IGlkZW50aWZpYWJsZSBpbmZvcm1hdGlvbiBhbmQgaXMgc3RvcmVkIGluIGNhc2UgeW91IG5lZWQgdG8gdmVyaWZ5IHlvdXIgc3RhdHVzIGFnYWluIGluIHRoZSBmdXR1cmUuPC9wPg0KPHA+DQoJTm9uLXBlcnNvbmFsbHkgaWRlbnRpZmlhYmxlIGluZm9ybWF0aW9uIGlzIGNvbGxlY3RlZCB1c2luZyB0ZWNobm9sb2d5IHN1Y2ggYXMgY29va2llcy4g4oCcQ29va2llc+KAnSBhcmUgc21hbGwgcGllY2VzIG9mIGluZm9ybWF0aW9uIHRoYXQgYXJlIHN0b3JlZCBieSB5b3VyIGJyb3dzZXIgb24geW91ciBsb2NhbCBzdG9yYWdlLiBUaGUgaW5mb3JtYXRpb24gY29sbGVjdGVkIGJ5IHRoaXMgdGVjaG5vbG9neSBpcyBub24tcGVyc29uYWxseSBpZGVudGlmaWFibGUgb25seSBhbmQgYWxsb3dzIHVzIHRvIG9wdGltaXplIHlvdXIgaW50ZXJhY3Rpb25zIHdpdGggdGhlIHNpdGUuPC9wPg0KPGg0Pg0KCVVzaW5nIG5vbi1wZXJzb25hbGx5IGlkZW50aWZpYWJsZSBpbmZvcm1hdGlvbjwvaDQ+DQo8cD4NCglDb29raWVzIGFsbG93IGZvciBjdXN0b21lciB0cmFmZmljIHBhdHRlcm5zIGFuZCBzaXRlIHVzYWdlIHRvIGJlIG1vbml0b3JlZCBvbiBhIGdlbmVyYWwgYmFzaXMgdG8gaGVscCBkZXZlbG9wIGFuZCBpbXByb3ZlIHRoZSBkZXNpZ24sIGxheW91dCBhbmQgZWZmaWNpZW5jeSBvZiB0aGUgd2Vic2l0ZS4gVW5kZXJzdGFuZGluZyB0aGVzZSBwYXR0ZXJucyBhbGxvd3MgdXMgdG8gcHJvdmlkZSBtb3JlIHJlbGV2YW50IGNvbnRlbnQgdG8geW91IGFuZCBpbXByb3ZlIGN1c3RvbWVyIHJlbGF0aW9uc2hpcHMuIEZ1cnRoZXJtb3JlLCB0aGUgaW5mb3JtYXRpb24gY29sbGVjdGVkIGlzIHVzZWQgdG8gY3JlYXRlIHRhcmdldGVkIGNvbW11bmljYXRpb25zIHRvIG9mZmVyIHlvdSBhIG1vcmUgcGVyc29uYWxpemVkIGFuZCBjdXN0b21pemFibGUgZXhwZXJpZW5jZS4gQ29va2llcyBhbHNvIHNhdmUgeW91IHRpbWUgYnkgcmVtZW1iZXJpbmcgeW91ciBwZXJzb25hbGl6ZWQgc2V0dGluZ3MuPC9wPg0KPHA+DQoJTm90ZSB0aGF0IGFsbCBpbmZvcm1hdGlvbiBpcyBjb2xsZWN0ZWQgYW5kIGFuYWx5emVkIGluIGFnZ3JlZ2F0ZWQgZm9ybSBvbmx5LiBDaGVjayB5b3VyIGJyb3dzZXIgdG8gZW5zdXJlIGNvb2tpZXMgYXJlIGVuYWJsZWQgZm9yIHRoaXMgc2l0ZSB0byB3b3JrIHByb3Blcmx5LjwvcD4NCjxwPg0KCUtpdnV0byBTb2x1dGlvbnMgSW5jLiBtYXkgdXNlIHRoaXJkLXBhcnR5IGFkdmVydGlzaW5nIHRlY2hub2xvZ3kgcGFydG5lcnMgdG8gc2VydmUgeW91IHJlbGV2YW50IGFkdmVydGlzZW1lbnRzIG9uIHdlYnNpdGVzIG91dHNpZGUgb2Ygb3VyIG5ldHdvcmsuIFRoZSBhZHZlcnRpc2luZyB0ZWNobm9sb2d5IHBhcnRuZXIgcHJvdmlkZXMgdXMgd2l0aCB0cmFja2luZyB0ZWNobm9sb2d5LCBzdWNoIGFzIGEgY29va2llLCB3aGljaCBpcyBhZGRlZCB0byB5b3VyIGJyb3dzZXIgYnkgdXMuIFRoaXMgYWxsb3dzIHVzIHRvIHNlcnZlIHlvdSB2ZXJ5IHJlbGV2YW50IGFkcyBvbiB0aGVpciBwYXJ0bmVyIHdlYnNpdGVzIGFjY29yZGluZyB0byB5b3VyIGVuZ2FnZW1lbnRzIHdpdGggdGhpcyBzaXRlLiBJZiB5b3Ugd291bGQgbGlrZSB0byBsZWFybiBtb3JlIGFib3V0IHRoaXMgcHJvY2VzcyBvciBldmVuIG9wdC1vdXQsIHBsZWFzZSBjb250YWN0IHVzLjwvcD4NCjxoND4NCglIb3cgdG8gbWFuYWdlIGNvb2tpZXM8L2g0Pg0KPHA+DQoJQnJvd3NlciBjb250cm9scyBhcmUgYXZhaWxhYmxlIHRvIGFsbG93LCBibG9jayBvciBkZWxldGUgY29va2llcy4gVG8gbWFuYWdlIHRoZSBjb29raWVzIHRoaXMgc2l0ZSBhbmQgb3RoZXJzIHVzZSwgdmlzaXQgdGhlIGZvbGxvd2luZyBzaXRlIGZvciBpbnN0cnVjdGlvbnM6IDxhIGhyZWY9Imh0dHA6Ly93aW5kb3dzLm1pY3Jvc29mdC5jb20vZW4tVVMvd2luZG93cy12aXN0YS9CbG9jay1vci1hbGxvdy1jb29raWVzIiB0YXJnZXQ9Il9ibGFuayI+aHR0cDovL3dpbmRvd3MubWljcm9zb2Z0LmNvbS9lbi1VUy93aW5kb3dzLXZpc3RhL0Jsb2NrLW9yLWFsbG93LWNvb2tpZXM8L2E+PC9wPg0KPHA+DQoJUGxlYXNlIG5vdGUgdGhhdCBieSBhZGp1c3RpbmcgeW91ciBjb29raWUgc2V0dGluZ3MsIGFueSBzZXR0aW5ncyBvciBwcmVmZXJlbmNlcyB3aWxsIG5vIGxvbmdlciBiZSBpbiBlZmZlY3QuIFRoZSB1c2FnZSBhbmQgZnVuY3Rpb25hbGl0eSBvZiB0aGUgc2l0ZSB3aWxsIGJlIHN1YmplY3QgdG8gY2hhbmdlIGluY2x1ZGluZyB0aGUgYWJpbGl0eSB0byBwdXJjaGFzZSBjZXJ0YWluIHByb2R1Y3RzIGFuZCB2aWV3IGNvbnRlbnQgb24gdGhlIHNpdGUuPC9wPg0KPGgzPg0KCTUuIDxhIG5hbWU9IjUiPjwvYT5XaGF0IHNlY3VyaXR5IGlzIGluIHBsYWNlIHRvIHByb3RlY3QgbXkgaW5mb3JtYXRpb24/PC9oMz4NCjxoND4NCglTZWN1cml0eSBNZWFzdXJlczwvaDQ+DQo8cD4NCglZb3VyIGluZm9ybWF0aW9uIGlzIHByb3RlY3RlZCBib3RoIGR1cmluZyB0cmFuc21pc3Npb24gYW5kIGluIHN0b3JhZ2UuIFlvdXIgYWNjb3VudCBhbmQgcHJvZmlsZSBpbmZvcm1hdGlvbiBhcmUgcGFzc3dvcmQtcHJvdGVjdGVkIHNvIHRoYXQgeW91IGFuZCBvbmx5IHlvdSBoYXZlIGFjY2VzcyB0byB0aGlzIHBlcnNvbmFsIGluZm9ybWF0aW9uLiBEdXJpbmcgcHVyY2hhc2UsIHRoZSBzZWN1cmUgc2VydmVyIHNvZnR3YXJlIChTU0wpIGVuY3J5cHRzIGFsbCBpbmZvcm1hdGlvbiB5b3UgaW5wdXQgYmVmb3JlIGl0IGlzIHRyYW5zbWl0dGVkLiBBcyBzdWNoLCBhbGwgY3VzdG9tZXIgZGF0YSBpcyBwcm90ZWN0ZWQgYWdhaW5zdCB1bmF1dGhvcml6ZWQgYWNjZXNzIG9uIHRoZSBzeXN0ZW3igJlzIHNlY3VyZSBzZXJ2ZXJzLjwvcD4NCjxoND4NCglCcmVhY2ggTm90aWZpY2F0aW9uPC9oND4NCjxwPg0KCUluIHRoZSBldmVudCBvZiBhIHNlY3VyaXR5IGJyZWFjaCB0aGF0IGNyZWF0ZXMgYSBwb3RlbnRpYWwgcmlzayB0byB1c2Vyc+KAmSBwZXJzb25hbCBpbmZvcm1hdGlvbiwgS2l2dXRvIHdpbGwgZW5zdXJlIHRoYXQgdGhlIGFwcHJvcHJpYXRlIGF1dGhvcml0aWVzIGFyZSBub3RpZmllZCBvZiB0aGUgYnJlYWNoIHdpdGhpbiA3MiBob3VycyBvZiBpdHMgZGlzY292ZXJ5LjwvcD4NCjxwPg0KCUlmIGEgc2VjdXJpdHkgYnJlYWNoIGlzIGp1ZGdlZCBsaWtlbHkgdG8gcG9zZSBhIGhpZ2ggcmlzayB0byB0aGUgcmlnaHRzIGFuZCBmcmVlZG9tcyBvZiBvbmUgb3IgbW9yZSBhZmZlY3RlZCB1c2VycywgYWxsIHJlYXNvbmFibGUgZWZmb3J0cyB3aWxsIGJlIG1hZGUgdG8gY29udGFjdCB0aG9zZSB1c2VycyBhbmQgaW5mb3JtIHRoZW0gb2YgdGhlIGJyZWFjaCBhbmQgdGhlIHBvdGVudGlhbCBpbXBhY3QgdGhlcmVvZi48L3A+DQo8aDM+DQoJNi4gPGEgbmFtZT0iNiI+PC9hPldoZXJlIHdpbGwgbXkgaW5mb3JtYXRpb24gYmUgcHJvY2Vzc2VkPzwvaDM+DQo8cD4NCglLaXZ1dG8gU29sdXRpb25zLCBJbmMuIGlzIGEgQ2FuYWRpYW4gY29ycG9yYXRpb24gd2l0aCBvZmZpY2VzIGF0IDEyNiBZb3JrIFN0cmVldCwgU3VpdGUgMjAwLCBPdHRhd2EsIE9udGFyaW8sIENhbmFkYS4gUGVyc29uYWwgaW5mb3JtYXRpb24gZ2F0aGVyZWQgYnkgS2l2dXRvIGlzIHN0b3JlZCBvbiBzZXJ2ZXJzIGxvY2F0ZWQgaW4gQ2FuYWRhIGFuZCB3aWxsIG5vdCBiZSB0cmFuc2ZlcnJlZCB0byBhbnkgb3RoZXIgY291bnRyeSB1bmxlc3MgaXQgaXMgcmVxdWlyZWQgYXMgcGFydCBvZiB0aGUgZnVsZmlsbG1lbnQgb2Ygc2VydmljZSBvciByZXF1ZXN0ZWQgYnkgdGhlIHVzZXIgKHNlZSBiZWxvdykuPC9wPg0KPHA+DQoJRHVlIHRvIGFncmVlbWVudHMgd2l0aCBvdXIgc29mdHdhcmUgcHVibGlzaGVyIHBhcnRuZXJzIGFuZCBDYW5hZGlhbiBsZWdhbCBvYmxpZ2F0aW9ucywgeW91ciBkYXRhIG1heSBiZSBzdG9yZWQgaW4gZW5jcnlwdGVkIGJhY2t1cHMgb24gb3VyIHNlcnZlcnMgZm9yIHVwIHRvIHNldmVuIHllYXJzLjwvcD4NCjxwPg0KCVByaXZhY3kgbGF3cyBhbmQgcmVxdWlyZW1lbnRzIGRpZmZlciBhY2NvcmRpbmcgdG8gZWFjaCBjb3VudHJ5LiBQbGVhc2Uga25vdywgaG93ZXZlciwgdGhhdCBhbGwgaW5mb3JtYXRpb24gY29sbGVjdGVkIHRocm91Z2ggS2l2dXRv4oCZcyBXZWJzaXRlcyB3aWxsIGJlIHByb3RlY3RlZCBieSB0aGUgdGVybXMgb2YgdGhpcyBQcml2YWN5IFBvbGljeSBhbmQgYW55IFByaXZhY3kgTm90aWNlcyB0aGF0IGFwcGx5IHRvIHlvdSwgcmVnYXJkbGVzcyBvZiB3aGF0IGNvdW50cnkgdGhlIGluZm9ybWF0aW9uIG9yaWdpbmF0ZXMgZnJvbS48L3A+DQo8aDQ+DQoJVHJhbnNmZXJyaW5nIFBlcnNvbmFsIEluZm9ybWF0aW9uIChEYXRhIFBvcnRhYmlsaXR5KTwvaDQ+DQo8cD4NCglVc2VycyBjYW4gcmVxdWVzdCB0byBoYXZlIGFsbCBwZXJzb25hbCBpbmZvcm1hdGlvbiBLaXZ1dG8gaGFzIGNvbGxlY3RlZCBhYm91dCB0aGVtIHRyYW5zZmVycmVkIGZyb20gS2l2dXRvIHRvIGFub3RoZXIgZGF0YSBoYW5kbGVyIG9mIHRoZSB1c2Vy4oCZcyBjaG9pY2UuPC9wPg0KPHA+DQoJTm90ZSB0aGF0IEtpdnV0byB3aWxsIG9ubHkgdHJhbnNmZXIgcGVyc29uYWwgaW5mb3JtYXRpb24gYWJvdXQgYSB1c2VyIHRvIGNvdW50cmllcyBhbmQgb3JnYW5pemF0aW9ucyB0aGF0IGFyZSBwZXJtaXR0ZWQgYnkgbGF3IGFuZCB0aGF0IG9mZmVyIGNvbXBhcmFibGUgbGV2ZWxzIG9mIHByb3RlY3Rpb24gb24gdXNlcnPigJkgcGVyc29uYWwgaW5mb3JtYXRpb24uPC9wPg0KPHA+DQoJVG8gcmVxdWVzdCB0aGUgdHJhbnNmZXIgb2YgeW91ciBwZXJzb25hbCBkYXRhIHRvIGFub3RoZXIgZGF0YSBoYW5kbGVyLCBjb250YWN0OiA8YSBocmVmPSJtYWlsdG86cHJpdmFjeUBraXZ1dG8uY29tIj5wcml2YWN5QGtpdnV0by5jb208L2E+LjwvcD4NCjxoMz4NCgk3LiA8YSBuYW1lPSI3Ij48L2E+V2hhdCBpcyB5b3VyIGVtYWlsIHBvbGljeT88L2gzPg0KPHA+DQoJS2l2dXRvIFNvbHV0aW9ucyBJbmMuIGNvbXBsaWVzIGZ1bGx5IHdpdGggdGhlIGZlZGVyYWwgQ0FOLVNQQU0gQWN0IG9mIDIwMDMgYW5kIENhbmFkYeKAmXMgQW50aS1TcGFtIExlZ2lzbGF0aW9uIChDQVNMKS4gS2l2dXRvIHdpbGwgbm90IHNoYXJlLCBzZWxsLCByZW50LCBzd2FwIG9yIGF1dGhvcml6ZSBhbnkgdGhpcmQgcGFydHkgdG8gdXNlIHlvdXIgZW1haWwgYWRkcmVzcyBmb3IgY29tbWVyY2lhbCBwdXJwb3NlcyB3aXRob3V0IHlvdXIgcGVybWlzc2lvbi4gSWYgeW91IGZlZWwgeW91IGhhdmUgcmVjZWl2ZWQgYW4gZW1haWwgZnJvbSB1cyBpbiBlcnJvciwgY29udGFjdCA8YSBocmVmPSJtYWlsdG86cHJpdmFjeUBraXZ1dG8uY29tIj5wcml2YWN5QGtpdnV0by5jb208L2E+LjwvcD4NCjxwPg0KCVlvdSBtYXkgcmVjZWl2ZSBvbmUgb3IgbW9yZSBvZiB0aGUgZm9sbG93aW5nIGVtYWlscyBmcm9tIEtpdnV0byBTb2x1dGlvbnMuPC9wPg0KPGg0Pg0KCUFjY291bnQtIGFuZCBTZXJ2aWNlLVJlbGF0ZWQgRW1haWw8L2g0Pg0KPHA+DQoJS2l2dXRvIFNvbHV0aW9ucyBJbmMuIHJlc2VydmVzIHRoZSByaWdodCB0byBzZW5kIHlvdSBlbWFpbHMgcmVsYXRpbmcgdG8geW91ciBhY2NvdW50IHN0YXR1cy4gVGhpcyBpbmNsdWRlcyBvcmRlciBjb25maXJtYXRpb25zLCByZW5ld2FsL2V4cGlyYXRpb24gbm90aWNlcywgbm90aWNlcyBvZiBjcmVkaXQtY2FyZCBwcm9ibGVtcywgb3RoZXIgdHJhbnNhY3Rpb25hbCBlbWFpbHMgYW5kIG5vdGlmaWNhdGlvbnMgYWJvdXQgbWFqb3IgY2hhbmdlcyB0byB0aGUgc2l0ZSBzZXJ2aWNlcyBhbmQvb3IgdG8gb3VyIFByaXZhY3kgUG9saWN5LiBJZiB5b3UgaGF2ZSByZWdpc3RlcmVkIGZvciBvbmxpbmUgZGlzY3Vzc2lvbnMgb3Igb3RoZXIgc2VydmljZXMsIHlvdSBtYXkgcmVjZWl2ZSBhbiBlbWFpbCBzcGVjaWZpYyB0byB5b3VyIHBhcnRpY2lwYXRpb24gaW4gdGhvc2UgYWN0aXZpdGllcy48L3A+DQo8aDQ+DQoJRW1haWwgTmV3c2xldHRlcnM8L2g0Pg0KPHA+DQoJS2l2dXRvIFNvbHV0aW9ucyBJbmMuIG9mZmVyIHNldmVyYWwgZW1haWwgbmV3c2xldHRlcnMuIFlvdSB3aWxsIG9ubHkgcmVjZWl2ZSB0aGVzZSBpZiB5b3UgcHJldmlvdXNseSBjaG9zZSB0byBvcHQtaW4gdG8gdGhlc2UgdHlwZXMgb2YgY29tbXVuaWNhdGlvbnMuIElmIHlvdSBubyBsb25nZXIgd2lzaCB0byByZWNlaXZlIGEgc3BlY2lmaWMgbmV3c2xldHRlciwgZm9sbG93IHRoZSDigJx1bnN1YnNjcmliZeKAnSBpbnN0cnVjdGlvbnMgbG9jYXRlZCBuZWFyIHRoZSBib3R0b20gb2YgZWFjaCBuZXdzbGV0dGVyLjwvcD4NCjxoND4NCglQcm9tb3Rpb25hbCBFbWFpbDwvaDQ+DQo8cD4NCglLaXZ1dG8gU29sdXRpb25zIEluYy4gbWF5IHBlcmlvZGljYWxseSBlbWFpbCB5b3UgbWVzc2FnZXMgYWJvdXQgcHJvZHVjdHMgYW5kIHNlcnZpY2VzIHRoYXQgS2l2dXRvIHRoaW5rcyBtYXkgYmUgb2YgaW50ZXJlc3QgdG8geW91IChpZiB5b3UgaGF2ZSBwcmV2aW91c2x5IG9wdGVkIGluIHRvIHJlY2VpdmUgdGhlc2UgdHlwZXMgb2YgY29tbXVuaWNhdGlvbnMpLiBZb3UgY2FuIGNob29zZSBub3QgdG8gcmVjZWl2ZSBtZXNzYWdlcyBpbiB0aGUgZnV0dXJlIGJ5IGZvbGxvd2luZyB0aGUg4oCcdW5zdWJzY3JpYmXigJ0gaW5zdHJ1Y3Rpb25zIGxvY2F0ZWQgbmVhciB0aGUgYm90dG9tIG9mIGVhY2ggZW1haWwuPC9wPg0KPGg0Pg0KCVN1cnZleSBFbWFpbDwvaDQ+DQo8cD4NCglLaXZ1dG8gbWF5IHNlbmQgeW91IGVtYWlscyBpbnZpdGluZyB5b3UgdG8gcGFydGljaXBhdGUgaW4gdXNlciBzdXJ2ZXlzLCBhc2tpbmcgZm9yIGZlZWRiYWNrIG9uIG91ciBzZXJ2aWNlcyBhbmQgZXhpc3Rpbmcgb3IgcHJvc3BlY3RpdmUgcHJvZHVjdHMgYW5kIHNlcnZpY2VzLCBhcyB3ZWxsIGFzIGluZm9ybWF0aW9uIHRvIGJldHRlciB1bmRlcnN0YW5kIG91ciB1c2Vycy4gVXNlciBzdXJ2ZXlzIGdyZWF0bHkgaGVscCB1cyB0byBpbXByb3ZlIG91ciBzZXJ2aWNlcywgYW5kIGFueSBpbmZvcm1hdGlvbiBLaXZ1dG8gb2J0YWlucyBpbiBzdWNoIHN1cnZleXMgd2lsbCBiZSB1c2VkIGludGVybmFsbHkuIFRoZSBpbmZvcm1hdGlvbiBtYXkgYmUgc2hhcmVkIHdpdGggYWZmaWxpYXRlZCB0aGlyZCBwYXJ0aWVzIGluIGFnZ3JlZ2F0ZSBmb3JtIG9ubHkuPC9wPg0KPGg0Pg0KCUhUTUwgRW1haWw8L2g0Pg0KPHA+DQoJSWYgeW91IHNpZ24gdXAgdG8gcmVjZWl2ZSBlbWFpbCBmcm9tIHVzIHlvdSB3aWxsIHJlY2VpdmUgZW1haWxzIGluIGJvdGggcGxhaW4gdGV4dCBhbmQgSFRNTCAod2l0aCBpbWFnZXMpIGZvcm1hdC4gSWYgeW91IHNlbGVjdCB0byB2aWV3IG91ciBlbWFpbHMgaW4gdGhlIEhUTUwgZm9ybWF0LCBLaXZ1dG8gbWF5IHBsYWNlIGEgb25lLXBpeGVsIC5naWYgdG8gZGV0ZXJtaW5lIHdoZXRoZXIgb3Igbm90IHJlYWRlcnMgdmlld2VkIHRoZSBlbWFpbC4gVGhpcyBwcm9jZXNzIGRvZXMgbm90IGxlYXZlIGFueSBpbmZvcm1hdGlvbiBvbiB5b3VyIGNvbXB1dGVyLCBub3IgZG9lcyBpdCBjb2xsZWN0IGluZm9ybWF0aW9uIGZyb20geW91ciBjb21wdXRlci4gS2l2dXRvIG1heSBzaGFyZSB0aGlzIGRhdGEgd2l0aCBvdGhlciB0aGlyZCBwYXJ0aWVzIGluIGFnZ3JlZ2F0ZSBmb3JtIG9ubHkgdG8gaW1wcm92ZSB0aGUgcXVhbGl0eSBvZiB0aGUgZW1haWxzIGFuZCBvZmZlcnMgS2l2dXRvIGRpc3RyaWJ1dGVzLjwvcD4NCjxoND4NCglFbWFpbHMgRnJvbSBZb3U8L2g0Pg0KPHA+DQoJSWYgeW91IHNlbmQgdXMgZW1haWxzLCBiZSBhd2FyZSB0aGF0IGluZm9ybWF0aW9uIGRpc2Nsb3NlZCBpbiBlbWFpbHMgbWF5IG5vdCBiZSBzZWN1cmUgb3IgZW5jcnlwdGVkIGFuZCB0aHVzIG1heSBiZSBhdmFpbGFibGUgdG8gb3RoZXJzLiBJdCBpcyByZWNvbW1lbmRlZCB0aGF0IHlvdSBleGVyY2lzZSBjYXV0aW9uIHdoZW4gZGVjaWRpbmcgdG8gZGlzY2xvc2UgYW55IHBlcnNvbmFsIG9yIGNvbmZpZGVudGlhbCBpbmZvcm1hdGlvbiBpbiBlbWFpbHMuIEtpdnV0byB3aWxsIHVzZSB5b3VyIGVtYWlsIGFkZHJlc3MgdG8gcmVzcG9uZCBkaXJlY3RseSB0byB5b3VyIHF1ZXN0aW9ucyBvciBjb21tZW50cy48L3A+DQo8aDM+DQoJOC4gPGEgbmFtZT0iOCI+PC9hPldobyBjYW4gSSBjb250YWN0IHdpdGggcXVlc3Rpb25zIG9yIGNvbmNlcm5zIGFib3V0IHRoaXMgcG9saWN5PzwvaDM+DQo8cD4NCglJZiB5b3UgaGF2ZSBxdWVzdGlvbnMsIGNvbW1lbnRzLCBjb25jZXJucywgb3IgY29tcGxhaW50cyBhYm91dCB0aGlzIHByaXZhY3kgb3IgS2l2dXRv4oCZcyBoYW5kbGluZyBvZiB5b3VyIHBlcnNvbmFsIGluZm9ybWF0aW9uLCB5b3UgZ2V0IGluIHRvdWNoIHdpdGggdXMgaW4gYW55IG9mIHRoZSBmb2xsb3dpbmcgd2F5cy48L3A+DQo8aDQ+DQoJQnkgRW1haWw8L2g0Pg0KPHA+DQoJUGxlYXNlIGRpcmVjdCBhbGwgcHJpdmFjeS1yZWxhdGVkIGlucXVpcmllcyB0byA8YSBocmVmPSJtYWlsdG86cHJpdmFjeUBraXZ1dG8uY29tIj5wcml2YWN5QGtpdnV0by5jb208L2E+LjwvcD4NCjxoND4NCglCeSBQaG9uZTwvaDQ+DQo8dGFibGUgYm9yZGVyPSIwIiBjZWxscGFkZGluZz0iMCIgY2VsbHNwYWNpbmc9IjAiPg0KCTx0Ym9keT4NCgkJPHRyPg0KCQkJPHRkIHN0eWxlPSJ3aWR0aDoxODBweDsiPg0KCQkJCTxwPg0KCQkJCQlVU0EvQ2FuYWRhICh0b2xsIGZyZWUpPC9wPg0KCQkJPC90ZD4NCgkJCTx0ZCBzdHlsZT0id2lkdGg6NDI1cHg7Ij4NCgkJCQk8cD4NCgkJCQkJMS04NjYtNDM1LTQ3MjI8L3A+DQoJCQk8L3RkPg0KCQk8L3RyPg0KCQk8dHI+DQoJCQk8dGQgc3R5bGU9IndpZHRoOjE4MHB4OyI+DQoJCQkJPHA+DQoJCQkJCUF1c3RyYWxpYSAodG9sbCBmcmVlKTwvcD4NCgkJCTwvdGQ+DQoJCQk8dGQgc3R5bGU9IndpZHRoOjQyNXB4OyI+DQoJCQkJPHA+DQoJCQkJCTEtODAwLTQyNi0yMzE8L3A+DQoJCQk8L3RkPg0KCQk8L3RyPg0KCQk8dHI+DQoJCQk8dGQgc3R5bGU9IndpZHRoOjE4MHB4OyI+DQoJCQkJPHA+DQoJCQkJCUZyYW5jZSAodG9sbCBmcmVlKTwvcD4NCgkJCTwvdGQ+DQoJCQk8dGQgc3R5bGU9IndpZHRoOjQyNXB4OyI+DQoJCQkJPHA+DQoJCQkJCTA4MDAtOTE2MDIxPC9wPg0KCQkJPC90ZD4NCgkJPC90cj4NCgkJPHRyPg0KCQkJPHRkIHN0eWxlPSJ3aWR0aDoxODBweDsiPg0KCQkJCTxwPg0KCQkJCQlHZXJtYW55ICh0b2xsIGZyZWUpPC9wPg0KCQkJPC90ZD4NCgkJCTx0ZCBzdHlsZT0id2lkdGg6NDI1cHg7Ij4NCgkJCQk8cD4NCgkJCQkJMDgwMC0xODItODYxMjwvcD4NCgkJCTwvdGQ+DQoJCTwvdHI+DQoJCTx0cj4NCgkJCTx0ZCBzdHlsZT0id2lkdGg6MTgwcHg7Ij4NCgkJCQk8cD4NCgkJCQkJSG9uZyBLb25nICh0b2xsIGZyZWUpPC9wPg0KCQkJPC90ZD4NCgkJCTx0ZCBzdHlsZT0id2lkdGg6NDI1cHg7Ij4NCgkJCQk8cD4NCgkJCQkJODAwLTk2OC03ODE8L3A+DQoJCQk8L3RkPg0KCQk8L3RyPg0KCQk8dHI+DQoJCQk8dGQgc3R5bGU9IndpZHRoOjE4MHB4OyI+DQoJCQkJPHA+DQoJCQkJCU1hbGF5c2lhICh0b2xsIGZyZWUpPC9wPg0KCQkJPC90ZD4NCgkJCTx0ZCBzdHlsZT0id2lkdGg6NDI1cHg7Ij4NCgkJCQk8cD4NCgkJCQkJMS04MDAtODE1LTMwMjwvcD4NCgkJCTwvdGQ+DQoJCTwvdHI+DQoJCTx0cj4NCgkJCTx0ZCBzdHlsZT0id2lkdGg6MTgwcHg7Ij4NCgkJCQk8cD4NCgkJCQkJU3BhaW4gKHRvbGwgZnJlZSk8L3A+DQoJCQk8L3RkPg0KCQkJPHRkIHN0eWxlPSJ3aWR0aDo0MjVweDsiPg0KCQkJCTxwPg0KCQkJCQk5MDAtODA5NzU0PC9wPg0KCQkJPC90ZD4NCgkJPC90cj4NCgkJPHRyPg0KCQkJPHRkIHN0eWxlPSJ3aWR0aDoxODBweDsiPg0KCQkJCTxwPg0KCQkJCQlVbml0ZWQgS2luZ2RvbSAodG9sbCBmcmVlKTwvcD4NCgkJCTwvdGQ+DQoJCQk8dGQgc3R5bGU9IndpZHRoOjQyNXB4OyI+DQoJCQkJPHA+DQoJCQkJCTAtODAwLTA5OC04NDM2PC9wPg0KCQkJPC90ZD4NCgkJPC90cj4NCgkJPHRyPg0KCQkJPHRkIHN0eWxlPSJ3aWR0aDoxODBweDsiPg0KCQkJCTxwPg0KCQkJCQlPdGhlciBjb3VudHJpZXM8L3A+DQoJCQk8L3RkPg0KCQkJPHRkIHN0eWxlPSJ3aWR0aDo0MjVweDsiPg0KCQkJCTxwPg0KCQkJCQkrNDQtODQ1LTg2OTc1NjY8L3A+DQoJCQk8L3RkPg0KCQk8L3RyPg0KCTwvdGJvZHk+DQo8L3RhYmxlPg0KPGg0Pg0KCTxzdHJvbmc+QnkgTWFpbDwvc3Ryb25nPjwvaDQ+DQo8dGFibGUgYm9yZGVyPSIwIiBjZWxscGFkZGluZz0iMCIgY2VsbHNwYWNpbmc9IjAiPg0KCTx0Ym9keT4NCgkJPHRyPg0KCQkJPHRkIHN0eWxlPSJ3aWR0aDoxMjNweDtoZWlnaHQ6ODJweDsiPg0KCQkJCTxwPg0KCQkJCQk8c3Ryb25nPk5vcnRoIEFtZXJpY2E8L3N0cm9uZz48YnIgLz4NCgkJCQkJKEhlYWQgT2ZmaWNlKTwvcD4NCgkJCTwvdGQ+DQoJCQk8dGQgc3R5bGU9IndpZHRoOjQ4MnB4O2hlaWdodDo4MnB4OyI+DQoJCQkJPHA+DQoJCQkJCUtpdnV0byBTb2x1dGlvbnMgSW5jLjxiciAvPg0KCQkJCQkxMjYgWW9yayBTdC4sIFN1aXRlIDIwMDwvcD4NCgkJCQk8cD4NCgkJCQkJT3R0YXdhLCBPbnRhcmlvLCBDYW5hZGE8L3A+DQoJCQkJPHA+DQoJCQkJCUsxTiA1VDU8L3A+DQoJCQk8L3RkPg0KCQk8L3RyPg0KCQk8dHI+DQoJCQk8dGQgc3R5bGU9IndpZHRoOjEyM3B4O2hlaWdodDo4MnB4OyI+DQoJCQkJPHA+DQoJCQkJCTxzdHJvbmc+RU1FQTwvc3Ryb25nPjwvcD4NCgkJCTwvdGQ+DQoJCQk8dGQgc3R5bGU9IndpZHRoOjQ4MnB4O2hlaWdodDo4MnB4OyI+DQoJCQkJPHA+DQoJCQkJCUtpdnV0byBTb2x1dGlvbnMgSW5jLjwvcD4NCgkJCQk8cD4NCgkJCQkJMjxzdXA+bmQ8L3N1cD4gRmxvb3IsIDE2IFNvdXRoIE1haW4gU3RyZWV0PGJyIC8+DQoJCQkJCU5hYXMsIENvLiBLaWxkYXJlLCBJcmVsYW5kPC9wPg0KCQkJPC90ZD4NCgkJPC90cj4NCgk8L3Rib2R5Pg0KPC90YWJsZT4NCjxwPg0KCcKgPC9wPmRkAiMPZBYIAgcPDxYEHwQFIX4vV2ViU3RvcmUvU3VwcG9ydC9Db250YWN0VXMuYXNweB4GVGFyZ2V0BQVfc2VsZmRkAgkPDxYEHwQFJH4vV2ViU3RvcmUvU3VwcG9ydC9TYWZlU2hvcHBpbmcuYXNweB8QBQVfc2VsZmRkAgsPDxYEHwQFJX4vV2ViU3RvcmUvU3VwcG9ydC9Qcml2YWN5UG9saWN5LmFzcHgfEAUFX3NlbGZkZAIVDw8WAh8DBRV2NC43LjcxMjUuMjggKEZld3MwNilkZAILDxYCHwNlZGTRxMJynAPNN/JkG675MUD27NYg2Q==" />
</div>

<script type="text/javascript">
//<![CDATA[
var theForm = document.forms['aspnetForm'];
if (!theForm) {
    theForm = document.aspnetForm;
}
function __doPostBack(eventTarget, eventArgument) {
    if (!theForm.onsubmit || (theForm.onsubmit() != false)) {
        theForm.__EVENTTARGET.value = eventTarget;
        theForm.__EVENTARGUMENT.value = eventArgument;
        theForm.submit();
    }
}
//]]>
</script>


<script src="/WebResource.axd?d=u6a1ShgHp8oy3Xk0QdrLMpAZkyIUYqBxBKeldwOU4P6dLogVK-mcAZiul1SNKO3WL1Xd38Z9CUvwdlsarV35O5VhXlM1&amp;t=636681459604795562" type="text/javascript"></script>


<script src="//e5.onthehub.com/static/js/common/analytics.js?4.7.7125.28" type="text/javascript"></script>
<script type="text/javascript">
//<![CDATA[
function HideStatusMessages() {{var statusMessages = document.all ? document.all['ctl00_smStatusMessages'] : document.getElementById('ctl00_smStatusMessages');statusMessages.style.display = 'none'; return false;}}//]]>
</script>

<script src="/ScriptResource.axd?d=ADX6pgLHQhaJu07wkPVBzCPj15G4gddXh9Z8y4-O0GEfrsoX9w94YjHB8upW_MlSmptz0KKrAwuOaXWYesI6-XMi7HAXBtgaTX9dWRgeOKaT-_vfxQXPnUsNHejeeH0VpC3xcpPhJ2dKo9xZX8MngcRPaEXuw2jpKyl2oMNEhaJZESZs0&amp;t=545ba255" type="text/javascript"></script>
<script src="/ScriptResource.axd?d=Vuo1A-JX6MBacXB_LZ4djyr8WPkawjwNr4h0STdXJwVokmmZvLToRyclrBf8nyG5i8qbu2AsyNQpKV9cL85FGNUTuB8RH1pcP5nIKOfLRlfwgDgyNFhGMmFTFlmlADqN8lvtzCU3EeXtiW5dKrZRJk4KNl-6YgUZo-TKrLqecOSMGEsO0&amp;t=545ba255" type="text/javascript"></script>
<script type="text/javascript">
//<![CDATA[
var PageMethods = function() {
PageMethods.initializeBase(this);
this._timeout = 0;
this._userContext = null;
this._succeeded = null;
this._failed = null;
}
PageMethods.prototype = {
_get_path:function() {
 var p = this.get_path();
 if (p) return p;
 else return PageMethods._staticInstance.get_path();},
OptInForTypeNoticeOnly:function(inputData,succeededCallback, failedCallback, userContext) {
return this._invoke(this._get_path(), 'OptInForTypeNoticeOnly',false,{inputData:inputData},succeededCallback,failedCallback,userContext); },
RemoveUserSavedPaymentMethod:function(userSavedPaymentMethodID,succeededCallback, failedCallback, userContext) {
return this._invoke(this._get_path(), 'RemoveUserSavedPaymentMethod',false,{userSavedPaymentMethodID:userSavedPaymentMethodID},succeededCallback,failedCallback,userContext); },
HideTestBanner:function(webstoreID,succeededCallback, failedCallback, userContext) {
return this._invoke(this._get_path(), 'HideTestBanner',false,{webstoreID:webstoreID},succeededCallback,failedCallback,userContext); },
ChangeResourceOptOutStatus:function(userResourceID,optOutStatus,succeededCallback, failedCallback, userContext) {
return this._invoke(this._get_path(), 'ChangeResourceOptOutStatus',false,{userResourceID:userResourceID,optOutStatus:optOutStatus},succeededCallback,failedCallback,userContext); },
RemoveFromCartAsync:function(data,succeededCallback, failedCallback, userContext) {
return this._invoke(this._get_path(), 'RemoveFromCartAsync',false,{data:data},succeededCallback,failedCallback,userContext); },
AddUserToWaitListAsync:function(input,succeededCallback, failedCallback, userContext) {
return this._invoke(this._get_path(), 'AddUserToWaitListAsync',false,{input:input},succeededCallback,failedCallback,userContext); },
AddOfferingToCartAsync:function(input,succeededCallback, failedCallback, userContext) {
return this._invoke(this._get_path(), 'AddOfferingToCartAsync',false,{input:input},succeededCallback,failedCallback,userContext); },
AddAddonToCartAsync:function(input,succeededCallback, failedCallback, userContext) {
return this._invoke(this._get_path(), 'AddAddonToCartAsync',false,{input:input},succeededCallback,failedCallback,userContext); },
AddShopperResourceToCartAsync:function(input,succeededCallback, failedCallback, userContext) {
return this._invoke(this._get_path(), 'AddShopperResourceToCartAsync',false,{input:input},succeededCallback,failedCallback,userContext); },
CountCartItems:function(input,succeededCallback, failedCallback, userContext) {
return this._invoke(this._get_path(), 'CountCartItems',false,{input:input},succeededCallback,failedCallback,userContext); },
UpdateQuantityAsync:function(input,succeededCallback, failedCallback, userContext) {
return this._invoke(this._get_path(), 'UpdateQuantityAsync',false,{input:input},succeededCallback,failedCallback,userContext); },
ClearNewAdditionsToCart:function(userID,succeededCallback, failedCallback, userContext) {
return this._invoke(this._get_path(), 'ClearNewAdditionsToCart',false,{userID:userID},succeededCallback,failedCallback,userContext); },
UpdateCrossSellOfferingSelection:function(productID,offeringID,accessGuaranteeStatus,offeringPrice,isSelected,succeededCallback, failedCallback, userContext) {
return this._invoke(this._get_path(), 'UpdateCrossSellOfferingSelection',false,{productID:productID,offeringID:offeringID,accessGuaranteeStatus:accessGuaranteeStatus,offeringPrice:offeringPrice,isSelected:isSelected},succeededCallback,failedCallback,userContext); },
GetCartSubtotal:function(succeededCallback, failedCallback, userContext) {
return this._invoke(this._get_path(), 'GetCartSubtotal',false,{},succeededCallback,failedCallback,userContext); }}
PageMethods.registerClass('PageMethods',Sys.Net.WebServiceProxy);
PageMethods._staticInstance = new PageMethods();
PageMethods.set_path = function(value) { PageMethods._staticInstance.set_path(value); }
PageMethods.get_path = function() { return PageMethods._staticInstance.get_path(); }
PageMethods.set_timeout = function(value) { PageMethods._staticInstance.set_timeout(value); }
PageMethods.get_timeout = function() { return PageMethods._staticInstance.get_timeout(); }
PageMethods.set_defaultUserContext = function(value) { PageMethods._staticInstance.set_defaultUserContext(value); }
PageMethods.get_defaultUserContext = function() { return PageMethods._staticInstance.get_defaultUserContext(); }
PageMethods.set_defaultSucceededCallback = function(value) { PageMethods._staticInstance.set_defaultSucceededCallback(value); }
PageMethods.get_defaultSucceededCallback = function() { return PageMethods._staticInstance.get_defaultSucceededCallback(); }
PageMethods.set_defaultFailedCallback = function(value) { PageMethods._staticInstance.set_defaultFailedCallback(value); }
PageMethods.get_defaultFailedCallback = function() { return PageMethods._staticInstance.get_defaultFailedCallback(); }
PageMethods.set_enableJsonp = function(value) { PageMethods._staticInstance.set_enableJsonp(value); }
PageMethods.get_enableJsonp = function() { return PageMethods._staticInstance.get_enableJsonp(); }
PageMethods.set_jsonpCallbackParameter = function(value) { PageMethods._staticInstance.set_jsonpCallbackParameter(value); }
PageMethods.get_jsonpCallbackParameter = function() { return PageMethods._staticInstance.get_jsonpCallbackParameter(); }
PageMethods.set_path("PrivacyPolicy.aspx");
PageMethods.OptInForTypeNoticeOnly= function(inputData,onSuccess,onFailed,userContext) {PageMethods._staticInstance.OptInForTypeNoticeOnly(inputData,onSuccess,onFailed,userContext); }
PageMethods.RemoveUserSavedPaymentMethod= function(userSavedPaymentMethodID,onSuccess,onFailed,userContext) {PageMethods._staticInstance.RemoveUserSavedPaymentMethod(userSavedPaymentMethodID,onSuccess,onFailed,userContext); }
PageMethods.HideTestBanner= function(webstoreID,onSuccess,onFailed,userContext) {PageMethods._staticInstance.HideTestBanner(webstoreID,onSuccess,onFailed,userContext); }
PageMethods.ChangeResourceOptOutStatus= function(userResourceID,optOutStatus,onSuccess,onFailed,userContext) {PageMethods._staticInstance.ChangeResourceOptOutStatus(userResourceID,optOutStatus,onSuccess,onFailed,userContext); }
PageMethods.RemoveFromCartAsync= function(data,onSuccess,onFailed,userContext) {PageMethods._staticInstance.RemoveFromCartAsync(data,onSuccess,onFailed,userContext); }
PageMethods.AddUserToWaitListAsync= function(input,onSuccess,onFailed,userContext) {PageMethods._staticInstance.AddUserToWaitListAsync(input,onSuccess,onFailed,userContext); }
PageMethods.AddOfferingToCartAsync= function(input,onSuccess,onFailed,userContext) {PageMethods._staticInstance.AddOfferingToCartAsync(input,onSuccess,onFailed,userContext); }
PageMethods.AddAddonToCartAsync= function(input,onSuccess,onFailed,userContext) {PageMethods._staticInstance.AddAddonToCartAsync(input,onSuccess,onFailed,userContext); }
PageMethods.AddShopperResourceToCartAsync= function(input,onSuccess,onFailed,userContext) {PageMethods._staticInstance.AddShopperResourceToCartAsync(input,onSuccess,onFailed,userContext); }
PageMethods.CountCartItems= function(input,onSuccess,onFailed,userContext) {PageMethods._staticInstance.CountCartItems(input,onSuccess,onFailed,userContext); }
PageMethods.UpdateQuantityAsync= function(input,onSuccess,onFailed,userContext) {PageMethods._staticInstance.UpdateQuantityAsync(input,onSuccess,onFailed,userContext); }
PageMethods.ClearNewAdditionsToCart= function(userID,onSuccess,onFailed,userContext) {PageMethods._staticInstance.ClearNewAdditionsToCart(userID,onSuccess,onFailed,userContext); }
PageMethods.UpdateCrossSellOfferingSelection= function(productID,offeringID,accessGuaranteeStatus,offeringPrice,isSelected,onSuccess,onFailed,userContext) {PageMethods._staticInstance.UpdateCrossSellOfferingSelection(productID,offeringID,accessGuaranteeStatus,offeringPrice,isSelected,onSuccess,onFailed,userContext); }
PageMethods.GetCartSubtotal= function(onSuccess,onFailed,userContext) {PageMethods._staticInstance.GetCartSubtotal(onSuccess,onFailed,userContext); }
var gtc = Sys.Net.WebServiceProxy._generateTypedConstructor;
Type.registerNamespace('eAcademy.Munthika.Web.Common');
if (typeof(eAcademy.Munthika.Web.Common.CartResult) === 'undefined') {
eAcademy.Munthika.Web.Common.CartResult=gtc("eAcademy.Munthika.Web.Common.CartResult");
eAcademy.Munthika.Web.Common.CartResult.registerClass('eAcademy.Munthika.Web.Common.CartResult');
}
if (typeof(eAcademy.Munthika.Web.Common.ActionResult) === 'undefined') {
eAcademy.Munthika.Web.Common.ActionResult=gtc("eAcademy.Munthika.Web.Common.ActionResult");
eAcademy.Munthika.Web.Common.ActionResult.registerClass('eAcademy.Munthika.Web.Common.ActionResult');
}
if (typeof(eAcademy.Munthika.Web.Common.CrossSellResult) === 'undefined') {
eAcademy.Munthika.Web.Common.CrossSellResult=gtc("eAcademy.Munthika.Web.Common.CrossSellResult");
eAcademy.Munthika.Web.Common.CrossSellResult.registerClass('eAcademy.Munthika.Web.Common.CrossSellResult');
}
Type.registerNamespace('eAcademy.Munthika.Entities');
if (typeof(eAcademy.Munthika.Entities.AccessGuaranteeStatus) === 'undefined') {
eAcademy.Munthika.Entities.AccessGuaranteeStatus = function() { throw Error.invalidOperation(); }
eAcademy.Munthika.Entities.AccessGuaranteeStatus.prototype = {None: 0,NotApplicable: 1,Basic: 2,ExtendedIncludedForFree: 4,PurchasedExtended: 8,PurchasedRetrieval: 16}
eAcademy.Munthika.Entities.AccessGuaranteeStatus.registerEnum('eAcademy.Munthika.Entities.AccessGuaranteeStatus', true);
}
//]]>
</script>

<div>

	<input type="hidden" name="__VIEWSTATEGENERATOR" id="__VIEWSTATEGENERATOR" value="98D4A53E" />
	<input type="hidden" name="__PREVIOUSPAGE" id="__PREVIOUSPAGE" value="42oWp96ZmECnpsvtrMnyRb2U1HX86f-vqaJ6SrFwfaftuHcsqngzB941KScjRI1GF5YDEt0HDpegMw-FEL2hUlmFbqUUyxFvK58Nzg5Cz2ckKGFGhBTf1uFkF5JPCvlhjRmxXA2" />
	<input type="hidden" name="__EVENTVALIDATION" id="__EVENTVALIDATION" value="/wEdAAfzKhQrsmNbAnAo5eQKNO5KVTvu3gWKD/R4jdhvYGyOVMx8J+VBLuxwTXAOXg9eqdVmsGuKKp5oS00Y4nHNvjI7VXpGQB+5+uolroumqcYWCyES1Bs+3i9wBXINDiumMtj1yEuv5c7anYxf+FNIvF++DXm0wHuC0XWfB1OPEFaHi63z8fk=" />
</div>
			<script type="text/javascript">
//<![CDATA[
Sys.WebForms.PageRequestManager._initialize('ctl00$smScriptManager', 'aspnetForm', ['tctl00$ctl05','','tctl00$upCheckout',''], [], [], 300, 'ctl00');
//]]>
</script>

			
			
			<div id="ctl00_divWebStoreMaster">
				<input type="hidden" name="ctl00$hfUILocale" id="ctl00_hfUILocale" value="en_US" />
				
				<div id="header">
					<div class="navbar navbar-default" id="e5-1st-nav">
						<div class="container">
							<div id="ctl00_pnlRightMenuCollapse" class="row">
	
								<div class="navbar-header">									
									<div class="col-sm-offset-10 col-sm-2 col-xs-12">
										<div class="row">
											<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#kv-usermenu">
												<span class="sr-only">Toggle Navigation</span>
												<span class="icon-bar"></span>
												<span class="icon-bar"></span>
												<span class="icon-bar"></span>
											</button>
										</div>
									</div>
								</div>
							
</div>
							<div id="header-row" class="row" role="navigation">
								<div class="header-row-right">
                                    
									    <div class="collapse navbar-collapse" id="kv-usermenu" style="overflow:hidden">
										    <div class="clearfix">
											    <ul class="nav navbar-nav navbar-right">												
												    <li>
													    <a id="ctl00_hlHomeTop" href="../ProductsByMajorVersionList.aspx?cmi_cs=1&amp;cmi_mnuMain=ed6ad73c-7bc7-e011-ae14-f04da23e67f6">Home</a>
												    </li>
												    <li>
													    <a id="ctl00_hlHelp" href="WebStoreHelpContents.aspx">Help</a>
												    </li>												
												    <li>
													    <a id="ctl00_ucCultureCurrencySelection_hlCulture" class="language" aria-label="Webstore culture and currency selection" href="../Common/SelectCurrencyAndCulture.aspx?rurl=%2fWebstore%2fSupport%2fPrivacyPolicy.aspx"><span id="ctl00_ucCultureCurrencySelection_linkCurrency" class="sr-only">US Dollars</span><span id="ctl00_ucCultureCurrencySelection_imgCountryLink" class="flag-icon flag-icon-us"></span><span id="ctl00_ucCultureCurrencySelection_lblCountry">English</span></a>

												    </li>
											    </ul>
										    </div>
										    <div id="ctl00_pnlUserContext" class="clearfix">
	
											    <ul class="nav navbar-nav navbar-right">																					
												    
												    <li id="ctl00_liSignIn">
													    <a id="ctl00_hlSignIn" href="/WebStore/Security/SignIn.aspx?rurl=%2fWebstore%2fSupport%2fPrivacyPolicy.aspx%3f">Sign In</a>
												    </li>
												    <li id="ctl00_registerListItem">
													    <a id="ctl00_llbRegister" href="javascript:__doPostBack(&#39;ctl00$llbRegister&#39;,&#39;&#39;)">Register</a>
												    </li>
											    </ul>
										    
</div>																																
									    </div>
                                    
								</div>								
								<div class="header-row-left">
									<div class="webstore-logo">
										<a id="ctl00_hlHome" href="../ProductsByMajorVersionList.aspx?cmi_cs=1&amp;cmi_mnuMain=ed6ad73c-7bc7-e011-ae14-f04da23e67f6"><img src="https://elmsprodcdnendpoint.azureedge.net/attachments/15/49c547ba-f56d-dd11-bb6c-0030485a6b08/b4508715-1050-4b81-8d8b-de9cc7e3afbd.jpg" alt="OnTheHub" style="border-width:0px;" /></a>
                                        
									</div>
								</div>
							</div>
						</div>
					</div>
					<div id="e52ndNavContainer" class="container">
	
						<div ID="e5-2nd-nav" class="navbar">
							<div class="col-xs-12">
								<div id="ctl00_pnlSearch" class="search-panel" role="search" onkeypress="javascript:return WebForm_FireDefaultButton(event, &#39;ctl00_btnSearch&#39;)">
		
									<div class="form-group has-feedback">
										<div class="input-group">
											<span class='sr-only'>Product Search</span>
											<input name="ctl00$txtProductSearchName" type="text" maxlength="100" id="ctl00_txtProductSearchName" class="form-control" title="Product Search" placeholder="Product Search" />
											<span class="input-group-addon unpadded-group">
												<input type="submit" name="ctl00$btnSearch" value="" onclick="showDialog({&#39;title&#39;:kvLocalStore.Common.PleaseWait,&#39;content&#39;:kvLocalStore.Common.Processing,&#39;allowClosing&#39;:false});return true;WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$btnSearch&quot;, &quot;&quot;, false, &quot;&quot;, &quot;../ProductSearchOfferingList.aspx&quot;, false, false))" id="ctl00_btnSearch" class="fa search-btn" aria-label="Search" />
											</span>
										</div>
									</div>
								
	</div>
							</div>
							<div class="row">
								<div class="col-xs-12">
									<div class="tab-wrapper" id="ctl00_mnuMain">
		<div class="parent-nav" role="navigation">
			<ul class="nav nav-tabs">
				<li role="presentation"><a href="/WebStore/ProductsByMajorVersionList.aspx?cmi_mnuMain=ed6ad73c-7bc7-e011-ae14-f04da23e67f6">Most Popular</a></li><li role="presentation"><a href="/WebStore/ProductsByMajorVersionList.aspx?cmi_mnuMain=b1a6c67e-78c7-e011-ae14-f04da23e67f6">New Deals</a></li><li role="presentation"><a href="/WebStore/ProductsByMajorVersionList.aspx?cmi_mnuMain=2ff73789-74c7-e011-ae14-f04da23e67f6">Data Analysis</a></li><li role="presentation"><a href="/WebStore/ProductsByMajorVersionList.aspx?cmi_mnuMain=59b45b5b-7cc7-e011-ae14-f04da23e67f6">Photo, Video & Design</a></li><li role="presentation"><a href="/WebStore/ProductsByMajorVersionList.aspx?cmi_mnuMain=d6d02f44-7dc7-e011-ae14-f04da23e67f6">Security & Utilities</a></li><li role="presentation"><a href="/WebStore/ProductsByMajorVersionList.aspx?cmi_mnuMain=7ff9e421-7fc7-e011-ae14-f04da23e67f6">Business & Office</a></li><li role="presentation"><a href="/WebStore/ProductsByMajorVersionList.aspx?cmi_mnuMain=8659da1b-241d-e611-941a-b8ca3a5db7a1">Browse by Publisher</a></li><li role="presentation" class="dropdown" style="display:none"><a data-toggle="dropdown" class="dropdown-toggle">More Options</a><ul class="dropdown-menu" id="parent-nav-dropdown">

				</ul></li>
			</ul>
		</div><div class="NavigationChildMenuSpacer PrimaryColor NavigationMenuPrimaryColor"></div>
	</div>
								</div>
							</div>
						</div>
					
</div>
				</div>
				<div id="main">
					<div class="container">
						<div class="row">
							<div class="col-sm-12">
								
								
								
								
							</div>
						</div>
						<div class="row">
							<div class="col-sm-12">
								<div id="contentHeading" class="StatusMessageContainer">
									
									<div aria-live="polite" class="status-message-container-inner">
										
									</div>
									<div id="validationSummaryContainer" aria-live="assertive" aria-atomic="true" tabindex="-1">
										<div id="ctl00_LocalizedValidationSummary1" class="alert alert-danger marginBottom" style="display:none;">

</div>
										<div id="ctl00_ctl05">
	
												<span style="display:none" id="asyncValidationSummary"></span>
											
</div>
									</div>
								</div>
							</div>
						</div>
						<div class="row">
							<div class="e5flex">
								
								
								<div class="e5flex-body">
									
	<div class="card">
		<div class="card-header">
			<h2>
				<span id="ctl00_cpContent_lblPrivacyPolicy">Terms of Use and Privacy Policy</span>
			</h2>
		</div>
		<div class="card-body">
			<span id="ctl00_cpContent_lblPrivacyPolicyContent"><p>
	By browsing this Site, you agree that you have read and understand the following Terms of Use and Privacy Policy in its entirety, including any updates that may be posted on the Site from time to time. Kivuto Solutions Inc. reserves the right to revise the Terms of Use and Privacy Policy, at its sole discretion, by updating this posting.</p>
<p>
	References to Kivuto Solutions Inc. (or Kivuto) in this document also apply to Kivuto’s wholly owned brands, Texidium and OnTheHub.</p>
<ol>
	<li>
		<a href="#1">What information do you gather about me?</a></li>
	<li>
		<a href="#2">How do you collect and use personally identifiable information?</a></li>
	<li>
		<a href="#3">How can I access, update or delete my personal information?</a></li>
	<li>
		<a href="#4">How do you collect and use non-personally identifiable information?</a></li>
	<li>
		<a href="#5">What security is in place to protect my information?</a></li>
	<li>
		<a href="#6">Where will my information be processed?</a></li>
	<li>
		<a href="#7">What is your email policy?</a></li>
	<li>
		<a href="#8">Who can I contact with questions or concerns about this policy?</a></li>
</ol>
<p align="left">
	<strong>Note: </strong>Kivuto’s privacy policy and standards adhere to the European Union’s General Data Protection Regulation (GDPR). The GDPR takes effect on 25 May 2018. The protections offered by this legislation apply to all users of Kivuto’s products and services, both inside and outside the EU.</p>
<h3>
	1. <a name="1"></a>What information do you gather about me?</h3>
<p>
	Both personally and non-personally identifiable information about each visitor may be gathered from this site. The type of information gathered depends on your actions and interaction with the site.</p>
<h4>
	Personally Identifiable Information</h4>
<p>
	Personally identifiable information is only collected when you voluntarily submit this information on an as-needed basis such as during registration and ordering. Any personal information that you may share with us is kept private. Neither your name nor any other identifying data about you is sold or shared with any other third party unless required for the fulfillment or refund of your order or service. More information on this use is provided later in this privacy policy.</p>
<h4>
	Non-Personally Identifiable Information</h4>
<p>
	Non-personally identifying information is gathered through our site technology to create a more personalized and relevant experience during your visit. The information also allows us to improve the functionality of the website to better serve you.</p>
<h3>
	2. <a name="2"></a>How do you collect and use personally identifiable information?</h3>
<h4>
	Collecting Personally Identifiable Information</h4>
<p>
	Personally identifiable information may be collected during registration, ordering and billing, during customer service interactions or when you enter a contest. Personally identifiable information is never shared in ways unrelated to the methods described below without notifying you of the intent beforehand, and also providing you with an opportunity to opt-out or otherwise prohibit such unrelated uses.</p>
<h4>
	Registration</h4>
<p>
	During registration, you may be prompted for your name and email address for authentication and verification purposes. These steps may be necessary to ensure users are properly identified and authenticated as a qualified user. Some offerings and promotions on this site may be restricted to certain types of users (e.g. students, faculty, or staff) or to members of certain organizations. By providing your email address, and subsequently having your account verified, you may benefit from these offerings and promotions.</p>
<h4>
	Ordering and Billing</h4>
<p>
	When you place an order through one of Kivuto’s sites for a product that is not free, you may need to supply your credit card information. When ordering a product that is physically delivered, you will need to provide the necessary shipping information (e.g. postal address). This information may be required to fulfill your order and/or for export-compliance purposes. Your credit card information is not stored on our server; it is simply passed on to the credit card processing system for validation. You may also be prompted for your name and email address to create your online receipt and for us to send you order-related emails.</p>
<h4>
	Customer Service</h4>
<p>
	Personally identifiable information may be collected if you report a problem or submit an inquiry to our customer service team(s). A record of that correspondence may be maintained to provide you with an optimal customer service experience.</p>
<h4>
	Entering a Contest or Promotion</h4>
<p>
	Furthermore, information from you may be collected for entry into contests and similar promotions when you voluntarily choose to participate. All contests have their own terms and conditions which can be viewed on the contest’s page.</p>
<h4>
	Using Personally Identifiable Information</h4>
<p>
	Your personally identifiable information is not sold, traded or rented to others.</p>
<p>
	Kivuto does employ other trusted companies to perform certain functions on our behalf, including order fulfillment and delivery, as well as credit card processing. These business affiliates have access to personal information needed to perform their functions, but are not permitted to use your personal information for any other purpose.</p>
<p>
	Additionally, information related to the order of a product may be shared with the supplier of that particular product, for warranty and support purposes. This may include your name, date of your order and product purchased.</p>
<p>
	If you have questions about how one of our business partners or suppliers use information about you, contact them directly.</p>
<h3>
	3. <a name="3"></a>How can I access, update, or delete my personal information?</h3>
<h4>
	Accessing and Updating Personal Information (Right to Access)</h4>
<p>
	Users can request any of the following from Kivuto at any time.</p>
<ul>
	<li>
		Confirmation of whether Kivuto possesses any of the user’s personal information</li>
	<li>
		The location(s) where Kivuto is processing the user’s personal information</li>
	<li>
		The purpose(s) for which Kivuto is processing the user’s personal information</li>
	<li>
		A copy of all the user’s personal information in Kivuto’s possession, to be provided in a commonly used, machine-readable format.</li>
</ul>
<p>
	To request any of the above information, contact <a href="mailto:privacy@kivuto.com">privacy@kivuto.com</a>.</p>
<p>
	Users can also review and make updates to the information and preferences in their account profile at any time through the Account Information page on their WebStore, provided they are signed in to their account.</p>
<h4>
	Deactivating an Account</h4>
<p>
	You can have your account deactivated or deleted by contacting Support. However, doing so will limit your access to members-only areas of the site. Any purchase history information, however, will remain in protected permanent records.</p>
<h4>
	Deleting Personal Information (Right to Erasure)</h4>
<p>
	Users can request the deletion of all of personal information Kivuto has collected about them at any time. In the absence of any urgent legal or business reason to retain a user’s personal information (e.g. adherence to a law or a contractual obligation), Kivuto will permanently delete or obfuscate all personal information about users who make these requests.</p>
<p>
	When required, Kivuto will also contact any third parties to which Kivuto passed the user’s personal data and ensure that the data is deleted from the systems and records of those third parties as well.</p>
<p>
	To request the erasure of your personal data, contact: <a href="mailto:privacy@kivuto.com">privacy@kivuto.com</a>.</p>
<h3>
	4. <a name="4"></a>How do you collect and use non-personally identifiable information?</h3>
<p>
	Kivuto uses technologies like cookies, pixel tags (“pixels”), and local storage to deliver, secure, and understand products, services, and ads, on and off our sites.</p>
<h4>
	Collecting non-personally identifiable information</h4>
<p>
	Your verification status is collected once you successfully register through any of our verification services. The resulting status is non-personally identifiable information and is stored in case you need to verify your status again in the future.</p>
<p>
	Non-personally identifiable information is collected using technology such as cookies. “Cookies” are small pieces of information that are stored by your browser on your local storage. The information collected by this technology is non-personally identifiable only and allows us to optimize your interactions with the site.</p>
<h4>
	Using non-personally identifiable information</h4>
<p>
	Cookies allow for customer traffic patterns and site usage to be monitored on a general basis to help develop and improve the design, layout and efficiency of the website. Understanding these patterns allows us to provide more relevant content to you and improve customer relationships. Furthermore, the information collected is used to create targeted communications to offer you a more personalized and customizable experience. Cookies also save you time by remembering your personalized settings.</p>
<p>
	Note that all information is collected and analyzed in aggregated form only. Check your browser to ensure cookies are enabled for this site to work properly.</p>
<p>
	Kivuto Solutions Inc. may use third-party advertising technology partners to serve you relevant advertisements on websites outside of our network. The advertising technology partner provides us with tracking technology, such as a cookie, which is added to your browser by us. This allows us to serve you very relevant ads on their partner websites according to your engagements with this site. If you would like to learn more about this process or even opt-out, please contact us.</p>
<h4>
	How to manage cookies</h4>
<p>
	Browser controls are available to allow, block or delete cookies. To manage the cookies this site and others use, visit the following site for instructions: <a href="http://windows.microsoft.com/en-US/windows-vista/Block-or-allow-cookies" target="_blank">http://windows.microsoft.com/en-US/windows-vista/Block-or-allow-cookies</a></p>
<p>
	Please note that by adjusting your cookie settings, any settings or preferences will no longer be in effect. The usage and functionality of the site will be subject to change including the ability to purchase certain products and view content on the site.</p>
<h3>
	5. <a name="5"></a>What security is in place to protect my information?</h3>
<h4>
	Security Measures</h4>
<p>
	Your information is protected both during transmission and in storage. Your account and profile information are password-protected so that you and only you have access to this personal information. During purchase, the secure server software (SSL) encrypts all information you input before it is transmitted. As such, all customer data is protected against unauthorized access on the system’s secure servers.</p>
<h4>
	Breach Notification</h4>
<p>
	In the event of a security breach that creates a potential risk to users’ personal information, Kivuto will ensure that the appropriate authorities are notified of the breach within 72 hours of its discovery.</p>
<p>
	If a security breach is judged likely to pose a high risk to the rights and freedoms of one or more affected users, all reasonable efforts will be made to contact those users and inform them of the breach and the potential impact thereof.</p>
<h3>
	6. <a name="6"></a>Where will my information be processed?</h3>
<p>
	Kivuto Solutions, Inc. is a Canadian corporation with offices at 126 York Street, Suite 200, Ottawa, Ontario, Canada. Personal information gathered by Kivuto is stored on servers located in Canada and will not be transferred to any other country unless it is required as part of the fulfillment of service or requested by the user (see below).</p>
<p>
	Due to agreements with our software publisher partners and Canadian legal obligations, your data may be stored in encrypted backups on our servers for up to seven years.</p>
<p>
	Privacy laws and requirements differ according to each country. Please know, however, that all information collected through Kivuto’s Websites will be protected by the terms of this Privacy Policy and any Privacy Notices that apply to you, regardless of what country the information originates from.</p>
<h4>
	Transferring Personal Information (Data Portability)</h4>
<p>
	Users can request to have all personal information Kivuto has collected about them transferred from Kivuto to another data handler of the user’s choice.</p>
<p>
	Note that Kivuto will only transfer personal information about a user to countries and organizations that are permitted by law and that offer comparable levels of protection on users’ personal information.</p>
<p>
	To request the transfer of your personal data to another data handler, contact: <a href="mailto:privacy@kivuto.com">privacy@kivuto.com</a>.</p>
<h3>
	7. <a name="7"></a>What is your email policy?</h3>
<p>
	Kivuto Solutions Inc. complies fully with the federal CAN-SPAM Act of 2003 and Canada’s Anti-Spam Legislation (CASL). Kivuto will not share, sell, rent, swap or authorize any third party to use your email address for commercial purposes without your permission. If you feel you have received an email from us in error, contact <a href="mailto:privacy@kivuto.com">privacy@kivuto.com</a>.</p>
<p>
	You may receive one or more of the following emails from Kivuto Solutions.</p>
<h4>
	Account- and Service-Related Email</h4>
<p>
	Kivuto Solutions Inc. reserves the right to send you emails relating to your account status. This includes order confirmations, renewal/expiration notices, notices of credit-card problems, other transactional emails and notifications about major changes to the site services and/or to our Privacy Policy. If you have registered for online discussions or other services, you may receive an email specific to your participation in those activities.</p>
<h4>
	Email Newsletters</h4>
<p>
	Kivuto Solutions Inc. offer several email newsletters. You will only receive these if you previously chose to opt-in to these types of communications. If you no longer wish to receive a specific newsletter, follow the “unsubscribe” instructions located near the bottom of each newsletter.</p>
<h4>
	Promotional Email</h4>
<p>
	Kivuto Solutions Inc. may periodically email you messages about products and services that Kivuto thinks may be of interest to you (if you have previously opted in to receive these types of communications). You can choose not to receive messages in the future by following the “unsubscribe” instructions located near the bottom of each email.</p>
<h4>
	Survey Email</h4>
<p>
	Kivuto may send you emails inviting you to participate in user surveys, asking for feedback on our services and existing or prospective products and services, as well as information to better understand our users. User surveys greatly help us to improve our services, and any information Kivuto obtains in such surveys will be used internally. The information may be shared with affiliated third parties in aggregate form only.</p>
<h4>
	HTML Email</h4>
<p>
	If you sign up to receive email from us you will receive emails in both plain text and HTML (with images) format. If you select to view our emails in the HTML format, Kivuto may place a one-pixel .gif to determine whether or not readers viewed the email. This process does not leave any information on your computer, nor does it collect information from your computer. Kivuto may share this data with other third parties in aggregate form only to improve the quality of the emails and offers Kivuto distributes.</p>
<h4>
	Emails From You</h4>
<p>
	If you send us emails, be aware that information disclosed in emails may not be secure or encrypted and thus may be available to others. It is recommended that you exercise caution when deciding to disclose any personal or confidential information in emails. Kivuto will use your email address to respond directly to your questions or comments.</p>
<h3>
	8. <a name="8"></a>Who can I contact with questions or concerns about this policy?</h3>
<p>
	If you have questions, comments, concerns, or complaints about this privacy or Kivuto’s handling of your personal information, you get in touch with us in any of the following ways.</p>
<h4>
	By Email</h4>
<p>
	Please direct all privacy-related inquiries to <a href="mailto:privacy@kivuto.com">privacy@kivuto.com</a>.</p>
<h4>
	By Phone</h4>
<table border="0" cellpadding="0" cellspacing="0">
	<tbody>
		<tr>
			<td style="width:180px;">
				<p>
					USA/Canada (toll free)</p>
			</td>
			<td style="width:425px;">
				<p>
					1-866-435-4722</p>
			</td>
		</tr>
		<tr>
			<td style="width:180px;">
				<p>
					Australia (toll free)</p>
			</td>
			<td style="width:425px;">
				<p>
					1-800-426-231</p>
			</td>
		</tr>
		<tr>
			<td style="width:180px;">
				<p>
					France (toll free)</p>
			</td>
			<td style="width:425px;">
				<p>
					0800-916021</p>
			</td>
		</tr>
		<tr>
			<td style="width:180px;">
				<p>
					Germany (toll free)</p>
			</td>
			<td style="width:425px;">
				<p>
					0800-182-8612</p>
			</td>
		</tr>
		<tr>
			<td style="width:180px;">
				<p>
					Hong Kong (toll free)</p>
			</td>
			<td style="width:425px;">
				<p>
					800-968-781</p>
			</td>
		</tr>
		<tr>
			<td style="width:180px;">
				<p>
					Malaysia (toll free)</p>
			</td>
			<td style="width:425px;">
				<p>
					1-800-815-302</p>
			</td>
		</tr>
		<tr>
			<td style="width:180px;">
				<p>
					Spain (toll free)</p>
			</td>
			<td style="width:425px;">
				<p>
					900-809754</p>
			</td>
		</tr>
		<tr>
			<td style="width:180px;">
				<p>
					United Kingdom (toll free)</p>
			</td>
			<td style="width:425px;">
				<p>
					0-800-098-8436</p>
			</td>
		</tr>
		<tr>
			<td style="width:180px;">
				<p>
					Other countries</p>
			</td>
			<td style="width:425px;">
				<p>
					+44-845-8697566</p>
			</td>
		</tr>
	</tbody>
</table>
<h4>
	<strong>By Mail</strong></h4>
<table border="0" cellpadding="0" cellspacing="0">
	<tbody>
		<tr>
			<td style="width:123px;height:82px;">
				<p>
					<strong>North America</strong><br />
					(Head Office)</p>
			</td>
			<td style="width:482px;height:82px;">
				<p>
					Kivuto Solutions Inc.<br />
					126 York St., Suite 200</p>
				<p>
					Ottawa, Ontario, Canada</p>
				<p>
					K1N 5T5</p>
			</td>
		</tr>
		<tr>
			<td style="width:123px;height:82px;">
				<p>
					<strong>EMEA</strong></p>
			</td>
			<td style="width:482px;height:82px;">
				<p>
					Kivuto Solutions Inc.</p>
				<p>
					2<sup>nd</sup> Floor, 16 South Main Street<br />
					Naas, Co. Kildare, Ireland</p>
			</td>
		</tr>
	</tbody>
</table>
<p>
	 </p></span>
		</div>
	</div>

								</div>
							</div>
						</div>
						
					</div>
				</div>
				<div id="footer">
					
  <div class="container-fluid footer-content">
	<div class="container">
        <div class="row">
            
                <div class="col-md-4 col-sm-6 crunch-center-sm">
				    <div class="row">
					    <div class="col-md-12">
						    <h2>
                                Connect With Us
						    </h2>
					    </div>
				    </div>
				    <div class="row">
					    <div class="col-md-12 social-link">
                            <a id="ctl00_ucFooter_hlTwitter" href="http://www.twitter.com/onthehub" target="_blank">
                                <span class="sr-only">
                                    Twitter
                                </span>
								<span class="fa-stack tw">
									<span class="fa fa-circle fa-stack-2x"></span>
									<span class="fa fa-twitter fa-stack-1x fa-inverse"></span>
								</span>
                            </a><a id="ctl00_ucFooter_hlFacebook" href="http://www.facebook.com/pages/On-The-Hub/25131788360?sid=7fd7b2be4847d87eb78d0e758b86dc7c" target="_blank">
								<span class="sr-only">
                                    Facebook
								</span>
                                <span class="fa-stack fb">
									<span class="fa fa-circle fa-stack-2x"></span>
                                    <span class="fa fa-facebook fa-stack-1x fa-inverse"></span>
								</span>
                            </a><a id="ctl00_ucFooter_hlGooglePlus" href="https://plus.google.com/115290003144094460033/about" target="_blank">
								<span class="sr-only">
								    Google+
                                </span>
                                <span class="fa-stack gp">
									<span class="fa fa-circle fa-stack-2x"></span>
									<span class="fa fa-google-plus fa-stack-1x fa-inverse"></span>
								</span>
                            </a><a id="ctl00_ucFooter_hlBlog" href="http://blog.onthehub.com/" target="_blank">
								<span class="sr-only">
								    Blog
                                </span>
                                <span class="fa-stack bl">
									<span class="fa fa-circle fa-stack-2x"></span>
									<span class="fa fa fa-rss fa-stack-1x fa-inverse"></span>
								</span>
                            </a><a id="ctl00_ucFooter_hlPinterest" href="https://www.pinterest.com/onthehub/" target="_blank">
                                <span class="sr-only">
                                    Pinterest
                                </span>
                                <span class="fa-stack pi">
									<span class="fa fa-circle fa-stack-2x"></span>
									<span class="fa fa fa-pinterest-p fa-stack-1x fa-inverse"></span>
								</span>
                            </a><a id="ctl00_ucFooter_hlInstagram" href="https://instagram.com/onthehub/" target="_blank">
                                <span class="sr-only">
                                    Instagram
                                </span>
                                <span class="fa-stack ig">
									<span class="fa fa-circle fa-stack-2x"></span>
									<span class="fa fa fa-instagram fa-stack-1x fa-inverse"></span>
								</span>
                            </a>
					    </div>
				    </div>
			    </div>
            
            <div class="col-md-4 col-sm-6 crunch-center-sm crunch-spacer">
			    <div class="row">
				    <div id="ctl00_ucFooter_pnlOTHHeader" class="col-md-12">
	
					    <h2>OnTheHub</h2>
				    
</div>
					
			    </div>
			    <div class="row">
				    <div class="col-sm-6">
					    <div class="row">
						    <div class="col-md-12">
							    <div class="footer-label kivuto">
                                    <a id="ctl00_ucFooter_lhlContactUs" href="ContactUs.aspx" target="_self">Contact Us</a>
							    </div>
						    </div>
						    <div class="col-md-12">
							    <div class="footer-label kivuto">
                                    <a id="ctl00_ucFooter_lhlSafeShopping" href="SafeShopping.aspx" target="_self">Safe Shopping</a>
							    </div>
						    </div>
					    </div>
				    </div>
				    <div class="col-sm-6">
					    <div class="row">
						    <div class="col-md-12">
							    <div class="footer-label kivuto">
                                    <a id="ctl00_ucFooter_lhlPrivacy" href="PrivacyPolicy.aspx" target="_self">Privacy Policy</a>
							    </div>
						    </div>
                            
					    </div>
                    </div>
			    </div>
		    </div>
            <div id="ctl00_ucFooter_kvtImageHolder" class="col-md-4">
				<div class="row hidden-sm hidden-xs">
					<div style="height:60px"></div>
				</div>
				<div class="row">
					<div class="col-xs-6">
						<a id="ctl00_ucFooter_hlEAcademy" href="http://www.kivuto.com" target="_blank"><img id="ctl00_ucFooter_Image2" class="img-responsive center-block" src="https://elmsprodcdnendpoint.azureedge.net/images/poweredbykivuto.png?4.7.7125.28" alt="Powered by Kivuto Solutions Inc." style="border-width:0px;" /></a>
					</div>					
					<div class="col-xs-6">
						<img id="ctl00_ucFooter_imgSslSeal" class="img-responsive center-block" src="https://elmsprodcdnendpoint.azureedge.net/images/rapidssl_seal-90x50.gif?4.7.7125.28" alt="Secured by RapidSSL" style="border-width:0px;" />
					</div>              
				</div>
			</div>
        </div>
    </div>
</div>
<div class="container-fluid e5-version">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <div class="version-text">
                    <small>                        
						<span id="ctl00_ucFooter_lblCopywrite">
							© Kivuto Solutions Inc. All Rights Reserved. - 
						</span>
						
                        <bdi><span id="ctl00_ucFooter_lblVersion">v4.7.7125.28 (Fews06)</span></bdi>
                    </small>
                </div>
            </div>
        </div>
    </div>
</div>
				</div>
			</div>
			
			<div id="notice-only-opt-ins">
				
			</div>
			<div id="ctl00_upCheckout" style="display:none">
	
					<a id="llbGeneralExpressCheckout" href="javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$llbGeneralExpressCheckout&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, true))">Express Checkout</a>
					<a id="llbGeneralCheckout" href="javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$llbGeneralCheckout&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, true))">Check Out</a>
				
</div>
			<div id="fb-root"></div>
			
		
<script type="text/javascript">
//<![CDATA[
var Page_ValidationSummaries =  new Array(document.getElementById("ctl00_LocalizedValidationSummary1"));
//]]>
</script>


<script type="text/javascript">
//<![CDATA[

(function(id) {
    var e = document.getElementById(id);
    if (e) {
        e.dispose = function() {
            Array.remove(Page_ValidationSummaries, document.getElementById(id));
        }
        e = null;
    }
})('ctl00_LocalizedValidationSummary1');
//]]>
</script>
</form>
		

<script type="text/javascript">

    /* Google Analytics */
    var _gaq = _gaq || [];
    var _ga = _ga || {};
    (function (data) {
        if (DoTracking) {
            DoTracking(data); // in Analytics.js
        }
    })({"config":{"classicTrackerCode":"UA-2768482-4","classicUmbrellaTrackerCode":"UA-2768482-14","umbrellaTrackingDomain":"onthehub.com","universalTrackerCode":"UA-2768482-18"},"customVariables":{"brand":"onthehub e-store","customerLoyalty":"Prospect (0 purchases)","groups":null,"program":null,"webstore":"OnTheHub"},"eCommerceData":null});

    

</script>

		

<!-- Facebook Conversion Code for e5 Visits -->
<script type="text/javascript">
    var fb_param = {};
    fb_param.pixel_id = '6017038665868';
    fb_param.value = '0.00';
    fb_param.currency = 'USD';
    (function () {
        var fpw = document.createElement('script');
        fpw.async = true;
        fpw.src = '//connect.facebook.net/en_US/fp.js';
        var ref = document.getElementsByTagName('script')[0];
        ref.parentNode.insertBefore(fpw, ref);
    })();
</script>
<noscript>
    <img height="1" width="1" alt="" style="display:none" src="https://www.facebook.com/offsite_event.php?id=6017038665868&amp;value=0&amp;currency=USD" />
</noscript>
	</body>
</html>