
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" prefix="og:http://ogp.me/ns#">
<head><link rel="stylesheet" type="text/css" href="/DXR.axd?r=1_29,1_33,1_3,0_282,0_284-ziGyd" />

<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-N5V2HKP');</script>

<meta charset="utf-8" /><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" /><meta http-equiv="x-ua-compatible" content="ie=edge" />
<script src="/new_brand_design/js/tether.min.js"></script>
<link rel="stylesheet" href="new_brand_design/css/bootstrap.min.css" /><link rel="stylesheet" href="new_brand_design/css/owl.carousel.css" /><link rel="alternate" hreflang="el" href="https://www.ergodotisi.com/privacy.aspx" /><link rel="alternate" hreflang="en" href="https://www.ergodotisi.com/en/privacy.aspx" />

<title>Πολιτική Απορρήτου</title><meta name="description" content="Read the following for the privacy rules governing Ergodotisi.com. All personal information is kept at maximum level of security" />
<meta name="keywords" content="job, cyprus, κύπρος, δουλειά, εργασία, θέση, θέσεις, καριέρα, kariera, κενή, jobs, CV, βιογραφικό, cover letter, interview, συνέντευξη" />


<link rel="stylesheet" href="/new_brand_design/css/stylesheet.css" /><link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet" /><link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i" rel="stylesheet" /><link rel="stylesheet" href="new_brand_design/css/font-awesome.min.css" />


<script async='async' src='https://www.googletagservices.com/tag/js/gpt.js'></script>
<script>
        !function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
        n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
        n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
        t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
        document,'script','https://connect.facebook.net/en_US/fbevents.js');
        fbq('init', '1397586537210171'); // Insert your pixel ID here.
        fbq('track', 'PageView');

        var googletag = googletag || {};
        googletag.cmd = googletag.cmd || [];

        googletag.cmd.push(function () {
            var mapping2 = googletag.sizeMapping().addSize([1300, 0], [728, 90]).addSize([768, 0], [728, 90]).addSize([360, 0], [320, 50]).addSize([320, 0], [320, 50]).build();
            googletag.defineSlot('/38893584/ergodotisi_common_leaderboard', [[320, 50], [728, 90]], 'div-gpt-ad-1504700248152-2').defineSizeMapping(mapping2).addService(googletag.pubads());
            googletag.pubads().enableSingleRequest();
            googletag.enableServices();
        });

        </script>
<noscript><img height="1" width="1" style="display:none"
        src="https://www.facebook.com/tr?id=1397586537210171&ev=PageView&noscript=1"
        /></noscript>



<meta property="og:site_name" content="ergodotisi.com" /><meta property="og:type" content="website" />
<style type="text/css">
        .ImgInstagramClass {
            border-radius:9px
        }

        @media (max-width: 480px)
        {
           .topbannerheight{height:50px;}

        }
         @media (min-width: 481px)
        {
           .topbannerheight{height:70px;}

        }

        .pricing-li{
            position:relative;
        }
         .pricing-hover{
             cursor:pointer;
         }

        .select-language-inner {
            left: auto;
            right: 0;
        }

        .select-option-inner, .dropdown-menu {
            position: absolute;
            left: 0;
            right: 0;
            visibility: hidden;
            opacity: 0;
            background: #3e1a61;
            border-radius: 4px;
            -ms-transform: scale(0.94);
            transform: scale(0.94);
            box-shadow: 0 2px 14px 0 rgba(0, 0, 0, 0.08);
            transition: all 200ms ease-out 10ms;
            padding-left:inherit;
        }

        .select-language-inner li {
            padding-top: 5px;
            padding-bottom: 5px;
        }

        .select-option-inner li, .dropdown-menu li {
            padding: 5px 5px 8px 0px;
            line-height: 6px;
            border-bottom: 1px solid #eee;
            transition: all 160ms linear 10ms;
        }

        .select-option-inner.active, .dropdown-menu.active {
            visibility: visible;
            opacity: 1;
            -ms-transform: scale(1);
            transform: scale(1);
        }

    </style>
<script type="application/ld+json">
         {
              "@context": "http://schema.org",
              "@type": "WebSite",
              "url": "https://www.ergodotisi.com/",
              "potentialAction": {
                "@type": "SearchAction",
                "target": "https://www.ergodotisi.com/SearchResults.aspx?q={search_term_string}",
                "query-input": "required name=search_term_string"
                }
        }
    </script>

<script>
    (function(h,o,t,j,a,r){
        h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
        h._hjSettings={hjid:763097,hjsv:6};
        a=o.getElementsByTagName('head')[0];
        r=o.createElement('script');r.async=1;
        r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
        a.appendChild(r);
    })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
</script>

<link rel="manifest" href="/manifest.json" /><script src="https://cdn.onesignal.com/sdks/OneSignalSDK.js" async=""></script><script>var OneSignal = window.OneSignal || [];OneSignal.push(function() {OneSignal.init({appId: "2fe73106-e46d-4361-ba7a-013814eac156",});});</script><link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.css" />
<script src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.js"></script>
<script>
window.addEventListener("load", function(){
window.cookieconsent.initialise({
  "palette": {
    "popup": {
      "background": "#5d2d8d",
      "text": "#ffffff"
    },
    "button": {
      "background": "transparent",
      "text": "#ffffff",
      "border": "#ffffff"
    }
  },
  "showLink": false,
  "content": {
    "message": "This website uses cookies to ensure you get the best experience on our website.",
    "dismiss": "Agree"
  }
})});
</script>
<script>
    function show() {
        document.getElementById('pricingmenu').style.visibility = 'visible';
    }

    function hide() {
        document.getElementById('pricingmenu').style.visibility = 'hidden';
    }

</script>
</head>
<body>

<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-N5V2HKP"
    height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>

<form method="post" action="/privacy.aspx" onsubmit="javascript:return WebForm_OnSubmit();" id="aspnetForm">
<div class="aspNetHidden">
<input type="hidden" name="__EVENTTARGET" id="__EVENTTARGET" value="" />
<input type="hidden" name="__EVENTARGUMENT" id="__EVENTARGUMENT" value="" />
<input type="hidden" name="__VIEWSTATE" id="__VIEWSTATE" value="/wEPDwUKLTcxMDk4MDk5Nw9kFgJmD2QWBAIBD2QWBAIKDxYCHgRUZXh0Ba0BPGxpbmsgcmVsPSJhbHRlcm5hdGUiIGhyZWZsYW5nPSJlbCIgaHJlZj0iaHR0cHM6Ly93d3cuZXJnb2RvdGlzaS5jb20vcHJpdmFjeS5hc3B4IiAvPjxsaW5rIHJlbD0iYWx0ZXJuYXRlIiBocmVmbGFuZz0iZW4iIGhyZWY9Imh0dHBzOi8vd3d3LmVyZ29kb3Rpc2kuY29tL2VuL3ByaXZhY3kuYXNweCIgLz5kAiEPFgIfAAWTAjxsaW5rIHJlbD0ibWFuaWZlc3QiIGhyZWY9Ii9tYW5pZmVzdC5qc29uIiAvPjxzY3JpcHQgc3JjPSJodHRwczovL2Nkbi5vbmVzaWduYWwuY29tL3Nka3MvT25lU2lnbmFsU0RLLmpzIiBhc3luYz0iIj48L3NjcmlwdD48c2NyaXB0PnZhciBPbmVTaWduYWwgPSB3aW5kb3cuT25lU2lnbmFsIHx8IFtdO09uZVNpZ25hbC5wdXNoKGZ1bmN0aW9uKCkge09uZVNpZ25hbC5pbml0KHthcHBJZDogIjJmZTczMTA2LWU0NmQtNDM2MS1iYTdhLTAxMzgxNGVhYzE1NiIsfSk7fSk7PC9zY3JpcHQ+ZAIDDxYCHgZhY3Rpb24FDS9wcml2YWN5LmFzcHgWRAIBDw8WAh4LTmF2aWdhdGVVcmwFG2h0dHBzOi8vd3d3LmVyZ29kb3Rpc2kuY29tL2RkAgMPZBYCZg9kFgICAw8WAh4EaHJlZgU4aHR0cHM6Ly93d3cuZXJnb2RvdGlzaS5jb20vUmVnaXN0ZXJVc2VyLmFzcHg/cHJvZHVjdGlkPTBkAgUPPCsACAIADxYEHg9EYXRhU291cmNlQm91bmRnHg5fIVVzZVZpZXdTdGF0ZWdkBjwrABIBABYCHg5Qb3B1cEVsZW1lbnRJRAUZY3RsMDBfTG9naW5WaWV3MV9UYWJMb2dpbhYCZg9kFgJmD2QWAmYPZBYCZg9kFgJmD2QWAmYPZBYCAgEPZBYCAgEPPCsACgEADxYCHhJEZXN0aW5hdGlvblBhZ2VVcmwFJ2h0dHBzOi8vd3d3LmVyZ29kb3Rpc2kuY29tL3ByaXZhY3kuYXNweGQWAmYPZBYCAgEPZBYEAg8PPCsABAEADxYCHwRnZGQCEw8PFgIfAgUuaHR0cHM6Ly93d3cuZXJnb2RvdGlzaS5jb20vZm9yZ290cGFzc3dvcmQuYXNweGRkAgcPPCsACQIADxYEHwRnHwVnZAYPZBAWBGYCAQICAgMWBDwrAAwBABYCHwIFMWh0dHBzOi8vd3d3LmVyZ29kb3Rpc2kuY29tL015QWNjb3VudC9DVkVudHJ5LmFzcHg8KwAMAQAWAh8CBThodHRwczovL3d3dy5lcmdvZG90aXNpLmNvbS9NeUFjY291bnQvQ2hhbmdlUGFzc3dvcmQuYXNweDwrAAwBABYCHwIFNmh0dHBzOi8vd3d3LmVyZ29kb3Rpc2kuY29tL015QWNjb3VudC9BcHBsaWNhdGlvbnMuYXNweDwrAAwBABYCHwIFMmh0dHBzOi8vd3d3LmVyZ29kb3Rpc2kuY29tL015QWNjb3VudC9wdXJjaGFzZS5hc3B4ZGQCDQ8PFgIfAgUbaHR0cHM6Ly93d3cuZXJnb2RvdGlzaS5jb20vZGQCDw8PFgIfAgUwaHR0cHM6Ly93d3cuZXJnb2RvdGlzaS5jb20vU2VhcmNoUmVzdWx0cy5hc3B4P3E9ZGQCEQ8PFgIfAgUpaHR0cHM6Ly93d3cuZXJnb2RvdGlzaS5jb20vQ29tcGFuaWVzLmFzcHhkZAIVDw8WAh8CBSJodHRwczovL3d3dy5lcmdvZG90aXNpLmNvbS9wcmljaW5nZGQCFw8PFgIfAgUhaHR0cHM6Ly93d3cuZXJnb2RvdGlzaS5nci9wcmljaW5nZGQCGw8PFgIfAgUpaHR0cHM6Ly93d3cuZXJnb2RvdGlzaS5jb20vY29udGFjdHVzLmFzcHhkZAIdDw8WAh8CBSlodHRwczovL3d3dy5lcmdvZG90aXNpLmNvbS9FbXBsb3llcnMuYXNweGRkAh8PDxYEHwAFTjxzcGFuIGNsYXNzPSdmYSBmYS1sb2NrIGZhLTJ4Jz48L3NwYW4+zpXOk86TzqHOkc6mzpcgzpPOmc6RIM6VzqHOk86fzpTOn86kzpXOox8CBSlodHRwczovL3d3dy5lcmdvZG90aXNpLmNvbS9FbXBsb3llcnMuYXNweGRkAiEPFgIfAAXtBDxsaSBjbGFzcz0ibmF2LWl0ZW0tdGFiIiBzdHlsZT0iZmxvYXQ6cmlnaHQiPjxhIGNsYXNzPSJuYXYtbGluayIgc3R5bGU9InBhZGRpbmctcmlnaHQ6MXB4IiB0aXRsZT0izpjOrc+DzrXOuc+CIM61z4HOs86xz4POr86xz4Igz4PPhM63zr0gzprPjc+Az4HOvyIgaHJlZj0iaHR0cHM6Ly93d3cuZXJnb2RvdGlzaS5jb20vZW4vcHJpdmFjeS5hc3B4Ij48aW1nIHNyYz0iL25ld19icmFuZF9kZXNpZ24vaW1nL2VuLVVTLmpwZyIgaGVpZ2h0PSIxMnB4IiBydW5hdD0ic2VydmVyIiBhbHQ9IkpvYnMgaW4gQ3lwcnVzIi8+PC9hPjwvbGk+PGxpIGNsYXNzPSJuYXYtaXRlbS10YWIiIHN0eWxlPSJmbG9hdDpyaWdodCI+PGEgY2xhc3M9Im5hdi1saW5rIiBzdHlsZT0icGFkZGluZy1yaWdodDoxcHgiIGRpc2FibGVkPSJkaXNhYmxlZCIgdGl0bGU9Is6Yzq3Pg861zrnPgiDOtc+BzrPOsc+Dzq/Osc+CIM+Dz4TOt869IM6az43PgM+Bzr8iIGhyZWY9Imh0dHBzOi8vd3d3LmVyZ29kb3Rpc2kuY29tL3ByaXZhY3kuYXNweCI+PGltZyBzcmM9Ii9uZXdfYnJhbmRfZGVzaWduL2ltZy9lbC1HUi5qcGciIGhlaWdodD0iMjBweCIgcnVuYXQ9InNlcnZlciIgYWx0PSJKb2JzIGluIEN5cHJ1cyIvPjwvYT48L2xpPmQCIw9kFgICAw8WAh8ABQogNzAwMCA3MTIwZAIlD2QWAgIDDxYCHwAFEyAoKzM1NykgMjUgNTUgODcgNDRkAicPZBYCAgEPZBYCZg8WAh4LXyFJdGVtQ291bnQCARYCZg9kFgQCAQ8WAh8ABSPOoM6/zrvOuc+EzrnOus6uIM6Rz4DOv8+Bz4HOrs+Ezr/PhWQCAw8WAh8ABciRATxwPjxiciAvPjwvcD48cD48c3BhbiBzdHlsZT0iZm9udC1zaXplOiAxMnB0OyI+PHNwYW4gc3R5bGU9InRleHQtZGVjb3JhdGlvbjogdW5kZXJsaW5lOyI+PHN0cm9uZz4xLiBJTlRST0RVQ1RJT048L3N0cm9uZz48L3NwYW4+PC9zcGFuPjwvcD48cD5UaGlzIFByaXZhY3kgUG9saWN5IGFpbXMgdG8gZ2l2ZSB5b3UgaW5mb3JtYXRpb24gb24gaG93IE1lbGlvciBDYXBpdGFsIExURCBjb2xsZWN0cywgdXNlcywgZGlzY2xvc2VzIGFuZCBwcm9jZXNzZXMgeW91ciBwZXJzb25hbCBkYXRhIHRocm91Z2ggeW91ciB1c2Ugb2YgdGhlIHdlYnNpdGUgZXJnb2RvdGlzaS5jb20gKGhlcmVpbmFmdGVyIHJlZmVycmVkIHRvIGFzIOKAnHRoZSBXZWJzaXRl4oCdIG9yIOKAnEVyZ29kb3Rpc2nigJ0pIGFuZCB0aGUgbWVhbnMgYnkgd2hpY2ggdGhpcyBpcyBkb25lLiBUaGUgUHJpdmFjeSBQb2xpY3kgYWN0cyBhcyBhIG1lYW5zIG9mIG5vdGlmeWluZyB0aGUgd2Vic2l0ZSB2aXNpdG9ycyBvZiB0aGVpciByaWdodHMgaW4gYWNjb3JkYW5jZSB3aXRoIGxvY2FsIGxhdyBhbmQgdGhlIEVVIEdlbmVyYWwgRGF0YSBQcm90ZWN0aW9uIFJlZ3VsYXRpb24gKEVVKSAyMDE2LzY3OS4mbmJzcDs8L3A+PHA+VGhpcyBXZWJzaXRlIGlzIG5vdCBpbnRlbmRlZCBmb3IgY2hpbGRyZW4gYW5kIHdlIGRvIG5vdCBrbm93aW5nbHkgY29sbGVjdCBkYXRhIHJlbGF0aW5nIHRvIGNoaWxkcmVuLjwvcD48cD5NZWxpb3IgQ2FwaXRhbCBMVEQgaXMgY29tbWl0dGVkIHRvIHByb3RlY3RpbmcgeW91ciBwcml2YWN5IGFuZCBkZXZlbG9waW5nIHRlY2hub2xvZ3kgdGhhdCBnaXZlcyB5b3UgdGhlIG1vc3QgcG93ZXJmdWwgYW5kIHNhZmUgb25saW5lIGV4cGVyaWVuY2UuPC9wPjxwPiZuYnNwO0J5IGFjY2Vzc2luZywgYnJvd3NpbmcgYW5kL29yIHVzaW5nIHRoaXMgV2Vic2l0ZSwgeW91IGNvbnNlbnQgdG8gdGhlIGRhdGEgcHJhY3RpY2VzIGRlc2NyaWJlZCBpbiB0aGlzIFByaXZhY3kgUG9saWN5IGFuZCBhY2tub3dsZWRnZSB0aGF0IHlvdSBoYXZlIHJlYWQsIHVuZGVyc3Rvb2QsIGFuZCBhZ3JlZSwgdG8gYmUgYm91bmQgYnkgdGhlc2UgdGVybXMgY29uZGl0aW9ucywgYW5kIG5vdGljZXMgY29udGFpbmVkIGhlcmVpbiBhbmQgdG8gY29tcGx5IHdpdGggYWxsIGFwcGxpY2FibGUgbGF3cyBhbmQgcmVndWxhdGlvbnMuPC9wPjxwPkZvciB0aGUgcHVycG9zZXMgb2YgdGhpcyBQcml2YWN5IFBvbGljeSDigJxQZXJzb25hbCBEYXRh4oCdIHJlZmVycyB0byBhbGwmbmJzcDsgZGF0YSB3aGljaCByZWxhdGVzIHRvIGEgbGl2aW5nIGluZGl2aWR1YWwgd2hvIGNhbiBiZSBpZGVudGlmaWVkIGZyb20gc3VjaCBkYXRhIHN1Y2ggYXMgZm9yIGluc3RhbmNlLCBuYW1lLCBhZGRyZXNzIGFuZC9vciBpZGVudGlmaWNhdGlvbiBudW1iZXIuIEl0IGRvZXMgbm90IGluY2x1ZGUgZGF0YSB3aGVyZSB0aGUgaWRlbnRpdHkgaGFzIGJlZW4gcmVtb3ZlZCAoYW5vbnltb3VzIGRhdGEpLjwvcD48cD48YnIgLz48L3A+PHA+PHNwYW4gc3R5bGU9ImZvbnQtc2l6ZTogMTJwdDsiPjxzcGFuIHN0eWxlPSJ0ZXh0LWRlY29yYXRpb246IHVuZGVybGluZTsiPjxzdHJvbmc+Mi4gV0hPIFdFIEFSRTwvc3Ryb25nPjwvc3Bhbj48L3NwYW4+PC9wPjxwPkVyZ29kb3Rpc2kgaXMgb3duZWQgYW5kIG9wZXJhdGVkIGJ5IE1lbGlvciBDYXBpdGFsIExURCwgYSBsaW1pdGVkIGxpYWJpbGl0eSBjb21wYW55IHJlZ2lzdGVyZWQgaW4gdGhlIFJlcHVibGljIG9mIEN5cHJ1cyB3aXRoIHJlZ2lzdHJhdGlvbiBudW1iZXIgzpfOlSAzMDU5NjUgYW5kIHJlZ2lzdGVyZWQgYWRkcmVzcyBhdCA4IE1pY2hhbGFraSBLYXJhb2xpIFN0cmVldCwgQW5lbW9sbXlsb3MgQnVpbGRpbmcsIDNyZCBmbG9vciwgMTA5NSBOaWNvc2lhLCBDeXBydXMuJm5ic3A7PC9wPjxwPkVyZ29kb3Rpc2kgaXMgYSBqb2Igc2VhcmNoIHJlbGF0ZWQgcGxhdGZvcm0gdXNlZCBmb3IgZmluZGluZyBhIGpvYiBpbiB0aGUgUmVwdWJsaWMgb2YgQ3lwcnVzLiBJdCBhaW1zIHRvIGNvbnRyaWJ1dGUgaW4gdGhlIHByb2Zlc3Npb25hbCBzdWNjZXNzIG9mIGl0cyB1c2VycyBhbmQgY29tcGFuaWVzIGFuZCBhc3Npc3QgY29tcGFuaWVzIGluIGZpbmRpbmcgc3VpdGFibGUgcHJvZmVzc2lvbmFscyBhbmQgcHJvZmVzc2lvbmFscyBpbiBmaW5kaW5nIHN1aXRhYmxlIGNvbXBhbmllcy48L3A+PHA+SWYgeW91IGhhdmUgYW55IHF1ZXN0aW9ucyBhYm91dCB0aGlzIFByaXZhY3kgUG9saWN5ICwgaW5jbHVkaW5nIGFueSByZXF1ZXN0cyB0byBleGVyY2lzZSB5b3VyIGxlZ2FsIHJpZ2h0cywgcGxlYXNlIGNvbnRhY3QgdXMgYXQgdGhlIGRldGFpbHMgc2V0IG91dCBiZWxvdy48L3A+PHA+PHNwYW4gc3R5bGU9InRleHQtZGVjb3JhdGlvbjogdW5kZXJsaW5lOyI+Q29udGFjdCBEZXRhaWxzOiBFcmdvZG90aXNpLmNvbSBUZWFtPC9zcGFuPjwvcD48cD48c3BhbiBzdHlsZT0idGV4dC1kZWNvcmF0aW9uOiB1bmRlcmxpbmU7Ij5BZGRyZXNzOiBTcHlyb3UgS3lwcmlhbm91IDM3LCDOpM6aIDQxNTQsIM6bzrXOvM61z4PPjM+CLCBMaW1hc3NvbCA0MTU0PC9zcGFuPjwvcD48cD5FbWFpbCBhZGRyZXNzOiBpbmZvQGVyZ29kb3Rpc2kuY29tPC9wPjxwPlRlbGVwaG9uZSBudW1iZXI6ICgrMzU3KSAyNSA1NSA4NyA0NDwvcD48cD4mbmJzcDtZb3UgaGF2ZSB0aGUgcmlnaHQgdG8gbWFrZSBhIGNvbXBsYWludCBhdCBhbnkgdGltZSB0byB0aGUgT2ZmaWNlIG9mIHRoZSBDb21taXNzaW9uZXIgZm9yIERhdGEgUHJvdGVjdGlvbiwgdGhlIHN1cGVydmlzb3J5IGF1dGhvcml0eSBmb3IgZGF0YSBwcm90ZWN0aW9uIGlzc3VlcyBpbiB0aGUgUmVwdWJsaWMgb2YgQ3lwcnVzJm5ic3A7ICg8YSBocmVmPSJodHRwOi8vd3d3LmRhdGFwcm90ZWN0aW9uLmdvdi5jeS9kYXRhcHJvdGVjdGlvbi9kYXRhcHJvdGVjdGlvbi5uc2YvaG9tZV9lbi9ob21lX2VuP29wZW5kb2N1bWVudCIgdGFyZ2V0PSJfYmxhbmsiPkNsaWNrIGhlcmUgdG8gc2VlIGRldGFpbHM8L2E+KS4gV2Ugd291bGQsIGhvd2V2ZXIsIGFwcHJlY2lhdGUgdGhlIGNoYW5jZSB0byBkZWFsIHdpdGggeW91ciBjb25jZXJucyBiZWZvcmUgeW91IGFwcHJvYWNoIHRoZSBDb21taXNzaW9uZXIgZm9yIERhdGEgUHJvdGVjdGlvbiB0aGVyZWZvcmUgcGxlYXNlIGNvbnRhY3QgdXMgaW4gdGhlIGZpcnN0IGluc3RhbmNlLjwvcD48cD48YnIgLz48L3A+PHA+PHN0cm9uZz48c3BhbiBzdHlsZT0idGV4dC1kZWNvcmF0aW9uOiB1bmRlcmxpbmU7Ij48c3BhbiBzdHlsZT0iZm9udC1zaXplOiAxMnB0OyI+My4gVFlQRSBBTkQgTUVUSE9EIE9GIENPTExFQ1RJT048L3NwYW4+PC9zcGFuPjwvc3Ryb25nPjwvcD48cD5UaGUgZGF0YSB3ZSBjb2xsZWN0IGNvbnNpc3RzIG9mIHdoYXQgdGhlIFVzZXImbmJzcDsgdm9sdW50YXJpbHkgbWFrZXMgYXZhaWxhYmxlIHRvIHVzIHdoZW4gYWNjZXNzaW5nIHRoZSBXZWJzaXRlIChlLmcuIGVtYWlsIGFkZHJlc3MpIG9yIHNlbmRpbmcmbmJzcDsgQ3VycmljdWx1bSBWaXRhZSAo4oCcQ1bigJ0pJm5ic3A7IChlLmcuIG5hbWUsIHN1cm5hbWUuIHRlbGVwaG9uZSwgZXRjLikuJm5ic3A7PC9wPjxwPk92ZXJhbGwgd2UgY29sbGVjdCBwZXJzb25hbGx5IGlkZW50aWZpYWJsZSBpbmZvcm1hdGlvbiwgc3VjaCBhcyB5b3VyIGUtbWFpbCBhZGRyZXNzLCBuYW1lLCBob21lIG9yIHdvcmsgYWRkcmVzcyBhbmQgdGVsZXBob25lIG51bWJlci48L3A+PHA+V2UgbWF5IGFsc28gY29sbGVjdCBhbm9ueW1vdXMgZGVtb2dyYXBoaWMgaW5mb3JtYXRpb24sIHdoaWNoIGlzIG5vdCB1bmlxdWUgdG8geW91LCBzdWNoIGFzIHlvdXIgWklQIGNvZGUsIGFnZSwgZ2VuZGVyLCBwcmVmZXJlbmNlcywgaW50ZXJlc3RzIGFuZCBmYXZvcml0ZXMuIFRoZXJlIGlzIGFsc28gaW5mb3JtYXRpb24gYWJvdXQgeW91ciBjb21wdXRlciBoYXJkd2FyZSBhbmQgc29mdHdhcmUgdGhhdCBpcyBhdXRvbWF0aWNhbGx5IGNvbGxlY3RlZCBieSB0aGUgV2Vic2l0ZS4gVGhpcyBpbmZvcm1hdGlvbiBjYW4gaW5jbHVkZTogeW91ciBJUCBhZGRyZXNzLCBicm93c2VyIHR5cGUsIGRvbWFpbiBuYW1lcywgYWNjZXNzIHRpbWVzIGFuZCByZWZlcnJpbmcgV2Vic2l0ZSBhZGRyZXNzZXMuPC9wPjxwPkVyZ29kb3Rpc2kmbmJzcDsgZW5jb3VyYWdlcyB5b3UgdG8gcmV2aWV3IHRoZSBwcml2YWN5IHN0YXRlbWVudHMgb2YgV2Vic2l0ZXMgeW91IGNob29zZSB0byBsaW5rIHRvIGZyb20gZXJnb2RvdGlzaS5jb20gc28gdGhhdCB5b3UgY2FuIHVuZGVyc3RhbmQgaG93IHRob3NlIFdlYnNpdGVzIGNvbGxlY3QsIHVzZSBhbmQgc2hhcmUgeW91ciBpbmZvcm1hdGlvbi4gTWVsaW9yIENhcGl0YWwgTHRzIGFuZC9vciBFcmdvZG90aXNpIGlzIG5vdCByZXNwb25zaWJsZSBmb3IgdGhlIHByaXZhY3kgc3RhdGVtZW50cyBvciBvdGhlciBjb250ZW50IG9uIHdlYnNpdGVzIG91dHNpZGUgb2YgZXJnb2RvdGlzLmNvbTwvcD48cD5XZSBkbyBub3QgY29sbGVjdCBhbnkgU3BlY2lhbCBDYXRlZ29yaWVzIG9mIFBlcnNvbmFsIERhdGEgYWJvdXQgeW91ICh0aGlzIGluY2x1ZGVzIGRldGFpbHMgYWJvdXQgeW91ciByYWNlIG9yIGV0aG5pY2l0eSwgcmVsaWdpb3VzIG9yIHBoaWxvc29waGljYWwgYmVsaWVmcywgc2V4IGxpZmUsIHNleHVhbCBvcmllbnRhdGlvbiwgcG9saXRpY2FsIG9waW5pb25zLCB0cmFkZSB1bmlvbiBtZW1iZXJzaGlwLCBpbmZvcm1hdGlvbiBhYm91dCB5b3VyIGhlYWx0aCBhbmQgZ2VuZXRpYyBhbmQgYmlvbWV0cmljIGRhdGEpLiBOb3IgZG8gd2UgY29sbGVjdCBhbnkgaW5mb3JtYXRpb24gYWJvdXQgY3JpbWluYWwgY29udmljdGlvbnMgYW5kIG9mZmVuY2VzLjwvcD48cD5UaGUmbmJzcDsgV2Vic2l0ZSBjb25zaXN0cyBvZiAmcXVvdDtjb29raWVzJnF1b3Q7IHRvIGhlbHAgeW91IHBlcnNvbmFsaXplIHlvdXIgb25saW5lIGV4cGVyaWVuY2UuIEEgY29va2llIGlzIGEgdGV4dCBmaWxlIHRoYXQgaXMgcGxhY2VkIG9uIHlvdXIgaGFyZCBkaXNrIGJ5IGEgV2ViIHBhZ2Ugc2VydmVyLiBDb29raWVzIGNhbm5vdCBiZSB1c2VkIHRvIHJ1biBwcm9ncmFtcyBvciBkZWxpdmVyIHZpcnVzZXMgdG8geW91ciBjb21wdXRlci4gQ29va2llcyBhcmUgdW5pcXVlbHkgYXNzaWduZWQgdG8geW91LCBhbmQgY2FuIG9ubHkgYmUgcmVhZCBieSBhIHdlYiBzZXJ2ZXIgaW4gdGhlIGRvbWFpbiB0aGF0IGlzc3VlZCB0aGUgY29va2llIHRvIHlvdS4gT25lIG9mIHRoZSBwcmltYXJ5IHB1cnBvc2VzIG9mIGNvb2tpZXMgaXMgdG8gcHJvdmlkZSBhIGNvbnZlbmllbmNlIGZlYXR1cmUgdG8gc2F2ZSB5b3UgdGltZS4gVGhlIHB1cnBvc2Ugb2YgYSBjb29raWUgaXMgdG8gdGVsbCB0aGUgV2ViIHNlcnZlciB0aGF0IHlvdSBoYXZlIHJldHVybmVkIHRvIGEgc3BlY2lmaWMgcGFnZS4gRm9yIGV4YW1wbGUsIGlmIHlvdSByZWdpc3RlciB3aXRoIHRoZSBXZWJpc3RlIG9yIHNlcnZpY2VzLCBhIGNvb2tpZSBoZWxwcyB1cyZuYnNwOyByZWNhbGwgeW91ciBzcGVjaWZpYyBpbmZvcm1hdGlvbiBvbiBzdWJzZXF1ZW50IHZpc2l0cy4gVGhpcyBzaW1wbGlmaWVzIHRoZSBwcm9jZXNzIG9mIHJlY29yZGluZyB5b3VyIHBlcnNvbmFsIGluZm9ybWF0aW9uLCBzdWNoIGFzIGJpbGxpbmcgYWRkcmVzc2VzLCBzaGlwcGluZyBhZGRyZXNzZXMsIGFuZCBzbyBvbi4gV2hlbiB5b3UgcmV0dXJuIHRvIHRoZSBXZWJzaXRlLCB0aGUgaW5mb3JtYXRpb24geW91IHByZXZpb3VzbHkgcHJvdmlkZWQgY2FuIGJlIHJldHJpZXZlZCwgc28geW91IGNhbiBlYXNpbHkgdXNlIHRoZSBXZWJpc3RlIGZlYXR1cmVzIHRoYXQgeW91IGN1c3RvbWl6ZWQuIFlvdSBoYXZlIHRoZSBhYmlsaXR5IHRvIGFjY2VwdCBvciBkZWNsaW5lIGNvb2tpZXMuPC9wPjxwPk1vc3QgV2ViIGJyb3dzZXJzIGF1dG9tYXRpY2FsbHkgYWNjZXB0IGNvb2tpZXMsIGJ1dCB5b3UgY2FuIHVzdWFsbHkgbW9kaWZ5IHlvdXIgYnJvd3NlciBzZXR0aW5nIHRvIGRlY2xpbmUgY29va2llcyBpZiB5b3UgcHJlZmVyLiBJZiB5b3UgY2hvb3NlIHRvIGRlY2xpbmUgY29va2llcywgeW91IG1heSBub3QgYmUgYWJsZSB0byBmdWxseSBleHBlcmllbmNlIHRoZSBpbnRlcmFjdGl2ZSBmZWF0dXJlcyBvZiB0aGUgV2Vic2l0ZS48L3A+PHA+PGJyIC8+PC9wPjxwPjxzcGFuIHN0eWxlPSJmb250LXNpemU6IDEycHQ7Ij48c3BhbiBzdHlsZT0idGV4dC1kZWNvcmF0aW9uOiB1bmRlcmxpbmU7Ij48c3Ryb25nPjQuIFVTRSBPRiBUSEUgREFUQTwvc3Ryb25nPjwvc3Bhbj48L3NwYW4+PC9wPjxwPldlIHdpbGwgb25seSB1c2UgeW91ciBwZXJzb25hbCBkYXRhIHdoZW4gdGhlIGxhdyBhbGxvd3MgdXMgdG8uIE1vc3QgY29tbW9ubHksIHdlIHdpbGwgdXNlIHlvdXIgcGVyc29uYWwgZGF0YSBpbiB0aGUgZm9sbG93aW5nIGNpcmN1bXN0YW5jZXM6PC9wPjx1bD48bGk+V2hlcmUgd2UgbmVlZCB0byBwZXJmb3JtIHRoZSBjb250cmFjdCB3ZSBhcmUgYWJvdXQgdG8gZW50ZXIgaW50byBvciBoYXZlIGVudGVyZWQgaW50byB3aXRoIHlvdS48L2xpPjwvdWw+PHVsPjxsaT5XaGVyZSBpdCBpcyBuZWNlc3NhcnkgZm9yIG91ciBsZWdpdGltYXRlIGludGVyZXN0cy4gTGVnaXRpbWF0ZSBJbnRlcmVzdCBtZWFucyB0aGUgaW50ZXJlc3Qgb2Ygb3VyIGJ1c2luZXNzIGluIGNvbmR1Y3RpbmcgYW5kIG1hbmFnaW5nIG91ciBidXNpbmVzcyB0byBlbmFibGUgdXMgdG8gZ2l2ZSB5b3UgdGhlIGJlc3Qgc2VydmljZS9wcm9kdWN0IGFuZCB0aGUgYmVzdCBhbmQgbW9zdCBzZWN1cmUgZXhwZXJpZW5jZS4gV2UgbWFrZSBzdXJlIHdlIGNvbnNpZGVyIGFuZCBiYWxhbmNlIGFueSBwb3RlbnRpYWwgaW1wYWN0IG9uIHlvdSAoYm90aCBwb3NpdGl2ZSBhbmQgbmVnYXRpdmUpIGFuZCB5b3VyIHJpZ2h0cyBiZWZvcmUgd2UgcHJvY2VzcyB5b3VyIHBlcnNvbmFsIGRhdGEgZm9yIG91ciBsZWdpdGltYXRlIGludGVyZXN0cy4gV2UgZG8gbm90IHVzZSB5b3VyIHBlcnNvbmFsIGRhdGEgZm9yIGFjdGl2aXRpZXMgd2hlcmUgb3VyIGludGVyZXN0cyBhcmUgb3ZlcnJpZGRlbiBieSB0aGUgaW1wYWN0IG9uIHlvdSAodW5sZXNzIHdlIGhhdmUgeW91ciBjb25zZW50IG9yIGFyZSBvdGhlcndpc2UgcmVxdWlyZWQgb3IgcGVybWl0dGVkIHRvIGJ5IGxhdykuKFdoZXJlIHdlIG5lZWQgdG8gY29tcGx5IHdpdGggYSBsZWdhbCBvciByZWd1bGF0b3J5IG9ibGlnYXRpb24uPC9saT48L3VsPjx1bD48bGk+V2hlcmUgaXQgaXMgbmVjZXNzYXJ5IGZvciBjb21wbGlhbmNlIHdpdGggYSBsZWdhbCBvciByZWd1bGF0b3J5IG9ibGlnYXRpb24gdGhhdCB3ZSBhcmUgc3ViamVjdCB0by48L2xpPjwvdWw+PHA+Jm5ic3A7TWVsaW9yIENhcGl0YWwgTHRkIHVzZXMgdGhlIGRhdGEgaXQgY29sbGVjdHMgdG8gaW5mb3JtIHVzZXJzIGFib3V0IG5ldywgdG8gbW9kaWZ5IHRoZSBzZXJ2aWNlcyB0aGVyZWluLCBpbXByb3ZlIHRoZSBwZXJmb3JtYW5jZSBvZiB0aGUgV2Vic2l0ZSwgdG8gc2VuZCBpbmZvcm1hdGlvbiBhbmQgcHJvZmVzc2lvbmFsIG1hdGVyaWFsLCBpZiB0aGUgdXNlciBoYXMgY29uc2VudGVkIHRvIHRoaXMsIGFzIHdlbGwgYXMgdG8gY29sbGVjdCBzdGF0aXN0aWNzLiBXaXRoIHJlc3BlY3QgdG8gdGhlIFBlcnNvbmFsIERhdGEgY29sbGVjdGVkIGZyb20gdGhlIENWcyB1cGxvYWRlZCBieSB0aGUgVXNlcnMgKGUuZy4gbmFtZSwgdGVsZXBob25lLCBhZGRyZXNzLCBldGMpLCBNZWxpb3IgQ2FwaXRhbCBMdGQmbmJzcDsgcmV0YWlucyB0aGUgcmlnaHQgYm90aCB0byBjb2xsZWN0IGFuZCBkaXNwb3NlIGl0IC0gcHJvbW90ZSBpdCB0byBpbnRlcmVzdGVkIGVtcGxveWVycyAtIGJ1c2luZXNzZXMsIGFnZW5jaWVzLCBvcmdhbml6YXRpb25zIG9yIGh1bWFuIHJlc291cmNlcyBjb25zdWx0YW50cyB3aG8gYXJlIHN1YnNjcmliZXJzLjwvcD48cD5JbiBhZGRpdGlvbiwgR29vZ2xlLCBhcyBhIHRoaXJkIHBhcnR5IHZlbmRvciwgdXNlcyBjb29raWVzIHRvIHJ1biBhZHMgb24gdGhlIFdlYnNpdGUuIFRoZSB1c2Ugb2YgREFSVCBjb29raWVzIGZyb20gR29vZ2xlJm5ic3A7IGFsbG93cyBpdCB0byBkaXNwbGF5IGFkcyB0byBlcmdvZG90aXNpIHVzZXJzIGJhc2VkIG9uIHRoZWlyIHZpc2l0cyB0byBvdXIgV2Vic2l0ZSBhbmQgb3RoZXIgV2Vic2l0ZXMgb24gdGhlIEludGVybmV0LjwvcD48cD5NZWxpb3IgQ2FwaXRhbCBMdGQgYWxzbyB1c2VzIHlvdXIgcGVyc29uYWxseSBpZGVudGlmaWFibGUgaW5mb3JtYXRpb24gdG8gaW5mb3JtIHlvdSBvZiBvdGhlciBwcm9kdWN0cyBvciBzZXJ2aWNlcyBhdmFpbGFibGUgZnJvbSBNZWxpb3IgQ2FwaXRhbCBMdGQgYW5kIGl0cyBhZmZpbGlhdGVzLjwvcD48cD5JbiB0aGUgaW5zdGFuY2UsIHRoYXQgeW91IHdpbGwgYmUgY29tbXVuaWNhdGVkIGJ5IGFuIGFmZmlsaWF0ZSZuYnNwOyBmb3IgdGhlIHB1cnBvc2VzIG9mIGRpcmVjdCBtYXJrZXRpbmcsIHByaW9yIHRvIHN1Y2ggY29tbXVuaWNhdGlvbiBiZWluZyBhZmZlY3RlZCB5b3Ugd2lsbCBiZSByZXF1ZXN0ZWQgdG8gZ2l2ZSZuYnNwOyB5b3VyIGZyZWUsIGV4cGxpY2l0IGFuZCBzcGVjaWZpYyBjb25zZW50IHRvIGJlIGV4cHJlc3NlZCBpbiBhIGNsZWFyIGFuZCZuYnNwOyBjb25zY2lvdXMgbWFubmVyLiBTdWNoIGNvbnNlbnQgd2lsbCBiZSByZXF1ZXN0ZWQgdG8gYmUgZ2l2ZW4gYnkgeW91IHdoZW4geW91IHdpbGwgYmUgdmlzaXRpbmcgdGhlIFdlYnNpdGUgb2YgdGhlIHNhaWQgcmVsYXRlZCBjb21wYW5pZXMgYW5kIHRpY2tpbmcgdGhlIHJlbGV2YW50IGJveCByZWZlcnJpbmcgdG8gdGhlIHByb3Zpc2lvbiBvZiBkaXJlY3QgbWFya2V0aW5nIHNlcnZpY2VzLjwvcD48cD48YnIgLz48L3A+IDxwPjxzcGFuIHN0eWxlPSJmb250LXNpemU6IDEycHQ7Ij48c3BhbiBzdHlsZT0idGV4dC1kZWNvcmF0aW9uOiB1bmRlcmxpbmU7Ij48c3Ryb25nPjUuIEFDQ0VTUyBUTyBUSEUgREFUQS9ZT1VSIFJJR0hUUyBBUyBVU0VSIE9OIFRIRSBXRUJTSVRFPC9zdHJvbmc+PC9zcGFuPjwvc3Bhbj48L3A+PHA+VW5kZXIgY2VydGFpbiBjaXJjdW1zdGFuY2VzLCB5b3UgaGF2ZSByaWdodHMgdW5kZXIgZGF0YSBwcm90ZWN0aW9uIGxhd3MgaW4gcmVsYXRpb24gdG8geW91ciBQZXJzb25hbCBEYXRhLiBTdWNoIHJpZ2h0cyBhcmUgYXMgZm9sbG93czo8L3A+PHVsPjxsaT48c3Ryb25nPlJlcXVlc3QgYWNjZXNzPC9zdHJvbmc+Jm5ic3A7dG8geW91ciBQZXJzb25hbCBEYXRhIChjb21tb25seSBrbm93biBhcyBhIOKAnGRhdGEgc3ViamVjdCBhY2Nlc3MgcmVxdWVzdOKAnSkuIFRoaXMgZW5hYmxlcyB5b3UgdG8gcmVjZWl2ZSBhIGNvcHkgb2YgdGhlIHBlcnNvbmFsIGRhdGEgd2UgaG9sZCBhYm91dCB5b3UgYW5kIHRvIGNoZWNrIHRoYXQgd2UgYXJlIGxhd2Z1bGx5IHByb2Nlc3NpbmcgaXQuPC9saT48L3VsPjx1bD48bGk+PHNwYW4+PHN0cm9uZz5SZXF1ZXN0IGNvcnJlY3Rpb248L3N0cm9uZz4mbmJzcDs8L3NwYW4+PHNwYW4+b2YgdGhlIFBlcnNvbmFsIERhdGEgdGhhdCB3ZSBob2xkIGFib3V0IHlvdS4gVGhpcyBlbmFibGVzIHlvdSB0byBoYXZlIGFueSBpbmNvbXBsZXRlIG9yIGluYWNjdXJhdGUgZGF0YSB3ZSBob2xkIGFib3V0IHlvdSBjb3JyZWN0ZWQsIHRob3VnaCB3ZSBtYXkgbmVlZCB0byB2ZXJpZnkgdGhlIGFjY3VyYWN5IG9mIHRoZSBuZXcgZGF0YSB5b3UgcHJvdmlkZSB0byB1cy48L3NwYW4+PC9saT48L3VsPjx1bD48bGk+PHNwYW4+PHN0cm9uZz5SZXF1ZXN0IGVyYXN1cmU8L3N0cm9uZz4mbmJzcDs8L3NwYW4+PHNwYW4+b2YgeW91ciBQZXJzb25hbCBEYXRhLiBUaGlzIGVuYWJsZXMgeW91IHRvIGFzayB1cyB0byBkZWxldGUgb3IgcmVtb3ZlIHBlcnNvbmFsIGRhdGEgd2hlcmUgdGhlcmUgaXMgbm8gZ29vZCByZWFzb24gZm9yIHVzIGNvbnRpbnVpbmcgdG8gcHJvY2VzcyBpdC4gWW91IGFsc28gaGF2ZSB0aGUgcmlnaHQgdG8gYXNrIHVzIHRvIGRlbGV0ZSBvciByZW1vdmUgeW91ciBwZXJzb25hbCBkYXRhIHdoZXJlIHlvdSBoYXZlIHN1Y2Nlc3NmdWxseSBleGVyY2lzZWQgeW91ciByaWdodCB0byBvYmplY3QgdG8gcHJvY2Vzc2luZyAoc2VlIGJlbG93KSwgd2hlcmUgd2UgbWF5IGhhdmUgcHJvY2Vzc2VkIHlvdXIgaW5mb3JtYXRpb24gdW5sYXdmdWxseSBvciB3aGVyZSB3ZSBhcmUgcmVxdWlyZWQgdG8gZXJhc2UgeW91ciBwZXJzb25hbCBkYXRhIHRvIGNvbXBseSB3aXRoIGxvY2FsIGxhdy4gTm90ZSwgaG93ZXZlciwgdGhhdCB3ZSBtYXkgbm90IGFsd2F5cyBiZSBhYmxlIHRvIGNvbXBseSB3aXRoIHlvdXIgcmVxdWVzdCBvZiBlcmFzdXJlIGZvciBzcGVjaWZpYyBsZWdhbCByZWFzb25zIHdoaWNoIHdpbGwgYmUgbm90aWZpZWQgdG8geW91LCBpZiBhcHBsaWNhYmxlLCBhdCB0aGUgdGltZSBvZiB5b3VyIHJlcXVlc3QuPC9zcGFuPjwvbGk+PC91bD48dWw+PGxpPjxzdHJvbmc+T2JqZWN0IHRvIHByb2Nlc3Npbmc8L3N0cm9uZz4mbmJzcDtvZiB5b3VyIFBlcnNvbmFsIERhdGEgd2hlcmUgd2UgYXJlIHJlbHlpbmcgb24gYSBsZWdpdGltYXRlIGludGVyZXN0IChvciB0aG9zZSBvZiBhIHRoaXJkIHBhcnR5KSBhbmQgdGhlcmUgaXMgc29tZXRoaW5nIGFib3V0IHlvdXIgcGFydGljdWxhciBzaXR1YXRpb24gd2hpY2ggbWFrZXMgeW91IHdhbnQgdG8gb2JqZWN0IHRvIHByb2Nlc3Npbmcgb24gdGhpcyBncm91bmQgYXMgeW91IGZlZWwgaXQgaW1wYWN0cyBvbiB5b3VyIGZ1bmRhbWVudGFsIHJpZ2h0cyBhbmQgZnJlZWRvbXMuIFlvdSBhbHNvIGhhdmUgdGhlIHJpZ2h0IHRvIG9iamVjdCB3aGVyZSB3ZSBhcmUgcHJvY2Vzc2luZyB5b3VyIHBlcnNvbmFsIGRhdGEgZm9yIGRpcmVjdCBtYXJrZXRpbmcgcHVycG9zZXMuIEluIHNvbWUgY2FzZXMsIHdlIG1heSBkZW1vbnN0cmF0ZSB0aGF0IHdlIGhhdmUgY29tcGVsbGluZyBsZWdpdGltYXRlIGdyb3VuZHMgdG8gcHJvY2VzcyB5b3VyIGluZm9ybWF0aW9uIHdoaWNoIG92ZXJyaWRlIHlvdXIgcmlnaHRzIGFuZCBmcmVlZG9tcy48L2xpPjwvdWw+PHVsPjxsaT48c3Bhbj48c3Ryb25nPlJlcXVlc3QgcmVzdHJpY3Rpb24gb2YgcHJvY2Vzc2luZzwvc3Ryb25nPiZuYnNwOzwvc3Bhbj48c3Bhbj5vZiB5b3VyIFBlcnNvbmFsIERhdGEuIFRoaXMgZW5hYmxlcyB5b3UgdG8gYXNrIHVzIHRvIHN1c3BlbmQgdGhlIHByb2Nlc3Npbmcgb2YgeW91ciBwZXJzb25hbCBkYXRhIGluIHRoZSBmb2xsb3dpbmcgc2NlbmFyaW9zOiAoYSkgaWYgeW91IHdhbnQgdXMgdG8gZXN0YWJsaXNoIHRoZSBkYXRh4oCZcyBhY2N1cmFjeTsgKGIpIHdoZXJlIG91ciB1c2Ugb2YgdGhlIGRhdGEgaXMgdW5sYXdmdWwgYnV0IHlvdSBkbyBub3Qgd2FudCB1cyB0byBlcmFzZSBpdDsgKGMpIHdoZXJlIHlvdSBuZWVkIHVzIHRvIGhvbGQgdGhlIGRhdGEgZXZlbiBpZiB3ZSBubyBsb25nZXIgcmVxdWlyZSBpdCBhcyB5b3UgbmVlZCBpdCB0byBlc3RhYmxpc2gsIGV4ZXJjaXNlIG9yIGRlZmVuZCBsZWdhbCBjbGFpbXM7IG9yIChkKSB5b3UgaGF2ZSBvYmplY3RlZCB0byBvdXIgdXNlIG9mIHlvdXIgZGF0YSBidXQgd2UgbmVlZCB0byB2ZXJpZnkgd2hldGhlciB3ZSBoYXZlIG92ZXJyaWRpbmcgbGVnaXRpbWF0ZSBncm91bmRzIHRvIHVzZSBpdC48L3NwYW4+PC9saT48L3VsPjx1bD48bGk+PHNwYW4+PHN0cm9uZz5SZXF1ZXN0IHRoZSB0cmFuc2Zlcjwvc3Ryb25nPiZuYnNwOzwvc3Bhbj48c3Bhbj5vZiB5b3VyIFBlcnNvbmFsIERhdGEgdG8geW91IG9yIHRvIGEgdGhpcmQgcGFydHkuIFdlIHdpbGwgcHJvdmlkZSB0byB5b3UsIG9yIGEgdGhpcmQgcGFydHkgeW91IGhhdmUgY2hvc2VuLCB5b3VyIHBlcnNvbmFsIGRhdGEgaW4gYSBzdHJ1Y3R1cmVkLCBjb21tb25seSB1c2VkLCBtYWNoaW5lLXJlYWRhYmxlIGZvcm1hdC4gTm90ZSB0aGF0IHRoaXMgcmlnaHQgb25seSBhcHBsaWVzIHRvIGF1dG9tYXRlZCBpbmZvcm1hdGlvbiB3aGljaCB5b3UgaW5pdGlhbGx5IHByb3ZpZGVkIGNvbnNlbnQgZm9yIHVzIHRvIHVzZSBvciB3aGVyZSB3ZSB1c2VkIHRoZSBpbmZvcm1hdGlvbiB0byBwZXJmb3JtIGEgY29udHJhY3Qgd2l0aCB5b3UuPC9zcGFuPjwvbGk+PC91bD48dWw+PGxpPjxzcGFuPjxzdHJvbmc+V2l0aGRyYXcgY29uc2VudCBhdCBhbnkgdGltZTwvc3Ryb25nPiZuYnNwOzwvc3Bhbj48c3Bhbj53aGVyZSB3ZSBhcmUgcmVseWluZyBvbiBjb25zZW50IHRvIHByb2Nlc3MgeW91ciBQZXJzb25hbCBEYXRhLiBIb3dldmVyLCB0aGlzIHdpbGwgbm90IGFmZmVjdCB0aGUgbGF3ZnVsbmVzcyBvZiBhbnkgcHJvY2Vzc2luZyBjYXJyaWVkIG91dCBiZWZvcmUgeW91IHdpdGhkcmF3IHlvdXIgY29uc2VudC4gSWYgeW91IHdpdGhkcmF3IHlvdXIgY29uc2VudCwgd2UgbWF5IG5vdCBiZSBhYmxlIHRvIHByb3ZpZGUgY2VydGFpbiBwcm9kdWN0cyBvciBzZXJ2aWNlcyB0byB5b3UuIFdlIHdpbGwgYWR2aXNlIHlvdSBpZiB0aGlzIGlzIHRoZSBjYXNlIGF0IHRoZSB0aW1lIHlvdSB3aXRoZHJhdyB5b3VyIGNvbnNlbnQuPC9zcGFuPjwvbGk+PC91bD48cD4mbmJzcDtJdCBpcyBub3RlZCB0aGF0IHVwb24gdGhlIHJlZ2lzdHJhdGlvbiBvZiB0aGUgVXNlciBvbiB0aGUgV2Vic2l0ZSBhbmQgYWZ0ZXIgcHJvdmlkaW5nIGhpcyBlLW1haWwgYWRkcmVzcywgdGhlIFVzZXIgYXV0b21hdGljYWxseSBiZWNvbWVzIGEgcmVjaXBpZW50IG9mIHRoZSBXZWJzaXRl4oCZcyBuZXdzbGV0dGVyLiBUaGUgVXNlciBjYW4gT3B0LU91dCBmcm9tIHJlY2VpdmluZyBzdWNoIG5ld3NsZXR0ZXIgYnkgY2xpY2tpbmcgb24gdGhlIGxpbmsgdGhlcmVpbi48L3A+PHA+PGJyIC8+PC9wPjxwPjxzcGFuIHN0eWxlPSJmb250LXNpemU6IDEycHQ7Ij48c3BhbiBzdHlsZT0idGV4dC1kZWNvcmF0aW9uOiB1bmRlcmxpbmU7Ij48c3Ryb25nPjYuIENWIEJBTks8L3N0cm9uZz48L3NwYW4+PC9zcGFuPjwvcD48cD5UaGUgVXNlciBtYXkgbW9kaWZ5LCB1cGRhdGUsIG9yIGRlbGV0ZSBoaXMgQ1YgdGhyb3VnaCBoaXMgb3IgaGVyIGFjY291bnQgYXQgYW55IHRpbWUuIERlbGV0aW9uIG1lYW5zIHRoYXQgdGhpcmQgcGFydGllcyB3aWxsIG5vdCBiZSBhYmxlIHRvIGFjY2VzcyBpdC4gTWVsaW9yIENhcGl0YWwgTHRkIHZpYSBFcmdvZG90aXNpIHByb3ZpZGVzIGFjY2VzcyB0byB0aGUgQ1YgQmFuayB0byBpdHMgc3Vic2NyaWJlcnMgb25seSwgd2hvIGNhbiBhY2Nlc3MgaXQgdXNpbmcgdGhlIGNvbmZpZGVudGlhbCBjb2RlIHByb3ZpZGVkLjwvcD48cD5TZWVrNFUgaXMgc2VydmljZSwgd2hlcmUgYSBjb21wYW55IGlzIGFibGUgdG8gc2VhcmNoLCBzcG90IGFuZCBhcHByb2FjaCB0aGUgcGVyZmVjdCBjYW5kaWRhdGUgZm9yIHRoZSBwb3NpdGlvbiwgdXNpbmcgdG93biwgY2F0ZWdvcmllcywgc2tpbGxzIGFuZCBleHBlcmllbmNlIHNlYXJjaCBjcml0ZXJpYS4gVGhlIHRpbWUgZHVyYXRpb24gb2YgdGhpcyBzZXJ2aWNlIGlzIG9uZSB5ZWFyLiBVc2VycyBvZiBFcmdvZG90aXNpIGhhdmUgdGhlIG9wdGlvbiBvZiBjcmVhdGluZyBhbmQgcmVnaXN0ZXJpbmcgdGhlaXIgQ1ZzIHRvIHRoZSBTZWVrNFUgYmFuay4gQWNjZXNzIHRvIGZ1bGwgQ1YgZGV0YWlscyBpcyBvbmx5IGF2YWlsYWJsZSB0byBjb21wYW5pZXMgdGhhdCBoYXZlIHByb2NlZWRlZCB3aXRoIHRoZSByZWxldmFudCBwdXJjaGFzZSAoU2VlazRVIENWKS4gQWxsIGNvbXBhbmllcyBtYXkgaGF2ZSBhY2Nlc3MgdG8gdGhlIFNlZWs0VSBDViwgYnV0IHdpdGhvdXQgc2hvd2luZyBhbnkgcGVyc29uYWwgaW5mb3JtYXRpb24gYW5kIGNvbnRhY3QgaW5mb3JtYXRpb24gb3IgYXR0YWNobWVudHMuPC9wPjxwPjxiciAvPjwvcD48cD48c3BhbiBzdHlsZT0iZm9udC1zaXplOiAxMnB0OyI+PHNwYW4gc3R5bGU9InRleHQtZGVjb3JhdGlvbjogdW5kZXJsaW5lOyI+PHN0cm9uZz43LiBESVNQT1NBTCBUTyBUSElSRCBQQVJUSUVTPC9zdHJvbmc+PC9zcGFuPjwvc3Bhbj48L3A+PHA+RXhjZXB0IGFzIHNwZWNpZmljYWxseSBzZXQgZm9ydGggaW4gdGhpcyBQcml2YWN5IFBvbGljeSAsIHdlIGRvIG5vdCBzaGFyZSB5b3VyIHBlcnNvbmFsIGluZm9ybWF0aW9uIHdpdGggYW55IG5vbi1hZmZpbGlhdGVkIHRoaXJkIHBhcnR5IHdpdGhvdXQgeW91ciBmcmVlLCBleHBsaWNpdCBhbmQgc3BlY2lmaWMgY29uc2VudCBhbmQgaW4gYW55IGV2ZW50IHdoZW4geW91ciBwZXJzb25hbCBpbmZvcm1hdGlvbiBpcyBjb2xsZWN0ZWQgd2Ugd2lsbCBub3RpZnkgeW91IG9mIHRoZSByZWNpcGllbnQgb3IgdGhlIGNhdGVnb3JpZXMgb2YgcmVjaXBpZW50cyBvZiBzdWNoIGluZm9ybWF0aW9uLiZuYnNwOyBGdXJ0aGVybW9yZSwgd2Ugd2lsbCBwcm9tcHRseSBub3RpZnkgeW91IHdoZW4gdGhlIHNhaWQgZGF0YSBhcmUgdG8gYmUgZmlyc3QgYW5ub3VuY2VkIHRvIGEgdGhpcmQgcGFydHkuIFdlIG1heSBkaXNjbG9zZSBhZ2dyZWdhdGUgaW5mb3JtYXRpb24sIHN1Y2ggYXMgZGVtb2dyYXBoaWMgaW5mb3JtYXRpb24sIGFuZCBvdXIgc3RhdGlzdGljYWwgYW5hbHlzZXMgdG8gdGhpcmQgcGFydGllcywgaW5jbHVkaW5nIGFkdmVydGlzZXJzIG9yIG90aGVyIGJ1c2luZXNzIHBhcnRuZXJzLiBUaGlzIGFnZ3JlZ2F0ZSBpbmZvcm1hdGlvbiBkb2VzIG5vdCBpbmNsdWRlIHlvdXIgcGVyc29uYWwgaW5mb3JtYXRpb24uPC9wPjxwPjxiciAvPjwvcD48cD48c3BhbiBzdHlsZT0idGV4dC1kZWNvcmF0aW9uOiB1bmRlcmxpbmU7Ij48c3Ryb25nPjxzcGFuIHN0eWxlPSJmb250LXNpemU6IDEycHQ7Ij44LiBTRUNVUklUWTwvc3Bhbj48L3N0cm9uZz48L3NwYW4+PC9wPjxwPlRoZSBzZWN1cml0eSBvZiB5b3VyIHBlcnNvbmFsIGluZm9ybWF0aW9uIGlzIGltcG9ydGFudCB0byB1cyBhbmQgdGhpcyBpcyB3aHkgd2UgbWFpbnRhaW4gcGh5c2ljYWwsIGVsZWN0cm9uaWMsIGFuZCBwcm9jZWR1cmFsIHNhZmVndWFyZHMgdG8gc2VjdXJlIHlvdXIgcGVyc29uYWwgaW5mb3JtYXRpb24uIE1lbGlvciBDYXBpdGFsIEx0ZCBhbmQvb3IgRXJnb2RvdGlzaSBzZWN1cmVzIHlvdXIgcGVyc29uYWwgaW5mb3JtYXRpb24gZnJvbSB1bmF1dGhvcml6ZWQgYWNjZXNzLCB1c2Ugb3IgZGlzY2xvc3VyZS48L3A+PHA+VGhpcyBXZWJzaXRlIGhhcyBzZWN1cml0eSBtZWFzdXJlcyBpbiBwbGFjZSB0byBwcm90ZWN0IHRoZSBsb3NzLCBtaXN1c2UgYW5kIGFsdGVyYXRpb24gb2YgdGhlIGluZm9ybWF0aW9uIHVuZGVyIG91ciBjb250cm9sLiBTdWNoIG1lYXN1cmVzIGluY2x1ZGUgcmVndWxhciBzZWN1cml0eSByZXZpZXdzLCB1cGdyYWRlcywgYW5kIGJhY2t1cHMuIFdlIHVzZSBvdXIgYmVzdCBlZmZvcnRzIHRvIG1haW50YWluIHRoZSBzZWN1cml0eSBhbmQgcmVsaWFiaWxpdHkgb2Ygb3VyIGluZnJhc3RydWN0dXJlOyBob3dldmVyLCB0aGV5IGFyZSBwcm92aWRlZCAmcXVvdDthcyBpcyZxdW90OyB3aXRob3V0IGFueSBleHByZXNzIG9yIGltcGxpZWQgd2FycmFudHkgb2YgYW55IGtpbmQgaW5jbHVkaW5nIHdhcnJhbnRpZXMgb2YgbWVyY2hhbnRhYmlsaXR5LCByZWxpYWJpbGl0eSwgb3IgZml0bmVzcyBmb3IgYSBwYXJ0aWN1bGFyIHB1cnBvc2UuIFdlIG9mZmVyIG5vIGFzc3VyYW5jZSBvZiB1bmludGVycnVwdGVkIG9yIGVycm9yIGZyZWUgc2VydmljZSwgbm9yIGRvZXMgTWVsaW9yIENhcGl0YWwgTHRkIHdhcnJhbnQgdGhlIGFjY3VyYWN5IG9yIGNvbXBsZXRlbmVzcyBvZiBhbnkgc2VydmljZS4gSW4gbm8gZXZlbnQgc2hhbGwgTWVsaW9yIENhcGl0YWwgTHRkIGJlIGhlbGQgbGlhYmxlIGZvciBhbnkgZGFtYWdlcyB3aGF0c29ldmVyIChpbmNsdWRpbmcsIHdpdGhvdXQgbGltaXRhdGlvbiwgZGFtYWdlcyBmb3IgbG9zcyBvZiBwcm9maXRzLCBidXNpbmVzcyBpbnRlcnJ1cHRpb24sIGxvc3Mgb2YgaW5mb3JtYXRpb24pIGFyaXNpbmcgb3V0IG9mIHRoZSB1c2Ugb3IgaW5hYmlsaXR5IHRvIHVzZSB0aGUgV2Vic2l0ZS48L3A+PHA+PGJyIC8+PC9wPjxwPjxzcGFuIHN0eWxlPSJmb250LXNpemU6IDEycHQ7Ij48c3BhbiBzdHlsZT0idGV4dC1kZWNvcmF0aW9uOiB1bmRlcmxpbmU7Ij48c3Ryb25nPjkuIElOVEVSTkFUSU9OQUwgVFJBTlNGRVJTPC9zdHJvbmc+PC9zcGFuPjwvc3Bhbj4mbmJzcDsmbmJzcDs8L3A+PHA+SW4gdGhlIGluc3RhbmNlIHRoYXQgeW91ciBQZXJzb25hbCBEYXRhIHdpbGwgYmUgdHJhbnNmZXJyZWQgb3V0IG9mIHRoZSBFRUEsIHdlIGVuc3VyZSBhIHNpbWlsYXIgZGVncmVlIG9mIHByb3RlY3Rpb24gaXMgYWZmb3JkZWQgdG8gaXQgYnkgZW5zdXJpbmcgYXQgbGVhc3Qgb25lIG9mIHRoZSBmb2xsb3dpbmcgc2FmZWd1YXJkcyBpcyBpbXBsZW1lbnRlZDo8L3A+PHVsPjxsaT5XZSB3aWxsIG9ubHkgdHJhbnNmZXIgeW91ciBwZXJzb25hbCBkYXRhIHRvIGNvdW50cmllcyB0aGF0IGhhdmUgYmVlbiBkZWVtZWQgdG8gcHJvdmlkZSBhbiBhZGVxdWF0ZSBsZXZlbCBvZiBwcm90ZWN0aW9uIGZvciBwZXJzb25hbCBkYXRhIGJ5IHRoZSBFdXJvcGVhbiBDb21taXNzaW9uIGluIGFjY29yZGFuY2Ugd2l0aCBBcnRpY2xlIDQ2IG9mIHRoZSBHRFBSLjwvbGk+PC91bD48dWw+PGxpPldoZXJlIHdlIHVzZSBjZXJ0YWluIHNlcnZpY2UgcHJvdmlkZXJzLCB3ZSBtYXkgdXNlIHNwZWNpZmljIGNvbnRyYWN0cyBhcHByb3ZlZCBieSB0aGUgRXVyb3BlYW4gQ29tbWlzc2lvbiB3aGljaCBnaXZlIHBlcnNvbmFsIGRhdGEgdGhlIHNhbWUgcHJvdGVjdGlvbiBpdCBoYXMgaW4gRXVyb3BlLjwvbGk+PC91bD48cD48YnIgLz48L3A+PHA+PHNwYW4gc3R5bGU9InRleHQtZGVjb3JhdGlvbjogdW5kZXJsaW5lOyI+PHN0cm9uZz48c3BhbiBzdHlsZT0iZm9udC1zaXplOiAxMnB0OyI+MTAuIERBVEEgUkVURU5USU9OPC9zcGFuPjwvc3Ryb25nPjwvc3Bhbj48L3A+PHA+V2Ugd2lsbCBvbmx5IHJldGFpbiB5b3VyIHBlcnNvbmFsIGRhdGEgZm9yIGFzIGxvbmcgYXMgbmVjZXNzYXJ5IHRvIGZ1bGZpbCB0aGUgcHVycG9zZXMgd2UgY29sbGVjdGVkIGl0IGZvciwgaW5jbHVkaW5nIGZvciB0aGUgcHVycG9zZXMgb2Ygc2F0aXNmeWluZyBhbnkgbGVnYWwsIGFjY291bnRpbmcsIG9yIHJlcG9ydGluZyByZXF1aXJlbWVudHMuPC9wPjxwPlRvIGRldGVybWluZSB0aGUgYXBwcm9wcmlhdGUgcmV0ZW50aW9uIHBlcmlvZCBmb3IgcGVyc29uYWwgZGF0YSwgd2UgY29uc2lkZXIgdGhlIGFtb3VudCwgbmF0dXJlLCBhbmQgc2Vuc2l0aXZpdHkgb2YgdGhlIHBlcnNvbmFsIGRhdGEsIHRoZSBwb3RlbnRpYWwgcmlzayBvZiBoYXJtIGZyb20gdW5hdXRob3Jpc2VkIHVzZSBvciBkaXNjbG9zdXJlIG9mIHlvdXIgcGVyc29uYWwgZGF0YSwgdGhlIHB1cnBvc2VzIGZvciB3aGljaCB3ZSBwcm9jZXNzIHlvdXIgcGVyc29uYWwgZGF0YSBhbmQgd2hldGhlciB3ZSBjYW4gYWNoaWV2ZSB0aG9zZSBwdXJwb3NlcyB0aHJvdWdoIG90aGVyIG1lYW5zLCBhbmQgdGhlIGFwcGxpY2FibGUgbGVnYWwgcmVxdWlyZW1lbnRzLjwvcD48cD48YnIgLz48L3A+PHA+PHNwYW4gc3R5bGU9InRleHQtZGVjb3JhdGlvbjogdW5kZXJsaW5lOyI+PHN0cm9uZz48c3BhbiBzdHlsZT0iZm9udC1zaXplOiAxMnB0OyI+MTEuIENIQU5HRVMgVE8gVEhJUyBTVEFURU1FTlQ8L3NwYW4+PC9zdHJvbmc+PC9zcGFuPjwvcD48cD5NZWxpb3IgQ2FwaXRhbCBMdGQgYW5kIEVyZ29kb3Rpc2kgd2lsbCBvY2Nhc2lvbmFsbHkgdXBkYXRlIHRoaXMgUHJpdmFjeSBQb2xpY3kgdG8gcmVmbGVjdCBjb21wYW55IGFuZCBjdXN0b21lciBmZWVkYmFjay4gWW91IHdpbGwgYmUgbm90aWZpZWQgb2YgYW55IGNoYW5nZXMgdG8gdGhpcyBQcml2YWN5IFBvbGljeSBidXQgd2UgZW5jb3VyYWdlIHlvdSZuYnNwOyB0byBwZXJpb2RpY2FsbHkgcmV2aWV3IHRoaXMgUHJpdmFjeSBQb2xpY3kgc28gYXMgdG8gYmUgaW5mb3JtZWQgb2YgaG93IHlvdXIgaW5mb3JtYXRpb24gaXMgcHJvdGVjdGVkLjwvcD48cD48YnIgLz48L3A+PHA+PHNwYW4gc3R5bGU9InRleHQtZGVjb3JhdGlvbjogdW5kZXJsaW5lOyI+PHN0cm9uZz48c3BhbiBzdHlsZT0iZm9udC1zaXplOiAxMnB0OyI+MTIuIFRJTUUgTElNSVQgVE8gUkVTUE9ORDwvc3Bhbj48L3N0cm9uZz48L3NwYW4+PC9wPjxwPldlIHRyeSB0byByZXNwb25kIHRvIGFsbCBsZWdpdGltYXRlIHJlcXVlc3RzIHdpdGhpbiBvbmUgbW9udGguIE9jY2FzaW9uYWxseSBpdCBtYXkgdGFrZSB1cyBsb25nZXIgdGhhbiBhIG1vbnRoIGlmIHlvdXIgcmVxdWVzdCBpcyBwYXJ0aWN1bGFybHkgY29tcGxleCBvciB5b3UgaGF2ZSBtYWRlIGEgbnVtYmVyIG9mIHJlcXVlc3RzLiBJbiB0aGlzIGNhc2UsIHdlIHdpbGwgbm90aWZ5IHlvdSBhbmQga2VlcCB5b3UgdXBkYXRlZC48L3A+PHA+PGJyIC8+PC9wPiA8cD48c3BhbiBzdHlsZT0idGV4dC1kZWNvcmF0aW9uOiB1bmRlcmxpbmU7Ij48c3Ryb25nPjxzcGFuIHN0eWxlPSJmb250LXNpemU6IDEycHQ7Ij4xMy4gVEhJUkQtUEFSVFkgTUFSS0VUSU5HPC9zcGFuPjwvc3Ryb25nPjwvc3Bhbj4mbmJzcDsmbmJzcDs8L3A+PHA+V2Ugd2lsbCBnZXQgeW91ciBleHByZXNzIG9wdC1pbiBjb25zZW50IGJlZm9yZSB3ZSBzaGFyZSB5b3VyIHBlcnNvbmFsIGRhdGEgd2l0aCBhbnkgY29tcGFueSBvdXRzaWRlIE1lbGlvciBDYXBpdGFsIEx0ZCBmb3IgbWFya2V0aW5nIHB1cnBvc2VzLjwvcD48cD48YnIgLz48L3A+ZAItDxYCHwMFOGh0dHBzOi8vd3d3LmVyZ29kb3Rpc2kuY29tL1JlZ2lzdGVyVXNlci5hc3B4P3Byb2R1Y3RpZD0wZAIvDxYCHwMFMGh0dHBzOi8vd3d3LmVyZ29kb3Rpc2kuY29tL1NlYXJjaFJlc3VsdHMuYXNweD9xPWQCMQ8WAh8DBSlodHRwczovL3d3dy5lcmdvZG90aXNpLmNvbS9Db21wYW5pZXMuYXNweGQCNQ8WAh8DBS5odHRwczovL3d3dy5lcmdvZG90aXNpLmNvbS9FbXBsb3llcnNMb2dpbi5hc3B4ZAI3DxYCHwMFLGh0dHBzOi8vd3d3LmVyZ29kb3Rpc2kuY29tL3ByaWNpbmcuYXNweCNmYXFzZAI5DxYCHwMFN2h0dHBzOi8vd3d3LmVyZ29kb3Rpc2kuY29tL1BvcnRhbC9BZGRKb2IuYXNweD9Db3VudHJ5PTFkAj0PFgIfAwUnaHR0cHM6Ly93d3cuZXJnb2RvdGlzaS5jb20vcHJpdmFjeS5hc3B4ZAI/DxYCHwMFKmh0dHBzOi8vd3d3LmVyZ29kb3Rpc2kuY29tL2NvbmRpdGlvbnMuYXNweGQCSQ8WAh8DBRtodHRwczovL3d3dy5lcmdvZG90aXNpLmNvbS8WAmYPFgIfAAUxzpjOlc6jzpXOmc6jIM6VzqHOk86RzqPOmc6RzqMgzqPOpM6Xzp0gzprOpc6gzqHOn2QCSw8PFgIfAgUqaHR0cHM6Ly93d3cuZXJnb2RvdGlzaS5jb20vam9icy1pbi1uaWNvc2lhZBYCZg8WAh8ABTXOmM6tz4POtc65z4IgzrXPgc6zzrHPg86vzrHPgiDPg8+EzrcgzpvOtc+FzrrPic+Dzq/OsWQCTQ8PFgIfAgUraHR0cHM6Ly93d3cuZXJnb2RvdGlzaS5jb20vam9icy1pbi1saW1hc3NvbGQWAmYPFgIfAAUxzpjOrc+DzrXOuc+CIM61z4HOs86xz4POr86xz4Igz4PPhM63IM6bzrXOvM61z4PPjGQCTw8PFgIfAgUqaHR0cHM6Ly93d3cuZXJnb2RvdGlzaS5jb20vam9icy1pbi1sYXJuYWthZBYCZg8WAh8ABTPOmM6tz4POtc65z4IgzrXPgc6zzrHPg86vzrHPgiDPg8+EzrcgzpvOrM+Bzr3Osc66zrFkAlEPDxYCHwIFKWh0dHBzOi8vd3d3LmVyZ29kb3Rpc2kuY29tL2pvYnMtaW4tcGFwaG9zZBYCZg8WAh8ABS/OmM6tz4POtc65z4IgzrXPgc6zzrHPg86vzrHPgiDPg8+EzrfOvSDOoM6sz4bOv2QCUw8PFgIfAgUsaHR0cHM6Ly93d3cuZXJnb2RvdGlzaS5jb20vam9icy1pbi1mYW1hZ3VzdGFkFgJmDxYCHwAFOc6Yzq3Pg861zrnPgiDOtc+BzrPOsc+Dzq/Osc+CIM+Dz4TOt869IM6RzrzOvM+Mz4fPic+Dz4TOv2QCVQ8WAh8DBSpodHRwczovL3d3dy5lcmdvZG90aXNpLmNvbS9jb25kaXRpb25zLmFzcHhkAlcPFgIfAwUpaHR0cHM6Ly93d3cuZXJnb2RvdGlzaS5jb20vY29udGFjdHVzLmFzcHhkAlkPFgIfAwU0aHR0cHM6Ly93d3cuZXJnb2RvdGlzaS5jb20vam9icG9zdGluZ2NvbmRpdGlvbnMuYXNweGQCWg8VARtodHRwczovL3d3dy5lcmdvZG90aXNpLmNvbS9kGAEFHl9fQ29udHJvbHNSZXF1aXJlUG9zdEJhY2tLZXlfXxYEBRdjdGwwMCRBU1B4UG9wdXBDb250cm9sMQUUY3RsMDAkQVNQeFBvcHVwTWVudTEFLmN0bDAwJEFTUHhQb3B1cE1lbnUxJElUQ05UNSRMb2dpblN0YXR1czEkY3RsMDEFLmN0bDAwJEFTUHhQb3B1cE1lbnUxJElUQ05UNSRMb2dpblN0YXR1czEkY3RsMDMqKrOKKnn8z10j66CtkrRVFI8JAg==" />
</div>
<script type="text/javascript">
//<![CDATA[
var theForm = document.forms['aspnetForm'];
if (!theForm) {
    theForm = document.aspnetForm;
}
function __doPostBack(eventTarget, eventArgument) {
    if (!theForm.onsubmit || (theForm.onsubmit() != false)) {
        theForm.__EVENTTARGET.value = eventTarget;
        theForm.__EVENTARGUMENT.value = eventArgument;
        theForm.submit();
    }
}
//]]>
</script>
<script src="/WebResource.axd?d=_ISKwEvy8JR_oRsaxpiFCmG3H2GrK2ez83YbwKbagCrjgdmSJtEiw0J0CIlWXT7Mk_2w9RAQzZ3UfVg4vd5rasu3pAg1&amp;t=636744885301435895" type="text/javascript"></script>
<script src="/WebResource.axd?d=BgGRysZTvZG92R_EFUsBLjHLb5rCcsHTGExhT8SpHEVDsXvULlCfzGGG6LpxcKvKzbeMBTgt46vvEGaRVUyZWYQsKcc1&amp;t=636744885301435895" type="text/javascript"></script>
<script type="text/javascript">
//<![CDATA[
function WebForm_OnSubmit() {
if (typeof(ValidatorOnSubmit) == "function" && ValidatorOnSubmit() == false) return false;
return true;
}
//]]>
</script>
<div class="aspNetHidden">
<input type="hidden" name="__VIEWSTATEGENERATOR" id="__VIEWSTATEGENERATOR" value="EAA40B43" />
<input type="hidden" name="__EVENTVALIDATION" id="__EVENTVALIDATION" value="/wEdAAZAIkcqzqS3L9Dg6D0W+Y9Af2sv8xr+e/njZPaFmPdHnxCcE5kOWmQmNgDrMmf9D2+ZHlQcNIQhCmnjRgJ75/uZAR0ApmZrwJZ8PTVT8x3pOxLY8tsqoGfO8lkNj6BUQEUX3jpqkx/9+fcp9SXuMuOwWC1opw==" />
</div>
<header class="navbar navbar-light navbar-static-top bd-navbar">
<div class="container text-center">
<button class="navbar-toggler hidden-sm-up pull-xs-right" type="button" data-toggle="collapse" data-target="#navbar-header" aria-controls="navbar-header">
&#9776;
</button>
<a id="ctl00_HyperLink1" class="navbar-brand" href="https://www.ergodotisi.com/"><img id="ctl00_Image1" src="images/JobsinCyprus.png" alt="Jobs in Cyprus by Ergodotisi.com" /></a>
<div id='div-gpt-ad-1504700248152-2' style='float:left;margin:0 auto;text-align:left' class="topbannerheight">
<script>
            googletag.cmd.push(function () { googletag.display('div-gpt-ad-1504700248152-2'); });
        </script>
</div>
<ul class="nav navbar-nav pull-xs-right hidden-xs">
<li class="nav-item">
<a id="ctl00_LoginView1_TabLogin" class="nav-btn nav-btn-orange font-lato" style="color:white"><span class="fa fa-lock fa-2x"></span>
ΕΙΣΟΔΟΣ</a>
</li>
<li class="nav-item">
<a href="https://www.ergodotisi.com/RegisterUser.aspx?productid=0" class="nav-btn nav-btn-blue font-lato"><span class="fa fa-user fa-2x"></span>
ΕΓΓΡΑΦΗ ΧΡΗΣΤΩΝ</a>
</li>
</ul>
<script id="dxis_26536524" src="/DXR.axd?r=1_230,1_134,1_223,1_168,1_131,1_215,1_213,1_221,1_205,1_214-ziGyd" type="text/javascript"></script><div id="ctl00_ASPxPopupControl1_PW-1" class="dxpcLite dxpclW" style="width:200px;cursor:default;z-index:10000;display:none;visibility:hidden;">
<div class="dxpc-mainDiv dxpc-shadow">
<div class="dxpc-contentWrapper">
<div class="dxpc-content">
<div id="ctl00_ASPxPopupControl1_Login2_Panel1" onkeypress="javascript:return WebForm_FireDefaultButton(event, &#39;ctl00_ASPxPopupControl1_Login2_LoginButton&#39;)">
<table cellpadding="1" cellspacing="0" style="border-collapse: collapse; text-align: left; width: 100%">
<tr>
<td>
<label for="ctl00_ASPxPopupControl1_Login2_UserName" id="ctl00_ASPxPopupControl1_Login2_UserNameLabel" class="font-lato">Ηλεκτρονική διεύθυνση:</label>
</tr>
<tr>
<td>
<input name="ctl00$ASPxPopupControl1$Login2$UserName" type="text" id="ctl00_ASPxPopupControl1_Login2_UserName" class="inputcontrol" style="width:100%;" />
<span id="ctl00_ASPxPopupControl1_Login2_UserNameRequired" title="Συμπληρώστε την ηλεκτρονική σας διεύθυνση" style="visibility:hidden;">*</span>
</td>
</tr>
<tr>
<td>
<label for="ctl00_ASPxPopupControl1_Login2_Password" id="ctl00_ASPxPopupControl1_Login2_PasswordLabel" class="font-lato">Κωδικός πρόσβασης:</label>
</td>
</tr>
<tr>
<td>
<input name="ctl00$ASPxPopupControl1$Login2$Password" type="password" id="ctl00_ASPxPopupControl1_Login2_Password" class="inputcontrol" style="width:100%;" />
<span id="ctl00_ASPxPopupControl1_Login2_PasswordRequired" title="Συμπληρώστε τo κωδικό πρόσβασης." style="visibility:hidden;">*</span>
<br />
</td>
</tr>
<tr>
<td align="center" style="color: Red;">
</td>
</tr>
<tr>
<td align="center">
<input type="submit" name="ctl00$ASPxPopupControl1$Login2$LoginButton" value="ΕΙΣΟΔΟΣ" onclick="javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$ASPxPopupControl1$Login2$LoginButton&quot;, &quot;&quot;, true, &quot;loginPage&quot;, &quot;&quot;, false, false))" id="ctl00_ASPxPopupControl1_Login2_LoginButton" class="nav-btn nav-btn-orange font-lato" style="border-style:None;" />
</td>
</tr>
<tr>
<td>
<br />
<a id="ctl00_ASPxPopupControl1_Login2_ASPxHyperLink2" href="https://www.ergodotisi.com/forgotpassword.aspx" style="color:#5D2D8D;font-size:Medium;">Ξεχάσατε τον κωδικό?</a>
</td>
</tr>
</table>
</div>
</div>
</div>
</div>
</div><table id="ctl00_ASPxPopupControl1_LP" class="dxpcLoadingPanel dxlpLoadingPanel" cellspacing="0" cellpadding="0" style="border-collapse:collapse;left:0px;top:0px;z-index:30000;display:none;">
<tr>
<td class="dx" style="padding-right:0px;"><img class="dxlp-loadingImage dxlp-imgPosLeft" src="/DXR.axd?r=1_37-ziGyd" alt="" align="middle" /></td><td class="dx" style="padding-left:0px;"><span id="ctl00_ASPxPopupControl1_TL">Loading&hellip;</span></td>
</tr>
</table><div id="ctl00_ASPxPopupControl1_LD" class="dxpcLoadingDiv dxlpLoadingDiv dx-ft" style="left:0px;top:0px;z-index:29999;display:none;position:absolute;">
</div><script id="dxss_375342899" type="text/javascript">
<!--
ASPx.AddHoverItems('ctl00_ASPxPopupControl1',[[['dxpc-pinBtnHover'],[''],['HPB-1']]]);
ASPx.AddSelectedItems('ctl00_ASPxPopupControl1',[[['dxpc-pinBtnChecked'],[''],['HPB-1']]]);

var dxo = new ASPxClientPopupControl('ctl00_ASPxPopupControl1');
dxo.InitGlobalVariable('PopupLogin');
dxo.callBack = function(arg) { WebForm_DoCallback('ctl00$ASPxPopupControl1',arg,ASPx.Callback,'ctl00_ASPxPopupControl1',ASPx.CallbackError,true); };
dxo.uniqueID = 'ctl00$ASPxPopupControl1';
dxo.appearAfter=100;
dxo.popupAnimationType='slide';
dxo.closeAnimationType='slide';
dxo.popupHorizontalAlign='RightSides';
dxo.popupVerticalAlign='Below';
dxo.isPopupPositionCorrectionOn=false;
dxo.defaultWindowPopupElementIDList=['ctl00_LoginView1_TabLogin'];
dxo.AfterCreate();

//-->
</script>
<div class="dxmLite_Aqua dxm-ltr">
<div PopupAnimationType="Slide" id="ctl00_ASPxPopupMenu1" style="z-index:20000;display:none;">
<div class="dxm-popupMain dxm-shadow dxm-popup">
<ul class="dx dxm-noImages dxm-gutter">
<li class="dxm-item"><a class="dxm-content dxm-hasText dx" href="https://www.ergodotisi.com/MyAccount/CVEntry.aspx"><span class="dx-vam">Βιογραφικό μου</span></a><b class="dx-clear"></b></li><li class="dxm-spacing"></li><li class="dxm-item"><a class="dxm-content dxm-hasText dx" href="https://www.ergodotisi.com/MyAccount/ChangePassword.aspx"><span class="dx-vam">Αλλαγή κωδικού</span></a><b class="dx-clear"></b></li><li class="dxm-spacing"></li><li class="dxm-item"><a class="dxm-content dxm-hasText dx" href="https://www.ergodotisi.com/MyAccount/Applications.aspx"><span class="dx-vam">Αιτήσεις μου</span></a><b class="dx-clear"></b></li><li class="dxm-spacing"></li><li class="dxm-item"><a class="dxm-content dxm-hasText dx" href="https://www.ergodotisi.com/MyAccount/purchase.aspx"><span class="dx-vam">Συναλλαγές</span></a><b class="dx-clear"></b></li><li class="dxm-spacing"></li><li class="dxm-item"><div class="dxm-content dxm-hasText">
<span class="dx-vam">Γλώσσα Προτίμησης</span>
</div><b class="dx-clear"></b></li><li class="dxm-spacing"></li><li class="dxm-item dxm-tmpl">
<hr />
&nbsp; &nbsp;&nbsp;<br />
<a id="ctl00_ASPxPopupMenu1_ITCNT5_LoginStatus1" href="javascript:__doPostBack(&#39;ctl00$ASPxPopupMenu1$ITCNT5$LoginStatus1$ctl02&#39;,&#39;&#39;)" style="color:#FD8204;font-weight:bold;">Login</a>
<b class="dx-clear"></b></li>
</ul>
</div>
</div>
</div><script id="dxss_885844908" type="text/javascript">
<!--
ASPx.AddHoverItems('ctl00_ASPxPopupMenu1',[[[''],[''],['DXME_']],[['dxm-hovered',''],['',''],['DXI0_','DXI1_','DXI2_','DXI3_','DXI4_'],['','T']]]);
ASPx.AddDisabledItems('ctl00_ASPxPopupMenu1',[[['dxm-disabled'],[''],['DXI0_','DXI1_','DXI2_','DXI3_','DXI4_','DXI5_'],['','T']]]);

var dxo = new ASPxClientPopupMenu('ctl00_ASPxPopupMenu1');
dxo.InitGlobalVariable('PopupMenu1');
dxo.uniqueID = 'ctl00$ASPxPopupMenu1';
dxo.renderData={'':[[0],[1],[2],[3],4,5]};
dxo.appearAfter=0;
dxo.subMenuFIXOffset=2;
dxo.subMenuFIYOffset=-2;
dxo.subMenuLIXOffset=2;
dxo.subMenuLIYOffset=-2;
dxo.subMenuXOffset=2;
dxo.subMenuYOffset=-2;
dxo.rootSubMenuFIXOffset=2;
dxo.rootSubMenuFIYOffset=-2;
dxo.rootSubMenuLIXOffset=2;
dxo.rootSubMenuLIYOffset=-2;
dxo.rootSubMenuXOffset=2;
dxo.rootSubMenuYOffset=-2;
dxo.CreateItems([{'name':'CV'},{'name':'ChangePassword'},{'name':'Applications'},{'name':'Purchase'},{'name':'Language'},{}]);
dxo.popupAction='MouseOver';
dxo.closeAction='MouseOut';
dxo.popupHorizontalAlign='Center'
dxo.popupVerticalAlign='Below';
dxo.AfterCreate();

//-->
</script>
</div>
</header> 
<nav class="navbar navbar-purple navbar-toggleable-xs collapse" aria-expanded="false" id="navbar-header">
<div class="container clearfix">
<ul class="nav navbar-nav clearfix">
<li class="nav-item-tab pull-xs-left hidden-xs">
<a id="ctl00_HyperLink2" class="nav-link" href="https://bit.ly/ergrm" target="_blank"><img id="ctl00_Image2" class="ImgInstagramClass" src="new_brand_design/img/instagram.png" /></a>
</li>
<li class="nav-item-tab pull-xs-left hidden-xs">
<a id="ctl00_HyperLink3" class="nav-link" href="https://www.facebook.com/ErgodotisiOfficial/" target="_blank"><img id="ctl00_Image3" src="new_brand_design/img/facebook.png" /></a>
</li>
<li class="nav-item-tab">
<a id="ctl00_HyperLink6" class="nav-link" href="https://www.ergodotisi.com/">ΑΡΧΙΚΗ</a>
</li>
<li class="nav-item-tab seprator">
<a id="ctl00_HyperLink7" class="nav-link" href="https://www.ergodotisi.com/SearchResults.aspx?q=">ΤΕΛΕΥΤΑΙΕΣ ΑΝΑΡΤΗΣΕΙΣ</a>
</li>
<li class="nav-item-tab seprator">
<a id="ctl00_HyperLink8" class="nav-link" href="https://www.ergodotisi.com/Companies.aspx">ΕΤΑΙΡΕΙΕΣ</a>
</li>
<li class="nav-item-tab seprator pricing-li" onmouseover="show()" onmouseout="hide()">
<span id="ctl00_HyperLinkPricing" class="nav-link pricing-hover">ΑΓΟΡΑ ΥΠΗΡΕΣΙΑΣ</span>
<ul id="pricingmenu" class="select-option-inner select-language-inner active" style="position:absolute;z-index:1000;visibility:hidden">
<li>
<a id="ctl00_HyperLinkCyprus" class="nav-link" href="https://www.ergodotisi.com/pricing">ΓΙΑ ΚΥΠΡΟ</a>
</li>
<li>
<a id="ctl00_HyperLinkGreece" class="nav-link" href="https://www.ergodotisi.gr/pricing">ΓΙΑ ΕΛΛΑΔΑ</a></li>
</ul>
</li>
<li class="nav-item-tab seprator">
<a id="ctl00_HyperLink9" class="nav-link" href="http://blog.ergodotisi.com/?_ga=1.21024126.416805199.1458281157" target="_blank">BLOG</a>
</li>
<li class="nav-item-tab seprator">
<a id="ctl00_HyperLink5" class="nav-link" href="https://www.ergodotisi.com/contactus.aspx">ΕΠΙΚΟΙΝΩΝΙΑ</a>
</li>
<li class="nav-item-tab">
<a id="ctl00_HyperLink4" class="hidden-sm-up nav-btn nav-btn-orange" href="https://www.ergodotisi.com/Employers.aspx">ΕΙΣΟΔΟΣ</a>
<a id="ctl00_HyperLink11" class="hidden-sm-down nav-btn nav-btn-orange" href="https://www.ergodotisi.com/Employers.aspx"><span class='fa fa-lock fa-2x'></span>ΕΓΓΡΑΦΗ ΓΙΑ ΕΡΓΟΔΟΤΕΣ</a>
</li>
<li class="nav-item-tab" style="float:right"><a class="nav-link" style="padding-right:1px" title="Θέσεις εργασίας στην Κύπρο" href="https://www.ergodotisi.com/en/privacy.aspx"><img src="/new_brand_design/img/en-US.jpg" height="12px" runat="server" alt="Jobs in Cyprus" /></a></li><li class="nav-item-tab" style="float:right"><a class="nav-link" style="padding-right:1px" disabled="disabled" title="Θέσεις εργασίας στην Κύπρο" href="https://www.ergodotisi.com/privacy.aspx"><img src="/new_brand_design/img/el-GR.jpg" height="20px" runat="server" alt="Jobs in Cyprus" /></a></li>
</ul>
</div>
</nav>
<div class="container">
<div class="row">
<div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
</div>
</div>
</div>
<br /><br />
<div class="container">
<div class="row">
<div class="col-lg-12 col-sm-12 col-xs-12">
<h1> Πολιτική Απορρήτου</h1>
<p><br /></p><p><span style="font-size: 12pt;"><span style="text-decoration: underline;"><strong>1. INTRODUCTION</strong></span></span></p><p>This Privacy Policy aims to give you information on how Melior Capital LTD collects, uses, discloses and processes your personal data through your use of the website ergodotisi.com (hereinafter referred to as “the Website” or “Ergodotisi”) and the means by which this is done. The Privacy Policy acts as a means of notifying the website visitors of their rights in accordance with local law and the EU General Data Protection Regulation (EU) 2016/679.&nbsp;</p><p>This Website is not intended for children and we do not knowingly collect data relating to children.</p><p>Melior Capital LTD is committed to protecting your privacy and developing technology that gives you the most powerful and safe online experience.</p><p>&nbsp;By accessing, browsing and/or using this Website, you consent to the data practices described in this Privacy Policy and acknowledge that you have read, understood, and agree, to be bound by these terms conditions, and notices contained herein and to comply with all applicable laws and regulations.</p><p>For the purposes of this Privacy Policy “Personal Data” refers to all&nbsp; data which relates to a living individual who can be identified from such data such as for instance, name, address and/or identification number. It does not include data where the identity has been removed (anonymous data).</p><p><br /></p><p><span style="font-size: 12pt;"><span style="text-decoration: underline;"><strong>2. WHO WE ARE</strong></span></span></p><p>Ergodotisi is owned and operated by Melior Capital LTD, a limited liability company registered in the Republic of Cyprus with registration number ΗΕ 305965 and registered address at 8 Michalaki Karaoli Street, Anemolmylos Building, 3rd floor, 1095 Nicosia, Cyprus.&nbsp;</p><p>Ergodotisi is a job search related platform used for finding a job in the Republic of Cyprus. It aims to contribute in the professional success of its users and companies and assist companies in finding suitable professionals and professionals in finding suitable companies.</p><p>If you have any questions about this Privacy Policy , including any requests to exercise your legal rights, please contact us at the details set out below.</p><p><span style="text-decoration: underline;">Contact Details: Ergodotisi.com Team</span></p><p><span style="text-decoration: underline;">Address: Spyrou Kyprianou 37, ΤΚ 4154, Λεμεσός, Limassol 4154</span></p><p>Email address: <a href="/cdn-cgi/l/email-protection" class="__cf_email__" data-cfemail="0861666e67486d7a6f676c677c617b61266b6765">[email&#160;protected]</a></p><p>Telephone number: (+357) 25 55 87 44</p><p>&nbsp;You have the right to make a complaint at any time to the Office of the Commissioner for Data Protection, the supervisory authority for data protection issues in the Republic of Cyprus&nbsp; (<a href="http://www.dataprotection.gov.cy/dataprotection/dataprotection.nsf/home_en/home_en?opendocument" target="_blank">Click here to see details</a>). We would, however, appreciate the chance to deal with your concerns before you approach the Commissioner for Data Protection therefore please contact us in the first instance.</p><p><br /></p><p><strong><span style="text-decoration: underline;"><span style="font-size: 12pt;">3. TYPE AND METHOD OF COLLECTION</span></span></strong></p><p>The data we collect consists of what the User&nbsp; voluntarily makes available to us when accessing the Website (e.g. email address) or sending&nbsp; Curriculum Vitae (“CV”)&nbsp; (e.g. name, surname. telephone, etc.).&nbsp;</p><p>Overall we collect personally identifiable information, such as your e-mail address, name, home or work address and telephone number.</p><p>We may also collect anonymous demographic information, which is not unique to you, such as your ZIP code, age, gender, preferences, interests and favorites. There is also information about your computer hardware and software that is automatically collected by the Website. This information can include: your IP address, browser type, domain names, access times and referring Website addresses.</p><p>Ergodotisi&nbsp; encourages you to review the privacy statements of Websites you choose to link to from ergodotisi.com so that you can understand how those Websites collect, use and share your information. Melior Capital Lts and/or Ergodotisi is not responsible for the privacy statements or other content on websites outside of ergodotis.com</p><p>We do not collect any Special Categories of Personal Data about you (this includes details about your race or ethnicity, religious or philosophical beliefs, sex life, sexual orientation, political opinions, trade union membership, information about your health and genetic and biometric data). Nor do we collect any information about criminal convictions and offences.</p><p>The&nbsp; Website consists of &quot;cookies&quot; to help you personalize your online experience. A cookie is a text file that is placed on your hard disk by a Web page server. Cookies cannot be used to run programs or deliver viruses to your computer. Cookies are uniquely assigned to you, and can only be read by a web server in the domain that issued the cookie to you. One of the primary purposes of cookies is to provide a convenience feature to save you time. The purpose of a cookie is to tell the Web server that you have returned to a specific page. For example, if you register with the Webiste or services, a cookie helps us&nbsp; recall your specific information on subsequent visits. This simplifies the process of recording your personal information, such as billing addresses, shipping addresses, and so on. When you return to the Website, the information you previously provided can be retrieved, so you can easily use the Webiste features that you customized. You have the ability to accept or decline cookies.</p><p>Most Web browsers automatically accept cookies, but you can usually modify your browser setting to decline cookies if you prefer. If you choose to decline cookies, you may not be able to fully experience the interactive features of the Website.</p><p><br /></p><p><span style="font-size: 12pt;"><span style="text-decoration: underline;"><strong>4. USE OF THE DATA</strong></span></span></p><p>We will only use your personal data when the law allows us to. Most commonly, we will use your personal data in the following circumstances:</p><ul><li>Where we need to perform the contract we are about to enter into or have entered into with you.</li></ul><ul><li>Where it is necessary for our legitimate interests. Legitimate Interest means the interest of our business in conducting and managing our business to enable us to give you the best service/product and the best and most secure experience. We make sure we consider and balance any potential impact on you (both positive and negative) and your rights before we process your personal data for our legitimate interests. We do not use your personal data for activities where our interests are overridden by the impact on you (unless we have your consent or are otherwise required or permitted to by law).(Where we need to comply with a legal or regulatory obligation.</li></ul><ul><li>Where it is necessary for compliance with a legal or regulatory obligation that we are subject to.</li></ul><p>&nbsp;Melior Capital Ltd uses the data it collects to inform users about new, to modify the services therein, improve the performance of the Website, to send information and professional material, if the user has consented to this, as well as to collect statistics. With respect to the Personal Data collected from the CVs uploaded by the Users (e.g. name, telephone, address, etc), Melior Capital Ltd&nbsp; retains the right both to collect and dispose it - promote it to interested employers - businesses, agencies, organizations or human resources consultants who are subscribers.</p><p>In addition, Google, as a third party vendor, uses cookies to run ads on the Website. The use of DART cookies from Google&nbsp; allows it to display ads to ergodotisi users based on their visits to our Website and other Websites on the Internet.</p><p>Melior Capital Ltd also uses your personally identifiable information to inform you of other products or services available from Melior Capital Ltd and its affiliates.</p><p>In the instance, that you will be communicated by an affiliate&nbsp; for the purposes of direct marketing, prior to such communication being affected you will be requested to give&nbsp; your free, explicit and specific consent to be expressed in a clear and&nbsp; conscious manner. Such consent will be requested to be given by you when you will be visiting the Website of the said related companies and ticking the relevant box referring to the provision of direct marketing services.</p><p><br /></p> <p><span style="font-size: 12pt;"><span style="text-decoration: underline;"><strong>5. ACCESS TO THE DATA/YOUR RIGHTS AS USER ON THE WEBSITE</strong></span></span></p><p>Under certain circumstances, you have rights under data protection laws in relation to your Personal Data. Such rights are as follows:</p><ul><li><strong>Request access</strong>&nbsp;to your Personal Data (commonly known as a “data subject access request”). This enables you to receive a copy of the personal data we hold about you and to check that we are lawfully processing it.</li></ul><ul><li><span><strong>Request correction</strong>&nbsp;</span><span>of the Personal Data that we hold about you. This enables you to have any incomplete or inaccurate data we hold about you corrected, though we may need to verify the accuracy of the new data you provide to us.</span></li></ul><ul><li><span><strong>Request erasure</strong>&nbsp;</span><span>of your Personal Data. This enables you to ask us to delete or remove personal data where there is no good reason for us continuing to process it. You also have the right to ask us to delete or remove your personal data where you have successfully exercised your right to object to processing (see below), where we may have processed your information unlawfully or where we are required to erase your personal data to comply with local law. Note, however, that we may not always be able to comply with your request of erasure for specific legal reasons which will be notified to you, if applicable, at the time of your request.</span></li></ul><ul><li><strong>Object to processing</strong>&nbsp;of your Personal Data where we are relying on a legitimate interest (or those of a third party) and there is something about your particular situation which makes you want to object to processing on this ground as you feel it impacts on your fundamental rights and freedoms. You also have the right to object where we are processing your personal data for direct marketing purposes. In some cases, we may demonstrate that we have compelling legitimate grounds to process your information which override your rights and freedoms.</li></ul><ul><li><span><strong>Request restriction of processing</strong>&nbsp;</span><span>of your Personal Data. This enables you to ask us to suspend the processing of your personal data in the following scenarios: (a) if you want us to establish the data’s accuracy; (b) where our use of the data is unlawful but you do not want us to erase it; (c) where you need us to hold the data even if we no longer require it as you need it to establish, exercise or defend legal claims; or (d) you have objected to our use of your data but we need to verify whether we have overriding legitimate grounds to use it.</span></li></ul><ul><li><span><strong>Request the transfer</strong>&nbsp;</span><span>of your Personal Data to you or to a third party. We will provide to you, or a third party you have chosen, your personal data in a structured, commonly used, machine-readable format. Note that this right only applies to automated information which you initially provided consent for us to use or where we used the information to perform a contract with you.</span></li></ul><ul><li><span><strong>Withdraw consent at any time</strong>&nbsp;</span><span>where we are relying on consent to process your Personal Data. However, this will not affect the lawfulness of any processing carried out before you withdraw your consent. If you withdraw your consent, we may not be able to provide certain products or services to you. We will advise you if this is the case at the time you withdraw your consent.</span></li></ul><p>&nbsp;It is noted that upon the registration of the User on the Website and after providing his e-mail address, the User automatically becomes a recipient of the Website’s newsletter. The User can Opt-Out from receiving such newsletter by clicking on the link therein.</p><p><br /></p><p><span style="font-size: 12pt;"><span style="text-decoration: underline;"><strong>6. CV BANK</strong></span></span></p><p>The User may modify, update, or delete his CV through his or her account at any time. Deletion means that third parties will not be able to access it. Melior Capital Ltd via Ergodotisi provides access to the CV Bank to its subscribers only, who can access it using the confidential code provided.</p><p>Seek4U is service, where a company is able to search, spot and approach the perfect candidate for the position, using town, categories, skills and experience search criteria. The time duration of this service is one year. Users of Ergodotisi have the option of creating and registering their CVs to the Seek4U bank. Access to full CV details is only available to companies that have proceeded with the relevant purchase (Seek4U CV). All companies may have access to the Seek4U CV, but without showing any personal information and contact information or attachments.</p><p><br /></p><p><span style="font-size: 12pt;"><span style="text-decoration: underline;"><strong>7. DISPOSAL TO THIRD PARTIES</strong></span></span></p><p>Except as specifically set forth in this Privacy Policy , we do not share your personal information with any non-affiliated third party without your free, explicit and specific consent and in any event when your personal information is collected we will notify you of the recipient or the categories of recipients of such information.&nbsp; Furthermore, we will promptly notify you when the said data are to be first announced to a third party. We may disclose aggregate information, such as demographic information, and our statistical analyses to third parties, including advertisers or other business partners. This aggregate information does not include your personal information.</p><p><br /></p><p><span style="text-decoration: underline;"><strong><span style="font-size: 12pt;">8. SECURITY</span></strong></span></p><p>The security of your personal information is important to us and this is why we maintain physical, electronic, and procedural safeguards to secure your personal information. Melior Capital Ltd and/or Ergodotisi secures your personal information from unauthorized access, use or disclosure.</p><p>This Website has security measures in place to protect the loss, misuse and alteration of the information under our control. Such measures include regular security reviews, upgrades, and backups. We use our best efforts to maintain the security and reliability of our infrastructure; however, they are provided &quot;as is&quot; without any express or implied warranty of any kind including warranties of merchantability, reliability, or fitness for a particular purpose. We offer no assurance of uninterrupted or error free service, nor does Melior Capital Ltd warrant the accuracy or completeness of any service. In no event shall Melior Capital Ltd be held liable for any damages whatsoever (including, without limitation, damages for loss of profits, business interruption, loss of information) arising out of the use or inability to use the Website.</p><p><br /></p><p><span style="font-size: 12pt;"><span style="text-decoration: underline;"><strong>9. INTERNATIONAL TRANSFERS</strong></span></span>&nbsp;&nbsp;</p><p>In the instance that your Personal Data will be transferred out of the EEA, we ensure a similar degree of protection is afforded to it by ensuring at least one of the following safeguards is implemented:</p><ul><li>We will only transfer your personal data to countries that have been deemed to provide an adequate level of protection for personal data by the European Commission in accordance with Article 46 of the GDPR.</li></ul><ul><li>Where we use certain service providers, we may use specific contracts approved by the European Commission which give personal data the same protection it has in Europe.</li></ul><p><br /></p><p><span style="text-decoration: underline;"><strong><span style="font-size: 12pt;">10. DATA RETENTION</span></strong></span></p><p>We will only retain your personal data for as long as necessary to fulfil the purposes we collected it for, including for the purposes of satisfying any legal, accounting, or reporting requirements.</p><p>To determine the appropriate retention period for personal data, we consider the amount, nature, and sensitivity of the personal data, the potential risk of harm from unauthorised use or disclosure of your personal data, the purposes for which we process your personal data and whether we can achieve those purposes through other means, and the applicable legal requirements.</p><p><br /></p><p><span style="text-decoration: underline;"><strong><span style="font-size: 12pt;">11. CHANGES TO THIS STATEMENT</span></strong></span></p><p>Melior Capital Ltd and Ergodotisi will occasionally update this Privacy Policy to reflect company and customer feedback. You will be notified of any changes to this Privacy Policy but we encourage you&nbsp; to periodically review this Privacy Policy so as to be informed of how your information is protected.</p><p><br /></p><p><span style="text-decoration: underline;"><strong><span style="font-size: 12pt;">12. TIME LIMIT TO RESPOND</span></strong></span></p><p>We try to respond to all legitimate requests within one month. Occasionally it may take us longer than a month if your request is particularly complex or you have made a number of requests. In this case, we will notify you and keep you updated.</p><p><br /></p> <p><span style="text-decoration: underline;"><strong><span style="font-size: 12pt;">13. THIRD-PARTY MARKETING</span></strong></span>&nbsp;&nbsp;</p><p>We will get your express opt-in consent before we share your personal data with any company outside Melior Capital Ltd for marketing purposes.</p><p><br /></p>
</div>
</div>
</div>
<footer class="footer">
<div class="container relative">

<div class="row">
<aside class="col-md-3 text-center">
<h3>ΥΠΟΨΗΦΙΟΙ</h3>
<ul class="f-list-order">
<li class="clearfix" style="text-align:left">
<a href="https://www.ergodotisi.com/RegisterUser.aspx?productid=0" id="ctl00_LocalizeLinkRegisterLink" style="text-decoration:none">Δημιουργία Λογαριασμού</a>
</li>
<li class="clearfix" style="text-align:left">
<a href="https://www.ergodotisi.com/SearchResults.aspx?q=" style="text-decoration:none">Νεότερες θέσεις εργασίας</a>
</li>
<li class="clearfix" style="text-align:left">
<a href="https://www.ergodotisi.com/Companies.aspx" style="text-decoration:none">Ανά εταιρεία</a>
</li>
</ul>
</aside>
<aside class="col-md-3 text-center">
<h3>ΕΤΑΙΡΕΙΕΣ</h3>
<ul class="f-list-order">
<li class="clearfix" style="text-align:left">
<a href="https://www.ergodotisi.com/EmployersLogin.aspx" style="text-decoration:none">Δημιουργία Λογαριασμού</a>
</li>
<li class="clearfix" style="text-align:left">
<a href="https://www.ergodotisi.com/pricing.aspx#faqs" style="text-decoration:none">FAQ</a>
</li>
<li class="clearfix" style="text-align:left">
<a href="https://www.ergodotisi.com/Portal/AddJob.aspx?Country=1" style="text-decoration:none">Δημοσίευση Αγγελιών</a>
</li>
</ul>
</aside>
<aside class="col-md-3 text-center">
<h3>ΣΧΕΤΙΚΑ ΜΕ ΕΜΑΣ</h3>
<ul class="f-list-order">
<li class="clearfix" style="text-align:left">
<a href="https://www.ergodotisi.com/privacy.aspx" style="text-decoration:none">Πολιτική Απορρήτου</a>
</li>
<li class="clearfix" style="text-align:left">
<a href="https://www.ergodotisi.com/conditions.aspx" style="text-decoration:none">Όροι και προϋποθέσεις</a>
</li>
<li class="clearfix" style="text-align:left">
<a href="http://online.fliphtml5.com/wbnd/uech/#p=1" style="text-decoration:none" target="_blank">Περιοδικό Employers – Εργοδότες 2016</a>
</li>
</ul>
<h3>ΟΙ ΙΣΤΟΣΕΛΙΔΕΣ ΜΑΣ</h3>
<ul class="f-list-order">
<li class="clearfix" style="text-align:left">
<a href="https://www.portofolakis.com/" style="text-decoration:none" target="_blank">Προσφορές στην Κύπρο</a><span style="font-size:12px"> - Portofolakis.com</span>
</li>
<li class="clearfix" style="text-align:left">
<a href="https://www.deliveryman.com.cy/" style="text-decoration:none" target="_blank">Online Delivery Φαγητού και Ποτών</a><span style="font-size:12px"> - Deliveryman.com.cy</span>
</li>
</ul>
</aside>
<aside class="col-md-3 text-center">
<h3><a href="https://www.ergodotisi.com/" style="text-decoration:none;color:#fd8204">ΘΕΣΕΙΣ ΕΡΓΑΣΙΑΣ ΣΤΗΝ ΚΥΠΡΟ</a></h3>
<ul class="f-list-order">
<li class="clearfix" style="text-align:left">
<a id="ctl00_LinkCity1" href="https://www.ergodotisi.com/jobs-in-nicosia" style="text-decoration:none">Θέσεις εργασίας στη Λευκωσία</a>
</li>
<li class="clearfix" style="text-align:left">
<a id="ctl00_LinkCity2" href="https://www.ergodotisi.com/jobs-in-limassol" style="text-decoration:none">Θέσεις εργασίας στη Λεμεσό</a>
</li>
<li class="clearfix" style="text-align:left">
<a id="ctl00_LinkCity3" href="https://www.ergodotisi.com/jobs-in-larnaka" style="text-decoration:none">Θέσεις εργασίας στη Λάρνακα</a>
</li>
<li class="clearfix" style="text-align:left">
<a id="ctl00_LinkCity4" href="https://www.ergodotisi.com/jobs-in-paphos" style="text-decoration:none">Θέσεις εργασίας στην Πάφο</a>
</li>
<li class="clearfix" style="text-align:left">
<a id="ctl00_LinkCity5" href="https://www.ergodotisi.com/jobs-in-famagusta" style="text-decoration:none">Θέσεις εργασίας στην Αμμόχωστο</a>
</li>
</ul>
</aside>
</div>
<div class="row">
<div class="social">
<a href="https://bit.ly/ergrm" target="_blank"><img src="/new_brand_design/img/instagram.png" alt="" style="border-radius:9px" /></a>
<a href="https://www.facebook.com/ErgodotisiOfficial/" target="_blank"><img src="/new_brand_design/img/facebook.png" alt="" /></a>
</div>
</div>
<div class="row">
<div class="pai">
<ul class="pai-list-order">
<li class="">
<a href="https://www.ergodotisi.com/conditions.aspx">ΟΡΟΙ ΧΡΗΣΗΣ</a>
</li>
<li class="">
<a href="https://www.ergodotisi.com/contactus.aspx">ΕΠΙΚΟΙΝΩΝΙΑ</a>
</li>
<li class="">
<a href="https://www.ergodotisi.com/jobpostingconditions.aspx">ΠΟΛΙΤΙΚΗ ΓΙΑ ΑΓΓΕΛΙΕΣ</a>
</li>
</ul>
</div>
</div>
</div>
<div class="sub-footer">
<div class="container relative">
<div class="row">
<div class="col-xs-12 col-sm-4">
<a href="#" class="pull-left">
<img src="/new_brand_design/img/bank-card-logo.png">
</a>
</div>
<div class="col-xs-12 col-sm-4">
<a href='https://www.ergodotisi.com/' class="text-center">Copyright ergodotisi.com All Rights Reserved</a>
</div>
<div class="col-xs-12 col-sm-4">
<a class="text-orange" href="http://www.melior.com.cy" target="_blank">DEVELOPED & HOSTED BY melior</a>
</div>
</div>
</div>
</div>
<a href="javascript:void(0);" id="scroll" title="Scroll to Top" style="display: none;" class="go-to-top"><img src="new_brand_design/img/top.png" /></a>
</footer>
<script data-cfasync="false" src="/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script><script src="https://code.jquery.com/jquery-2.2.3.min.js" crossorigin="anonymous"></script>
<script type='text/javascript'>
                    $(document).ready(function(){ 
                        $(window).scroll(function(){ 
                            if ($(this).scrollTop() > 100) { 
                                $('#scroll').fadeIn(); 
                            } else { 
                                $('#scroll').fadeOut(); 
                            } 
                        }); 
                        $('#scroll').click(function(){ 
                            $("html, body").animate({ scrollTop: 0 }, 600); 
                            return false; 
                        });
                       


                    });
           </script>
<script type="text/javascript">
//<![CDATA[
var Page_Validators =  new Array(document.getElementById("ctl00_ASPxPopupControl1_Login2_UserNameRequired"), document.getElementById("ctl00_ASPxPopupControl1_Login2_PasswordRequired"));
//]]>
</script>
<script type="text/javascript">
//<![CDATA[
var ctl00_ASPxPopupControl1_Login2_UserNameRequired = document.all ? document.all["ctl00_ASPxPopupControl1_Login2_UserNameRequired"] : document.getElementById("ctl00_ASPxPopupControl1_Login2_UserNameRequired");
ctl00_ASPxPopupControl1_Login2_UserNameRequired.controltovalidate = "ctl00_ASPxPopupControl1_Login2_UserName";
ctl00_ASPxPopupControl1_Login2_UserNameRequired.errormessage = "*";
ctl00_ASPxPopupControl1_Login2_UserNameRequired.validationGroup = "loginPage";
ctl00_ASPxPopupControl1_Login2_UserNameRequired.evaluationfunction = "RequiredFieldValidatorEvaluateIsValid";
ctl00_ASPxPopupControl1_Login2_UserNameRequired.initialvalue = "";
var ctl00_ASPxPopupControl1_Login2_PasswordRequired = document.all ? document.all["ctl00_ASPxPopupControl1_Login2_PasswordRequired"] : document.getElementById("ctl00_ASPxPopupControl1_Login2_PasswordRequired");
ctl00_ASPxPopupControl1_Login2_PasswordRequired.controltovalidate = "ctl00_ASPxPopupControl1_Login2_Password";
ctl00_ASPxPopupControl1_Login2_PasswordRequired.errormessage = "*";
ctl00_ASPxPopupControl1_Login2_PasswordRequired.validationGroup = "loginPage";
ctl00_ASPxPopupControl1_Login2_PasswordRequired.evaluationfunction = "RequiredFieldValidatorEvaluateIsValid";
ctl00_ASPxPopupControl1_Login2_PasswordRequired.initialvalue = "";
//]]>
</script>
<script type="text/javascript">
//<![CDATA[

var callBackFrameUrl='/WebResource.axd?d=DOG1Nl3DgQkNPDafhAbOBdncKnAEyLqDxqvlLSoEaqk6f1a9v2DkSQVq07Q1kx3hWUhi9_KoY9q6INTozlr-YqPH-yk1&t=636744885301435895';
WebForm_InitCallback();
var Page_ValidationActive = false;
if (typeof(ValidatorOnLoad) == "function") {
    ValidatorOnLoad();
}

function ValidatorOnSubmit() {
    if (Page_ValidationActive) {
        return ValidatorCommonOnSubmit();
    }
    else {
        return true;
    }
}
        //]]>
</script>
</form>

</body>
</html>
